import re

WHITELIST = [
    "GIMP",
    "Spring",
    "dotnet",
    "kernel",
]

# r'\b\.NET\b' does not match properly because word boundary \b does not cooperate well
# with dot.
WHITELIST_SPECIAL_CASES = [r"(?:\W|^)\.NET\b"]

BLACKLIST = [
    r"(HPE|Hewlett Packard Enterprise).*(IceWall|FlexNetwork|FlexFabric|OneView|Nimble)",
    r"(Industrial Edge Management|Nucleus NET|SINEC).*[\n]*.*siemens",
    r"(Jfinal|Final)[ _]CMS",
    r"(Pinniped Supervisor|VMware Cloud Foundation).*[\n]*.*vmware.*",
    r"(SIMATIC|Mendix|Parasolid|Opcenter Quality|SCALANCE).*[\n]*.*siemens",
    r"(Simcenter Femap|LOGO!|Solid Edge|APOGEE).*[\n]*.*siemens",
    r".*plugin.*for WordPress",
    "1Password",
    "72crm",
    "74cmsSE",
    "ABB e-Design",
    "ABB netCADOPS",
    "ACEweb Online Portal",
    "AEF CMS",
    "ALPS ALPINE touchpad driver",
    "APNGDis",
    "ASANHAMAYESH CMS",
    "Academy Learning Management System",
    "Accusoft ImageGear",
    "Acronis Cyber Backup",
    "Acronis True Image",
    "Adobe Acrobat Reader",
    "Adobe Acrobat and Reader",
    "Adobe Animate",
    "Adobe Bridge",
    "Adobe Campaign",
    "Adobe Character Animator",
    "Adobe Commerce",
    "Adobe Dimension",
    "Adobe Experience Manager",
    "Adobe FrameMaker",
    "Adobe Illustrator",
    "Adobe InCopy",
    "Adobe InDesign",
    "Adobe Lightroom",
    "Adobe Media Encoder",
    "Adobe Photoshop",
    "Adobe Premiere Elements",
    "Adobe RoboHelp",
    "Advanced SystemCare Ultimate",
    "Advantech",
    "AeroCMS",
    "Afian FileRun",
    "AirWave",
    "Ajenti",
    "AnchorCMS",
    "AntSword",
    "Anuko Time Tracker",
    "Apache Geode",
    "Apache NiFi",
    "Apache OpenMeetings",
    "Apache ShenYu",
    "Apache Syncope",
    "Apache Wicket",
    "Apartment Visitor Management System",
    "Apexis",
    "AppFormix",
    "ArcGIS Server",
    "Arista EOS",
    "ArsenoL",
    "Artica Web Proxy",
    "Aruba (ClearPass|EdgeConnect|Networks)",
    "ArubaOS",
    "Atlassian Bamboo",
    "Atlassian Confluence",
    "Atlassian Crucible",
    "Atlassian Fisheye",
    "Atlassian JIRA",
    "Aurea Jive",
    "Automation License Manager",
    "Automotive Shop Management System",
    "Avaya",
    "Avira",
    "Avolve Software ProjectDox",
    "AxxonSoft",
    "AyaCMS",
    "BEESCMS",
    "BMC Medical",
    "BMC Remedy AR System",
    "BMC Remedy Action Request",
    "Backdrop CMS",
    "Badminton Center Management",
    "Bagecms",
    "Barco Control Room Management",
    "BaserCMS",
    "Bento4",
    "Best Student Result Management System",
    "BigBlueButton",
    "BigTree CMS",
    "Billing System Project",
    "Bitcoin Core",
    "Bitdefender Antivirus",
    "Bitdefender Engines",
    "BlackBerry QNX Software Development Platform",
    "BlackBerry UEM Management Console",
    "BlackCat CMS",
    "Bludit",
    "BlueSpice",
    "Bookme Control Panel",
    "Bravo Tejari",
    "Brocade Fabric OS",
    "Brocade Fibre",
    "Brocade SANnav",
    "BtiTracker",
    "CCN-lite",
    "CMS Made Simple",
    "CMSuno",
    "CODESYS",
    "CSZCMS",
    "CactusVPN",
    "Call for Papers",
    "Campcodes Advanced Online Voting System",
    "Canteen Management System",
    "Car Rental Management",
    "Carbon Black",
    "Carel pCOWeb",
    "Centum CS",
    "Chamilo LMS",
    "Chaoji CMS",
    "ChatBot App with Suggestion",
    "ChemCMS",
    "Cisco",
    "Citrix NetScaler",
    "Clansphere CMS",
    "Classcms",
    "Claymore Dual Miner",
    "Clinic's Patient Management System",
    "CloudMe",
    "CloudVision Portal",
    "Clustered Data ONTAP",
    "CoDeSys Runtime",
    "Codoforum",
    "College Management System",
    "Combodo iTop",
    "Complete Online Job Search",
    "Composr CMS",
    "Contiki-NG",
    r"Converse\.js",
    "CoverCMS",
    "Cozy",
    "Craft CMS",
    "CraftCMS",
    "Creditwest Bank CMS",
    "Cybozu Garoon",
    r"D-LINK DIR.*",
    r"D-LINK.*(DIR|COVR|DAP).*",
    r"D-LINK.*(DIR|COVR|DAP|DSL|DCS).*",
    "DIAEnergie",
    r"DIR.*[\n]*.*dlink.com.*",
    "Dataiku DSS",
    "DedeCMS",
    "Dell (Client )?BIOS",
    "Dell (Hybrid Client|GeoDrive)",
    "Dell Container Storage",
    "Dell EMC",
    "Dell NetWorker",
    "Dell PowerScale",
    "Dell SonicWALL Scrutinizer",
    "Dell Storage Manager",
    "Dell Wyse Management Suite",
    "Delta Electronics",
    "Delta Industrial Automation",
    "Desigo",
    "Digital Guardian Managment Console",
    "DiliCMS",
    "DiligentCMS",
    "Discuz",
    "Disk Savvy Enterprise",
    "DocuTrac QuicDoc",
    "Dolibarr",
    "DolphinPHP",
    "DomainMOD",
    "Doufoxcms",
    "DrayTek",
    "Dreamer CMS",
    "EGavilan Media",
    "EMC Data Protection Advisor",
    "EPIC MyChart",
    "ESPCMS",
    "EasyCMS",
    "Eaton's",
    "Edimax",
    "Emlog Pro",
    "Enalean Tuleap",
    "Enhancesoft osTicket",
    "Epson Airprint",
    "Eshtery CMS",
    "EspoCRM",
    "Expense Management System",
    "Explzh",
    "Exponent CMS",
    "Exponent-CMS",
    "EyouCMS",
    "F-Secure Atlant",
    "F5 BIG-IP",
    "FATEK FvDesigner",
    "FUDforum",
    "FUEL-CMS",
    "FactoryTalk",
    "Fast Food Ordering System",
    "FastAdmin",
    "FastCMS",
    r"FeMiner.*wms",
    "Feehi CMS",
    "FeehiCMS",
    "FeiFeiCMS",
    "FiberHome",
    "FlatCore-CMS",
    "Flexense DiskBoss",
    "Flexense DiskPulse",
    "Flexense DiskSavvy",
    "Flexense DiskSorter",
    "Flexense DupScout",
    "Flexense SyncBreeze",
    "Flexense VX Search",
    "Food Ordering Management System",
    "ForgeRock",
    r"FortiADC|FortiMail",
    "FortiAnalyzer",
    "FortiClient",
    "FortiNAC",
    "FortiOS",
    "FortiSOAR",
    "Fortinet",
    r"Foxit .*PDF reader",
    "Frog CMS",
    "Fuji Electric",
    "FusionCompute",
    "FusionSphere OpenStack",
    "GE D60",
    "GPAC ",
    "GSKit",
    "GXCMS",
    "Galileo CMS",
    "Gallagher Command Centre",
    "Garage Management System",
    "Geist WatchDog Console",
    "Gemini-Net",
    "GeniXCMS",
    "GetSimple CMS",
    "GetSimpleCMS",
    "GilaCMS",
    "Gleez CMS",
    "Grandstream",
    "GreenCMS",
    "Gxlcms",
    "Gym Management System",
    r"H3C (Magic|H200|GR[0-9-]+|B5 Mini)",
    r"HCL (iNotes|Commerce|Workload Automation|Digital Experience)",
    "HP Security",
    "HPE Aruba AirWave Glass",
    "HPE Aruba ClearPass Policy Manager",
    "HPE Business Process Monitor",
    "HPE Cloud Optimizer",
    "HPE Data Protector",
    "HPE Diagnostics",
    "HPE Helion Eucalyptus",
    "HPE IceWall Federation Agent",
    "HPE Insight Control",
    "HPE Integrated Lights-Out",
    "HPE Intelligent Management Center",
    "HPE LoadRunner",
    "HPE Matrix Operating Environment",
    "HPE Network Automation",
    "HPE Network Node Manager",
    "HPE NonStop Server",
    "HPE NonStop Software Essentials",
    "HPE OfficeConnect Network Switches",
    "HPE OpenCall Media Platform",
    "HPE Operations Bridge Analytics",
    "HPE Operations Orchestration Community",
    "HPE Pay Per Use",
    "HPE Project and Portfolio Management",
    "HPE SiteScope",
    "HPE Smart Storage Administrator",
    "HPE StoreVirtual",
    "HPE Systems Insight Manager",
    "HPE UCMDB",
    "HPE Version Control Repository Manager",
    "HPE Vertica Analytics",
    "HPE iMC PLAT",
    "HashiCorp Terraform",
    "Helmet Store Showroom",
    "Hewlett Packard Enterprise Intelligent Management Center",
    "Hewlett Packard Enterprise Moonshot Provisioning Manager",
    r"Hirschmann.*[\n]*.*belden",
    "Honeywell",
    "HongCMS",
    "Horizon Client for Windows",
    "Hospital Management System",
    "Hotel Management System",
    "HotelDruid",
    "Human Resource Management System",
    "I, Librarian",
    "I-librarian",
    "IBM AIX",
    "IBM API Connect",
    "IBM App Connect Enterprise",
    "IBM AppScan",
    "IBM Aspera",
    "IBM Aspera Web Application",
    "IBM BigFix",
    "IBM Business Automation Content Analyzer",
    "IBM Business Automation Workflow",
    "IBM Business Process Manager",
    "IBM CICS",
    "IBM Campaign",
    "IBM Capacity Management Analytics",
    "IBM Cloud Pak",
    "IBM CloudPak",
    "IBM Cognos",
    "IBM Connections",
    "IBM Content Manager",
    "IBM Content Navigator",
    "IBM Curam",
    "IBM Daeja ViewONE",
    "IBM Data Risk Manager",
    "IBM DataPower Gateway",
    "IBM Db2",
    "IBM Db2U",
    "IBM Domino",
    "IBM Doors",
    "IBM Emptoris",
    "IBM Endpoint Manager",
    "IBM Engineering Lifecycle Optimization",
    "IBM Event Streams",
    "IBM Financial Transaction Manager",
    "IBM Flex System",
    "IBM Forms Experience Builder",
    "IBM Forms Server",
    "IBM InfoSphere",
    "IBM Jazz",
    "IBM Jazz Foundation",
    "IBM Jazz Reporting Service",
    "IBM MQ",
    "IBM MQ Appliance",
    "IBM Maximo",
    "IBM Notes",
    "IBM Planning Analytics",
    "IBM Power Hardware Management Console",
    "IBM Publishing Engine",
    "IBM QRadar",
    "IBM RSA DM",
    "IBM Rational",
    "IBM Rhapsody",
    "IBM Robotic",
    "IBM Sametime",
    "IBM Secure External Authentication Server",
    "IBM Security Access Manager",
    "IBM Security Guardium",
    "IBM Security Identity Governance and Intelligence",
    "IBM Security Key Lifecycle Manager",
    "IBM Security QRadar",
    "IBM Security Secret Server",
    "IBM Security SiteProtector",
    "IBM Security Trusteer Pinpoint Detect",
    "IBM Security Verify Access",
    "IBM Security Verify Governance",
    "IBM Security Verify Information Queue",
    "IBM SiteProtector Appliance",
    "IBM Spectrum",
    "IBM Spectrum Protect Plus",
    "IBM Spectrum Scale",
    "IBM Sterling B2B Integrator",
    "IBM Sterling Connect:Direct",
    "IBM Sterling File Gateway",
    "IBM Sterling Partner Engagement Manager",
    "IBM Sterling Secure Proxy",
    "IBM TRIRIGA",
    "IBM Tealeaf",
    "IBM Tivoli",
    "IBM UrbanCode Deploy",
    "IBM Watson",
    "IBM WebSphere",
    "IBM XIV Storage",
    "IBM i ",
    "IBM i2 iBase",
    "INTELBRAS",
    "IOBit Malware Fighter",
    "ImageWorsener",
    "Imagely NextGEN Gallery",
    "InHand Networks",
    "Ingredients Stock Management System",
    "InspIRCd",
    "Insurance Management System",
    "Intel (R) LED Manager for NUC",
    "Intel Server Boards",
    "Intel(R) Graphics Drivers",
    "Intel(R) PAC with Arria(R)",
    "Intel(R) Server Boards",
    "Intelbras TELEFONE IP",
    "InventoryManagementSystem",
    "Invision Power Board",
    "IonizeCMS",
    "Ipswitch WhatsUp Gold",
    "Ivanti Endpoint Security",
    "JEXTN",
    "JFrog Artifactory",
    "JT2Go",
    "Jeecg-boot",
    "JerryScript",
    "Jiangmin Antivirus",
    "Jirafeau",
    "Jizhicms",
    "Joomla!",
    "Joyent SmartOS",
    "Judging Management System",
    "JupyterHub OAuthenticator",
    "Kaspersky Secure Mail",
    "Kentico",
    "Kingsoft Internet Security",
    "KiteCMS",
    "Kiwi TCMS",
    "Kliqqi CMS",
    "LAquis SCADA",
    "LJCMS",
    "Library Management System",
    "LibreNMS",
    "Liferay Portal",
    "LogicalDoc",
    "Loway QueueMetrics",
    "M-Files Server",
    "MB CONNECT LINE",
    "MDaemon",
    "MKCMS",
    "MOXA NPort",
    "MP Form Mail",
    "MTS Simple Booking",
    "MZ Automation",
    "Magnolia CMS",
    "Mahara",
    "Mailbutler Shimo",
    "MalwareFox AntiMalware",
    "Malwarebytes Anti-Malware",
    "ManageEngine OpManager",
    "ManageEngine Service Desk Plus",
    "March Hare WINCVS",
    "McAfee Network Security Management",
    "McAfee VirusScan Enterprise",
    "Merchandise Online Store",
    "MetInfo",
    "Micro Focus ArcSight",
    "Micro Focus ArcSight Management Center",
    "Micro Focus Operations Bridge",
    "Micro Focus Project",
    "Micro Focus UCMDB",
    "Micro Focus Universal CMDB",
    "Micro Focus ZENworks",
    "Micropoint proactive",
    "Microsoft",
    "Microweber",
    "MikroTik's RouterOS",
    "Mikrotik RouterOs",
    "Ming-Soft/MCMS",
    "MiniCMS",
    "Mitel ST",
    "Mitsubishi E-Designer",
    "Mitsubishi Electric",
    "Mobotix",
    "Money Transfer Management System",
    "MonstaFTP",
    "Monstra CMS",
    "Moxa OnCell",
    "NETGEAR",
    "NVIDIA GeForce NOW",
    "Navarino Infinity",
    "NetEx HyperIP",
    "NetIQ Access Manager",
    "NetIQ Identity Manager",
    "NetIQ Identity Reporting",
    "NetIQ iManager",
    "Nginx NJS",
    "Niagara",
    "Nokia",
    "NoneCms",
    "NordVPN",
    "Nortek Linear",
    "Novel-Plus",
    "NukeViet CMS",
    "OPTILINK OP",
    "OSIsoft PI",
    "OTCMS",
    "OXID eShop",
    "October CMS",
    "Octopus Deploy",
    "Omron CX-One",
    "Omron CX-Supervisor",
    "Online Car Wash Booking System",
    "Online Diagnostic Lab Management System",
    "Online Examination System",
    "Online Fire Reporting System",
    "Online Food Ordering System",
    "Online Leave Management System",
    "Online Ordering System",
    "Online Pet Shop We App",
    "Online Railway Reservation System",
    "Online Sports Complex Booking System",
    "Online Student Rate System",
    "Online Tours & Travels Management System",
    "Open Source SACCO Management System",
    "Open-AudIT Professional",
    "OpenBMC",
    "OpenEMR",
    "OpenHarmony",
    "OpenLiteSpeed",
    "OpenMRS",
    "OpenScape Deployment Service",
    "Opencast",
    "Ozeki NG SMS Gateway",
    "PAN-OS",
    "PHP Scripts Mall",
    "PHPGurukul",
    "PHPJabbers Class Scheduling System",
    "POSCMS",
    "Paessler PRTG Network Monitor",
    "Pagekit CMS",
    "Pandora FMS",
    "Parallels Remote Application Server",
    "PayPal",
    "PbootCMS",
    "Pega Platform",
    "Pegasystems Pega Platform",
    "Pharmacy Management System",
    "Philips Intellispace Portal",
    "PicturesPro Photo Cart",
    "Piwigo",
    "Pixar OpenUSD",
    "Plixer Scrutinizer",
    "Plone CMS",
    "Pluck",
    "PowerCMS",
    "PrestaShop",
    "PrivateVPN",
    "Project-Pier",
    "Promise Technology",
    "PublicCMS",
    "Pulse Connect Secure",
    "Pulse Secure Desktop Client",
    "PureVPN",
    "PyroCMS",
    "QNAP QTS",
    "Quest NetVault",
    "QuickTime",
    "RPCMS",
    "RUGGEDCOM",
    "Rapid Software LLC Rapid SCADA",
    "Red Discord Bot",
    "Rescue Dispatch Management",
    "Restaurant POS System",
    "Robustel R1510",
    "Rocket.Chat",
    "Rockwell Automation",
    "RosarioSIS",
    "Ruckus Networks",
    "Rukovoditel",
    "SAP 3D Visual Enterprise Viewer",
    "SAP Adaptive Server Enterprise",
    "SAP BASIS",
    "SAP Banking Services",
    "SAP Business Objects Business Intelligence Platform",
    "SAP Commerce versions",
    "SAP Data Hub",
    "SAP ERP",
    "SAP Fiori Launchpad",
    "SAP Marketing",
    "SAP NetWeaver",
    "SEMCMS",
    "SICAM",
    r"SIMATIC.*(PCS|CP)",
    "Sagemcom",
    "Sandoba CP:Shop",
    "Sanitization Management System",
    "Saperion Web Client",
    "Schneider Electric",
    "School Activity Updates with SMS Notification",
    "SeaCms",
    "Seagate Media Server",
    r"Secomea (GateManager|SiteManager)",
    "SeedDMS",
    "Shimmie",
    "Shirne CMS",
    "ShopXO",
    "Shopwind",
    "Silverstripe",
    "Simple Bus Ticket Booking System",
    "Simple Client Management System",
    "Simple Cold Storage Management System",
    "Simple Customer Relationship Management",
    "Simple E-Learning System",
    "Simple Image Gallery System",
    "Simple Inventory System",
    "Simple Online Book Store System",
    "Simple Online Public Access Catalog",
    "Simple Task Scheduling System",
    "Sinsiu Sinsiu Enterprise Website System",
    "SmartVista",
    "SnapCreek Duplicator",
    "SolarView Compact",
    "Solutions Atlantic Regulatory Reporting System",
    "SonicWall SMA100",
    "Sophos Endpoint Protection",
    "Sophos Firewall",
    "SourceCodester",
    "SpamTitan",
    "SpiderControl MicroBrowser",
    "Square 9 GlobalForms",
    "Stock Management System",
    "Stormshield Network Security",
    "Student Clearance System",
    "Student Information System",
    "Subrion CMS",
    "SugarCRM",
    "Sumatra PDF",
    "Symantec",
    "Synacor Zimbra",
    "Synology DiskStation Manager",
    "Synology Photo",
    "Synology Router Manager",
    "Synology Surveillance Station",
    "SysAid Help Desk",
    "Sysax Multi Server",
    "TIBCO DataSynapse GridServer Manager",
    "TOTOLINK",
    r"TP-Link.*(TL|AX10v1|Tapo)",
    "TRENDNet",
    "Taocms",
    "Telegram Desktop",
    "Tenda AC15",
    "Tenda AC9",
    r"Tenda( |_.*)",
    "Textpattern CMS",
    "Train Scheduler App",
    "TreasuryXpress",
    "Trend Micro",
    "TuziCMS",
    "Twonky Server",
    "UCMS ",
    "UJCMS",
    "Ubiquiti Networks EdgeOS",
    "Unisphere for PowerMax",
    "Unisys ClearPath",
    "Unisys Stealth SVG",
    "United Planet Intrexx Professional",
    "Unitrends Backup",
    "Untis WebUntis",
    "Userscape HelpSpot",
    r"VIDEOJET.*[\n]*.*psirt",
    "VMware ESXi and vCenter Server",
    "VMware Fusion",
    "VMware Workstation",
    "Vehicle Booking System",
    "Verint Workforce Optimization",
    "Veritas NetBackup",
    "Verizon 5G Home",
    "Vesta Control Panel",
    "Victor CMS",
    "VirtueMart",
    "WBCE CMS",
    "WECON LeviStudioU",
    "WPS Office",
    "WSO2 Enterprise Integrator",
    "WTCMS",
    "WUZHI CMS",
    "WatchDog Anti-Malware",
    "Wavlink",
    "Web Based Quiz System",
    "WebDynpro Java",
    "Weblication CMS",
    "Wedding Management System",
    "Wedding Planner",
    "Weeny Audio Cutter",
    "Wellcms",
    "Western Bridge Cobub Razor",
    "Western Digital My Cloud",
    "Winmail",
    "Wireless IP Camera 360",
    "WoWonder",
    "WonderCMS",
    "WordPress theme",
    r"WordPress.*plugin",
    "Wowza Streaming",
    "XYHCMS",
    "Xiaomi.*phones",
    "Xiuno BBS",
    "XunRuiCMS",
    "Yab Quarx",
    "Yahoo!",
    "Yxcms",
    "YxtCMF",
    "YzmCMS",
    "Z-BlogPHP",
    "Zenario CMS",
    "Zikula Application Framework",
    "Zoho ManageEngine",
    "ZoneAlarm",
    "ZoneMinder",
    "Zoo Management System",
    "Zulip Desktop",
    "Zyxel",
    "baijiacms",
    "bootstrap-table",
    "chatwoot",
    "cmseasy",
    "comforte SWAP",
    "concretecms",
    "dotCMS",
    "drawio",
    "eDNA Enterprise Data Historian",
    "ebCMS",
    r"ednareporting\.asmx",
    "elitecms",
    "emoncms",
    "enhavo CMS",
    "htmly",
    "https://gitee.com/oufu/ofcms/",
    "https://github.com/cesanta/mjs/",
    "https://github.com/kabirkhyrul/HMS/",
    "https://github.com/vapor/vapor/",
    "https://github.com/wp-plugins",
    "https://support.zte.com.cn/support/",
    "https://www.autodesk.com/",
    "https://www.solarwinds.com/",
    "iDashboards",
    "iPayPal",
    "iRedMail",
    "iScripts SupportDesk",
    "iScripts UberforX",
    "iScripts eSwap",
    "iTunes",
    "iota All-In-One Security Kit",
    "ismartgate PRO",
    "joyplus-cms",
    "lyadmin",
    "madlib-object-utils",
    r"mySCADA myPRO|Measuresoft ScadaPro",
    "open5gs",
    "perfex crm",
    "phpjs",
    "pimcore",
    r"plugin <= [0-9\.]+ at WordPress",
    r"plugins.*wordpress",
    "portfolioCMS",
    "prime-jwt",
    "publify",
    "puppyCMS",
    "rap2hpoutre Laravel Log Viewer",
    "rdiffweb",
    r"siteserver (CMS|SSCMS)",
    "swftools",
    "totaljs",
    "trudesk",
    "usememos/memos",
    "vBulletin",
    r"win32k\.sys",
    "wityCMS",
    "wuzhicms",
    "yetiforcecrm",
    "zzcms",
]

BLACKLIST_CASE_SENSITIVE = ["iOS"]

KEYWORD_WHITELIST = [
    re.compile(rf"\b{keyword}\b", re.IGNORECASE) for keyword in WHITELIST
] + [re.compile(keyword) for keyword in WHITELIST_SPECIAL_CASES]

KEYWORD_BLACKLIST = [
    re.compile(rf"\b{keyword}\b", re.IGNORECASE) for keyword in BLACKLIST
] + [re.compile(rf"\b{keyword}\b") for keyword in BLACKLIST_CASE_SENSITIVE]


def check_keywords(text):
    """
    Checks if a specified text is relevant or not based on found keywords.

    Returns tuple of matched blacklisted and whitelisted keywords.
    """
    whitelist = []
    for word in (regex.search(text) for regex in KEYWORD_WHITELIST):
        if word is not None:
            whitelist.append(word.group().strip())

    blacklist = []
    for word in (regex.search(text) for regex in KEYWORD_BLACKLIST):
        if word is not None:
            blacklist.append(word.group())

    return sorted(blacklist), sorted(whitelist)


def should_create_snippet(text):
    """
    Returns True if a snippet should be created, False otherwise.

    Snippet should be created if:
        words in `text` are in both whitelist and blacklist ([x], [x])
        words in `text` are in whitelist only               ([x], [])
        words in `text` are not in whitelist or blacklist   ([], [])

    Snippet should not be created if:
        words in `text` are in blacklist only               ([], [x])
        `text` is empty
    """
    if not text:
        return False

    blacklist, whitelist = check_keywords(text)

    return False if (blacklist and not whitelist) else True
