---
name: DEFAULT
description: default vulnerability analysis
priority: 0
conditions: []
states:
  - name: DRAFT
    enter_automaticaly: true
    jira_state: New
    jira_resolution: null
    requirements: []

  # as soon as we have some basic information
  # and ownership we are no draft any more
  - name: IN PROGRESS
    enter_automaticaly: true
    jira_state: New
    jira_resolution: null
    requirements:
      - has affects
      - has description
      - has source
      - has title
      - is owned

  - name: PUBLISHED
    # publishing is done by humans
    enter_automaticaly: false
    jira_state: Refinement
    jira_resolution: null
    requirements:
      # we file trackers in 24h
      - trackers filed

  - name: REVIEW
    enter_automaticaly: true
    jira_state: In Progress
    jira_resolution: null
    requirements:
      - has summary
      # TODO flags

  - name: FINALIZED
    enter_automaticaly: true
    jira_state: Closed
    jira_resolution: Done
    requirements:
      - has cve
