# input {
#   beats {
#     port => 5044
#   }
# }

# output {
#   stdout {
#     codec => rubydebug
#   }
# }

input {
  tcp {
    port => 5140                # Specify the port to listen on
    # codec => "json"         # Adjust the codec if logs are in JSON format
    # type => "tcp-logs"
    codec => json_lines {  # Decodes JSON payloads
      charset => "UTF-8"  # Specify UTF-8 charset
      ecs_compatibility => "disabled"
      # delimiter => "\n"
    }
  }
}

# filter {
#   # Parse the JSON structure
#   # json {
#   #   source => "formatted_record"
#   # }
#   # mutate {
#   #   rename => { "formatted_record" => "message" }
#   # }
# }

output {
  if [logfile] == "django.log" {
    file {
      path => "/usr/share/logstash/log/${LOGFILE_ENV_PREFIX}-django.log"  # Specify the file path for storing logs
      codec => line {
        format => "%{[formatted_record]}"
      }
      # file_mode => 0644
    }
  }
}
