input {
  tcp {
    port => 5140
    codec => json_lines {
      charset => "UTF-8"
      ecs_compatibility => "disabled"
    }
  }
}

output {
  if [logfile] == "django.log" {
    file {
      path => "/usr/share/logstash/log/${LOGFILE_ENV_PREFIX}-django.log"  # Specify the file path for storing logs
      codec => line {
        format => "%{[formatted_record]}"
      }
    }
  }

  if [logfile] == "celery.log" {
    file {
      path => "/usr/share/logstash/log/${LOGFILE_ENV_PREFIX}-celery.log"  # Specify the file path for storing logs
      codec => line {
        format => "%{[formatted_record]}"
      }
    }
  }
}
