stages:
  - check
  - test

before_script:
  - export LANG=en_US.UTF-8
  - export PIP_INDEX_URL=$PIP_INDEX_URL
  - curl $RH_CERT_URL -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
  - update-ca-trust
  - export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

check:
  stage: check
  image: quay.io/prodsecdev/fedora-latest:35  # includes tox
  script:
    - dnf install -y openldap-devel python3.9
    - tox --parallel --parallel-live

test:
  stage: test
  image: quay.io/prodsecdev/fedora-latest:35  # includes all deps
  services:
    - name: registry.redhat.io/rhel8/postgresql-13:1-21
      alias: postgres
    - name: quay.io/prodsecdev/openldap:2.5.7-debian-10-r57
      alias: testldap
  variables:
      POSTGRESQL_ADMIN_PASSWORD: test
      POSTGRES_DATABASE: osidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: postgres
      LDAP_ROOT: dc=redhat,dc=com
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      ET_URL: $ET_URL
      PRODUCT_DEF_URL: $PRODUCT_DEF_URL
  artifacts:
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  script:
    - dnf install -y openldap-devel openldap-clients python3.9
    - sleep 60
    - ldapadd -c -H "ldap://testldap:1389" -x -D "cn=admin,dc=redhat,dc=com" -w "adminpassword" -f etc/openldap/local-export.ldif || true
    - tox -e ci-osidb
