# Generated by Django 3.2.18 on 2023-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JiraProjectFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_key", models.CharField(max_length=50)),
                ("field_id", models.CharField(max_length=50)),
                ("field_name", models.CharField(max_length=50)),
                ("allowed_values", models.JSONField(default=list)),
            ],
            options={
                "unique_together": {("project_key", "field_name")},
            },
        ),
    ]
