# Generated by Django 3.2.25 on 2024-08-28 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraBugIssuetype',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
