# Generated by Django 5.2.13 on 2026-06-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_jirabugissuetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jiraprojectfields',
            unique_together={('project_key', 'field_id')},
        ),
    ]
