# Generated by Django 5.2.12 on 2026-04-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_jirabugissuetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jiraprojectfields',
            unique_together={('project_key', 'field_id')},
        ),
    ]
