# Generated by Django 4.2.16 on 2024-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sla", "0002_alter_sla_start_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="sla",
            name="ending",
            field=models.CharField(
                choices=[("any day", "Any Day"), ("no week ending", "No Week Ending")],
                default="any day",
                max_length=20,
            ),
        ),
    ]
