# Generated by Django 4.2.17 on 2025-01-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0003_sla_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slapolicy',
            name='sla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='sla.sla'),
        ),
    ]
