# Generated by Django 4.2.22 on 2025-10-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0004_make_sla_nullable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLA',
        ),
        migrations.CreateModel(
            name='TemporalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('Business Days', 'Business Days'), ('Calendar Days', 'Calendar Days')], max_length=20)),
                ('ending', models.CharField(choices=[('any day', 'Any Day'), ('no week ending', 'No Week Ending')], default='any day', max_length=20)),
                ('start_criteria', models.CharField(choices=[('Earliest', 'Earliest'), ('Latest', 'Latest')], max_length=20)),
                ('start_dates', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='sla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='sla.temporalpolicy'),
        ),
    ]
