# Generated by Django 4.2.22 on 2025-09-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sla', '0005_delete_sla_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('Business Days', 'Business Days'), ('Calendar Days', 'Calendar Days')], max_length=20)),
                ('ending', models.CharField(choices=[('any day', 'Any Day'), ('no week ending', 'No Week Ending')], default='any day', max_length=20)),
                ('start_criteria', models.CharField(choices=[('Earliest', 'Earliest'), ('Latest', 'Latest')], max_length=20)),
                ('start_dates', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SLOPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('condition_descriptions', models.JSONField(default=dict)),
                ('order', models.IntegerField(unique=True)),
                ('slo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='sla.slo')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
