# Generated by Django 4.2.22 on 2025-10-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0006_delete_slapolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLOPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('condition_descriptions', models.JSONField(default=dict)),
                ('order', models.IntegerField(unique=True)),
                ('slo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slo_policies', to='sla.temporalpolicy')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
