# Generated by Django 4.2.26 on 2025-11-28 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0008_create_slapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalpolicy',
            name='ending_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('any day', 'Any Day'), ('no shutdown', 'No Shutdown'), ('no week ending', 'No Week Ending')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='temporalpolicy',
            name='ending',
            field=models.CharField(choices=[('any day', 'Any Day'), ('no shutdown', 'No Shutdown'), ('no week ending', 'No Week Ending')], default='any day', max_length=20),
        ),
    ]
