# Generated by Django 4.2.26 on 2025-11-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0009_temporalpolicy_ending_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporalpolicy',
            name='ending',
        ),
    ]
