# Dockerfile for Log Listener
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
# COPY requirements.txt .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the log listener script
# COPY ./etc/log_listener/log_listener.py .

# Command to run the log listener
CMD ["python", "-u", "log_listener.py"]
