# Generated by Django 4.2.22 on 2025-07-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cveorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='type',
            field=models.CharField(choices=[('ALLOWLIST', 'Allowlist'), ('ALLOWLIST_SPECIAL_CASE', 'Allowlist Special Case'), ('BLOCKLIST', 'Blocklist'), ('BLOCKLIST_SPECIAL_CASE', 'Blocklist Special Case'), ('ASSIGNERORGID_BLOCKLIST', 'Assignerorgid Blocklist')], max_length=25),
        ),
    ]
