# Generated by Django 3.2.15 on 2022-09-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("bzimport", "0001_initial"),
        ("bzimport", "0002_rename_attr_job_meta_attr"),
        ("bzimport", "0003_remove_job_modes"),
        ("jiraffe", "0001_initial"),
        ("jiraffe", "0002_remove_job_models"),
    ]

    operations = []
