# Generated by Django 3.2.7 on 2021-09-30 22:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import psqlextra.fields.hstore_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_dt",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "bz_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                ("comment", models.CharField(max_length=255, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("apply_fixups", models.BooleanField(default=True)),
                ("dry_run", models.BooleanField(default=False)),
                ("fail_early", models.BooleanField(default=False)),
                ("update", models.BooleanField(default=True)),
                ("relax_validation", models.BooleanField(default=False)),
                (
                    "exclude",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                ("batch_create", models.BooleanField(default=True)),
                ("attr", psqlextra.fields.hstore_field.HStoreField(null=True)),
            ],
            options={
                "verbose_name_plural": "jobs",
            },
        ),
        migrations.CreateModel(
            name="JobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_uuid", models.UUIDField(editable=False, null=True)),
                (
                    "flaw_uuids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cve_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("bz_id", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "trace",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("number_cve_id", models.IntegerField(default=0)),
                ("number_affects", models.IntegerField(default=0)),
                ("number_trackers", models.IntegerField(default=0)),
                ("bz_data_score", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "jobitems",
            },
        ),
    ]
