# Generated by Django 3.2.6 on 2021-10-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bzimport", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="attr",
            new_name="meta_attr",
        ),
    ]
