# Generated by Django 3.2.15 on 2022-09-22 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import psqlextra.fields.hstore_field


class Migration(migrations.Migration):

    replaces = [
        ("framework", "0001_initial"),
        ("framework", "0002_auto_20220311_0904"),
        ("framework", "0003_collectormetadata_last_run_dt"),
        ("framework", "0004_collector_required_fields_revision"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectorMetadata",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_state",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="EMPTY",
                        max_length=10,
                    ),
                ),
                ("updated_until_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "meta_attr",
                    psqlextra.fields.hstore_field.HStoreField(blank=True, null=True),
                ),
                (
                    "collector_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BLOCKED", "Blocked"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("crontab", models.CharField(blank=True, max_length=100)),
                (
                    "depends_on",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "data_models",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("last_run_dt", models.DateTimeField(null=True)),
            ],
        ),
    ]
