# Generated by Django 3.2.12 on 2022-03-11 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectormetadata",
            name="model",
        ),
        migrations.AddField(
            model_name="collectormetadata",
            name="data_models",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
