# Generated by Django 3.2.13 on 2022-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20220311_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectormetadata',
            name='last_run_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
