# Generated by Django 5.2.12 on 2026-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0002_crontab"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectormetadata",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
