# Generated by Django 3.2.13 on 2022-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_collectormetadata_last_run_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectormetadata',
            name='crontab',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectormetadata',
            name='error',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
