---
name: DEFAULT
description: Automated vulnerability processing workflow.
priority: 0
conditions: []
states:
  - name: NEW
    description: >
      A new flaw arrived into the queue.
    jira_state: New
    jira_resolution: null
    requirements: []

  - name: TRIAGE
    description: >
      The flaw has passed automated initial triage. Basic data has been
      filled in and the flaw is ready for affect creation.
    jira_state: Refinement
    jira_resolution: null
    requirements:
      - has components
      - has impact
      - has reported_dt
      - has source
      - has title
      - condition: OR
        requirements:
          - impact is low
          - has cve_description

  - name: ANALYSIS
    description: >
      Affects have been created and are being analysed. Each affect
      needs to be resolved before the flaw can proceed.
    jira_state: Refinement
    jira_resolution: null
    requirements:
      - has affects

  - name: PRE_SECONDARY_ASSESSMENT
    description: >
      All affects have been resolved. The trackers can be filed.
      Also the flaw data is complete enough to make it public.
    jira_state: To Do
    jira_resolution: null
    visibility: PUBLIC
    requirements:
      - has affects resolved

  - name: SECONDARY_ASSESSMENT
    description: The trackers were filed. The flaw is ready for the review.
    jira_state: In Progress
    jira_resolution: null
    requirements:
      - has trackers

  - name: DONE
    description: >
      A flaw was approved and is considered done.
    jira_state: Closed
    jira_resolution: Done
    requirements:
      - has label approved
