# Generated by Django 3.2.8 on 2021-11-03 12:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bzimport", "0002_rename_attr_job_meta_attr"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraffeJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bzimport.job",
                    ),
                ),
                (
                    "affect_uuids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default=list, max_length=255, null=True
                        ),
                        size=None,
                    ),
                ),
            ],
            bases=("bzimport.job",),
        ),
        migrations.CreateModel(
            name="JiraffeJobItem",
            fields=[
                (
                    "jobitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bzimport.jobitem",
                    ),
                ),
                ("affect_uuid", models.UUIDField()),
            ],
            bases=("bzimport.jobitem",),
        ),
    ]
