# Generated by Django 3.2.12 on 2022-04-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jiraffe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jiraffejobitem",
            name="jobitem_ptr",
        ),
        migrations.DeleteModel(
            name="JiraffeJob",
        ),
        migrations.DeleteModel(
            name="JiraffeJobItem",
        ),
    ]
