# Generated by Django 5.2.13 on 2026-07-29 18:39

import osidb.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "regulatory_reporting",
            "0004_remove_upstreamnotification_insert_insert_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="upstreamproject",
            name="purl",
            field=osidb.models.fields.PURLField(blank=True),
        ),
    ]
