# Generated by Django 5.2.13 on 2026-08-03 16:08

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulatory_reporting", "0005_upstreamproject_purl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="upstreamnotification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_upstream_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upstreamnotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upstreamnotificationaudit",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upstreamnotificationaudit",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "actor_id", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "sent_at", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."actor_id", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", NEW."payload_text", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reportability_reason", NEW."sent_at", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="f0a3dd91a601b9c9d350bb3ef2136647d39fd924",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_cba87",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "actor_id", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "sent_at", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."actor_id", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", NEW."payload_text", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportability_reason", NEW."sent_at", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="cf6ef95e8605c310ada116b1ac99888e25067009",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_281d6",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "actor_id", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "sent_at", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."actor_id", OLD."created_dt", OLD."flaw_id", OLD."last_error", OLD."method", OLD."payload_text", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reportability_reason", OLD."sent_at", OLD."status", OLD."timer_started_at", OLD."updated_dt", OLD."upstream_project_id", OLD."uuid"); RETURN NULL;',
                    hash="48fdd4704073272e89496a4a155362586e3170f2",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_3a634",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
    ]
