# Generated by Django 5.2.12 on 2026-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulatory_reporting", "0009_srpreport_event_type_flaw_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="srpreport",
            name="title",
            field=models.TextField(help_text="Title of the SRP report"),
        ),
        migrations.AlterField(
            model_name="srpreportaudit",
            name="title",
            field=models.TextField(help_text="Title of the SRP report"),
        ),
    ]
