# Generated by Django 5.2.16 on 2026-08-18 13:36

import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0010_srpreport_title_textfield'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='srpreport',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='srpreportmilestone',
            name='update_update',
        ),
        migrations.AddField(
            model_name='srpreport',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='srpreport',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='srpreportaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='srpreportaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='srpreportmilestone',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='srpreportmilestone',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='srpreportmilestoneaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='srpreportmilestoneaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='upstreamnotification',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='upstreamnotification',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='upstreamnotificationaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='upstreamnotificationaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=[uuid.UUID('b5a7e618-aac7-559f-9465-58cc9e9ed439')], then=models.Value('EMBARGOED')), models.When(acl_read=[uuid.UUID('08e4d24f-8d50-535b-a7b5-d9bdf0cbb337')], then=models.Value('INTERNAL')), models.When(acl_read=[uuid.UUID('e62dac33-2b05-5be1-9417-e3d301ff57da')], then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreport',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."designated_csirt_country" IS DISTINCT FROM (NEW."designated_csirt_country") OR OLD."designated_csirt_source" IS DISTINCT FROM (NEW."designated_csirt_source") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."evidence" IS DISTINCT FROM (NEW."evidence") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."manufacturer_or_steward_name" IS DISTINCT FROM (NEW."manufacturer_or_steward_name") OR OLD."member_states_available" IS DISTINCT FROM (NEW."member_states_available") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."reportable_event_type" IS DISTINCT FROM (NEW."reportable_event_type") OR OLD."responsibility_scope" IS DISTINCT FROM (NEW."responsibility_scope") OR OLD."srp_reference_id" IS DISTINCT FROM (NEW."srp_reference_id") OR OLD."srp_reference_url" IS DISTINCT FROM (NEW."srp_reference_url") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."timer_started_at" IS DISTINCT FROM (NEW."timer_started_at") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "evidence", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."designated_csirt_country", NEW."designated_csirt_source", NEW."evidence", NEW."flaw_id", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manufacturer_or_steward_name", NEW."member_states_available", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportable_event_type", NEW."responsibility_scope", NEW."srp_reference_id", NEW."srp_reference_url", NEW."status", NEW."timer_started_at", NEW."title", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='b0c6fbaf57468adc1fad43fac2213bb5c105da05', operation='UPDATE', pgid='pgtrigger_update_update_20d0f', table='regulatory_reporting_srpreport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."milestone_type" IS DISTINCT FROM (NEW."milestone_type") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."request_received_at" IS DISTINCT FROM (NEW."request_received_at") OR OLD."request_source" IS DISTINCT FROM (NEW."request_source") OR OLD."request_text" IS DISTINCT FROM (NEW."request_text") OR OLD."srp_report_id" IS DISTINCT FROM (NEW."srp_report_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='8b25d318981a355218747bb7827567f0a9ce66b5', operation='UPDATE', pgid='pgtrigger_update_update_59a28', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
    ]
