# Generated by Django 5.2.16 on 2026-09-10 12:49

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulatory_reporting", "0016_srpreportmilestone_additional_details"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="srpreportmilestone",
            name="manual_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="srpreportmilestoneaudit",
            name="manual_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "manual_due_at", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."additional_details", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manual_due_at", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="f0f8c0fb911452304ae9629ebe88d79de0740137",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_53837",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."additional_details" IS DISTINCT FROM (NEW."additional_details") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."manual_due_at" IS DISTINCT FROM (NEW."manual_due_at") OR OLD."milestone_type" IS DISTINCT FROM (NEW."milestone_type") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."request_received_at" IS DISTINCT FROM (NEW."request_received_at") OR OLD."request_source" IS DISTINCT FROM (NEW."request_source") OR OLD."request_text" IS DISTINCT FROM (NEW."request_text") OR OLD."srp_report_id" IS DISTINCT FROM (NEW."srp_report_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."submitted_at" IS DISTINCT FROM (NEW."submitted_at") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))',
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "manual_due_at", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."additional_details", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manual_due_at", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="141daae790763c92bf14cce8d1076843a265cfa1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_59a28",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "manual_due_at", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."additional_details", OLD."created_dt", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."manual_due_at", OLD."milestone_type", OLD."missing_required_fields", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."srp_report_id", OLD."status", OLD."submitted_at", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="74906aedc00de9edd55c50c4e64f8b035d2c3ea5",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a9aad",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
    ]
