# Generated by Django 5.2.16 on 2026-09-21 15:12
from datetime import timedelta

from django.db import migrations

AIR_DURATION = timedelta(days=30)
FIXED_DURATIONS = {
    "24h": timedelta(hours=24),
    "72h": timedelta(hours=72),
}
FINAL_DURATIONS = {
    "EXPLOITS_KEV_APPROVED": timedelta(days=14),
    "MAJOR_INCIDENT_APPROVED": timedelta(days=30),
}


def backfill_due_at(apps, schema_editor):
    SRPReportMilestone = apps.get_model("regulatory_reporting", "SRPReportMilestone")
    milestones = SRPReportMilestone.objects.filter(due_at__isnull=True).select_related(
        "srp_report"
    )

    for milestone in milestones:
        new_due_at = None

        if milestone.milestone_type == "additional_information_response":
            if milestone.request_received_at:
                new_due_at = milestone.request_received_at + AIR_DURATION
        else:
            timer_started_at = milestone.srp_report.timer_started_at
            if timer_started_at:
                if milestone.milestone_type == "final":
                    duration = FINAL_DURATIONS.get(
                        milestone.srp_report.reportable_event_type
                    )
                else:
                    duration = FIXED_DURATIONS.get(milestone.milestone_type)

                if duration is not None:
                    new_due_at = timer_started_at + duration

        if new_due_at is not None:
            SRPReportMilestone.objects.filter(pk=milestone.pk).update(due_at=new_due_at)


class Migration(migrations.Migration):
    dependencies = [
        (
            "regulatory_reporting",
            "0017_remove_srpreportmilestone_insert_insert_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(backfill_due_at, migrations.RunPython.noop),
    ]
