# Generated by Django 5.2.16 on 2026-09-16 14:24

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_reporting", "0018_backfill_milestone_due_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInformationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "request_received_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was received", null=True
                    ),
                ),
                (
                    "request_source",
                    models.CharField(
                        blank=True, help_text="Source of the request", max_length=255
                    ),
                ),
                (
                    "request_text",
                    models.TextField(blank=True, help_text="Text of the request"),
                ),
                (
                    "manual_due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manual override for the due date",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("milestone", "created_dt"),
                "abstract": False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreportmilestone",
            name="delete_delete",
        ),
        migrations.RemoveConstraint(
            model_name="srpreportmilestone",
            name="unique_srp_report_milestone_type_level",
        ),
        migrations.RemoveField(
            model_name="srpreportmilestoneaudit",
            name="request_received_at",
        ),
        migrations.RemoveField(
            model_name="srpreportmilestoneaudit",
            name="request_source",
        ),
        migrations.RemoveField(
            model_name="srpreportmilestoneaudit",
            name="request_text",
        ),
        migrations.AlterField(
            model_name="srpreportmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("24h", "24 Hour Template"),
                    ("72h", "72 Hour Template"),
                    ("final", "Final Report Template"),
                ],
                help_text="Type of milestone (24h, 72h, final, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="srpreportmilestoneaudit",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("24h", "24 Hour Template"),
                    ("72h", "72 Hour Template"),
                    ("final", "Final Report Template"),
                ],
                help_text="Type of milestone (24h, 72h, final, etc.)",
                max_length=50,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."additional_details", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="16ebe69a1f8150c26d13fa25c1f3922e450bfe86",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_53837",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."additional_details" IS DISTINCT FROM (NEW."additional_details") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."milestone_type" IS DISTINCT FROM (NEW."milestone_type") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."srp_report_id" IS DISTINCT FROM (NEW."srp_report_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."submitted_at" IS DISTINCT FROM (NEW."submitted_at") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))',
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."additional_details", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="a09da2280a2b4891cbc42aadf53c98aae92ec010",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_59a28",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreportmilestone",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "additional_details", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."additional_details", OLD."created_dt", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."milestone_type", OLD."missing_required_fields", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."srp_report_id", OLD."status", OLD."submitted_at", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="1bc03d0f1e66468c791291259a201149d8b326db",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a9aad",
                    table="regulatory_reporting_srpreportmilestone",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="srpreportmilestone",
            constraint=models.UniqueConstraint(
                fields=("srp_report", "milestone_type"),
                name="unique_srp_report_milestone_type_level",
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="milestone",
            field=models.ForeignKey(
                help_text="The milestone this additional information request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_information_requests",
                to="regulatory_reporting.srpreportmilestone",
            ),
        ),
        migrations.AddIndex(
            model_name="additionalinformationrequest",
            index=models.Index(
                fields=["-updated_dt"], name="regulatory__updated_8c70d7_idx"
            ),
        ),
    ]
