# Generated by Django 5.2.16 on 2026-09-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0019_copy_legacy_air_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srpreportmilestone',
            name='request_received_at',
        ),
        migrations.RemoveField(
            model_name='srpreportmilestone',
            name='request_source',
        ),
        migrations.RemoveField(
            model_name='srpreportmilestone',
            name='request_text',
        ),
    ]
