# Generated by Django 5.2.16 on 2026-09-17 18:09

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_reporting", "0019_additionalinformationrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="acl_read",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="acl_write",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="embargoed",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        acl_read=[uuid.UUID("b5a7e618-aac7-559f-9465-58cc9e9ed439")],
                        then=True,
                    ),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="visibility",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        acl_read=[uuid.UUID("b5a7e618-aac7-559f-9465-58cc9e9ed439")],
                        then=models.Value("EMBARGOED"),
                    ),
                    models.When(
                        acl_read=[uuid.UUID("08e4d24f-8d50-535b-a7b5-d9bdf0cbb337")],
                        then=models.Value("INTERNAL"),
                    ),
                    models.When(
                        acl_read=[uuid.UUID("e62dac33-2b05-5be1-9417-e3d301ff57da")],
                        then=models.Value("PUBLIC"),
                    ),
                    default=models.Value("PUBLIC"),
                    output_field=models.CharField(),
                ),
                output_field=models.CharField(max_length=10),
            ),
        ),
        migrations.RunSQL(
            reverse_sql="""
--drop policies and disable row based security for additionalinformationrequest entity table
DROP policy if exists acl_policy_additionalinformationrequest_create on regulatory_reporting_additionalinformationrequest;
DROP policy if exists acl_policy_additionalinformationrequest_select on regulatory_reporting_additionalinformationrequest;
DROP policy if exists acl_policy_additionalinformationrequest_update on regulatory_reporting_additionalinformationrequest;
DROP policy if exists acl_policy_additionalinformationrequest_delete on regulatory_reporting_additionalinformationrequest;
ALTER TABLE regulatory_reporting_additionalinformationrequest NO FORCE ROW LEVEL SECURITY;
ALTER TABLE regulatory_reporting_additionalinformationrequest DISABLE ROW LEVEL SECURITY;
""",
            sql="""
--enable row based security for additionalinformationrequest entity table
ALTER TABLE regulatory_reporting_additionalinformationrequest ENABLE ROW LEVEL SECURITY;
ALTER TABLE regulatory_reporting_additionalinformationrequest FORCE ROW LEVEL SECURITY;
--following policies define fine grained read/write control on additionalinformationrequest entity
--policy for entity insert (eg. create)
DROP policy if exists acl_policy_additionalinformationrequest_create on regulatory_reporting_additionalinformationrequest;
create policy acl_policy_additionalinformationrequest_create
on regulatory_reporting_additionalinformationrequest
for INSERT
WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
    AND acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
--policy for entity select
DROP policy if exists acl_policy_additionalinformationrequest_select on regulatory_reporting_additionalinformationrequest;
create policy acl_policy_additionalinformationrequest_select
on regulatory_reporting_additionalinformationrequest
for select
USING (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
--policy for entity update
DROP policy if exists acl_policy_additionalinformationrequest_update on regulatory_reporting_additionalinformationrequest;
create policy acl_policy_additionalinformationrequest_update
on regulatory_reporting_additionalinformationrequest
for update
USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[])
WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
    AND acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
--policy for entity delete
DROP policy if exists acl_policy_additionalinformationrequest_delete on regulatory_reporting_additionalinformationrequest;
create policy acl_policy_additionalinformationrequest_delete
on regulatory_reporting_additionalinformationrequest
for delete
USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
""",
        ),
    ]
