# Generated by Django 5.2.16 on 2026-09-22 18:13

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        (
            "regulatory_reporting",
            "0023_remove_srpreportmilestone_insert_insert_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInformationRequestAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "embargoed",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                acl_read=[
                                    uuid.UUID("b5a7e618-aac7-559f-9465-58cc9e9ed439")
                                ],
                                then=True,
                            ),
                            default=False,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "visibility",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                acl_read=[
                                    uuid.UUID("b5a7e618-aac7-559f-9465-58cc9e9ed439")
                                ],
                                then=models.Value("EMBARGOED"),
                            ),
                            models.When(
                                acl_read=[
                                    uuid.UUID("08e4d24f-8d50-535b-a7b5-d9bdf0cbb337")
                                ],
                                then=models.Value("INTERNAL"),
                            ),
                            models.When(
                                acl_read=[
                                    uuid.UUID("e62dac33-2b05-5be1-9417-e3d301ff57da")
                                ],
                                then=models.Value("PUBLIC"),
                            ),
                            default=models.Value("PUBLIC"),
                            output_field=models.CharField(),
                        ),
                        output_field=models.CharField(max_length=10),
                    ),
                ),
                (
                    "request_received_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was received", null=True
                    ),
                ),
                (
                    "request_source",
                    models.CharField(
                        blank=True, help_text="Source of the request", max_length=255
                    ),
                ),
                (
                    "request_text",
                    models.TextField(blank=True, help_text="Text of the request"),
                ),
                (
                    "manual_due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manual override for the due date",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "id", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."id", NEW."manual_due_at", NEW."milestone_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."updated_dt"); RETURN NULL;',
                    hash="beacfb7a3091cf9e93ddb7f523bab1759ed3deb2",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_63f0e",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "id", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."id", NEW."manual_due_at", NEW."milestone_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."updated_dt"); RETURN NULL;',
                    hash="9619527a1ae329cfad67369e79df13f908e254dc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_48e36",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "id", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."id", OLD."manual_due_at", OLD."milestone_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."updated_dt"); RETURN NULL;',
                    hash="3728ba10e6861e2ccc3fb2ab6ac012dbfb180bf0",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_8d3eb",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequestaudit",
            name="milestone",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="The milestone this additional information request belongs to",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="regulatory_reporting.srpreportmilestone",
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequestaudit",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequestaudit",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="regulatory_reporting.additionalinformationrequest",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequestaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ae6ee9231443aaff7055e7814645e0c164e20fdf",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_919f9",
                    table="regulatory_reporting_additionalinformationrequestaudit",
                    when="BEFORE",
                ),
            ),
        ),
    ]
