# Generated by Django 5.2.16 on 2026-09-22 18:59

import uuid

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_reporting", "0024_additionalinformationrequestaudit_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="additionalinformationrequest",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="additionalinformationrequest",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="additionalinformationrequest",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="additionalinformationrequest",
            name="id",
        ),
        migrations.RemoveField(
            model_name="additionalinformationrequestaudit",
            name="id",
        ),
        migrations.AddField(
            model_name="additionalinformationrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="additionalinformationrequestaudit",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."manual_due_at", NEW."milestone_id", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="bb45c213c4cfef6d14b20f7acd64bd7c6a19f0a0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_63f0e",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."manual_due_at", NEW."milestone_id", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="34310280e15d6b5e62c0a0baebb4d525c9bc83fc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_48e36",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="additionalinformationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_due_at", "milestone_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."manual_due_at", OLD."milestone_id", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="196388e44742fa6e1086fa0ce66954752c3ce696",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_8d3eb",
                    table="regulatory_reporting_additionalinformationrequest",
                    when="AFTER",
                ),
            ),
        ),
    ]
