# Generated by Django 5.2.16 on 2026-09-22 19:08
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "regulatory_reporting",
            "0025_remove_additionalinformationrequest_insert_insert_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalinformationrequestaudit",
            name="pgh_obj",
        ),
        migrations.AddField(
            model_name="additionalinformationrequestaudit",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="regulatory_reporting.additionalinformationrequest",
                null=True,
            ),
        ),
    ]
