# Generated by Django 5.2.16 on 2026-09-23 13:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0027_alter_additionalinformationrequestaudit_pgh_obj'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='additionalinformationrequest',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='additionalinformationrequest',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='additionalinformationrequest',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='additionalinformationrequest',
            name='manual_completion_notes',
            field=models.TextField(blank=True, help_text='Manual completion notes'),
        ),
        migrations.AddField(
            model_name='additionalinformationrequest',
            name='owner',
            field=models.CharField(blank=True, help_text='Owner of this additional information request', max_length=60),
        ),
        migrations.AddField(
            model_name='additionalinformationrequest',
            name='response_text',
            field=models.TextField(blank=True, help_text='Text of the response'),
        ),
        migrations.AddField(
            model_name='additionalinformationrequest',
            name='status',
            field=models.CharField(choices=[('required', 'Required'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('submitted', 'Submitted'), ('obsolete', 'Obsolete')], default='required', help_text='Current status of this additional information request', max_length=20),
        ),
        migrations.AddField(
            model_name='additionalinformationrequestaudit',
            name='manual_completion_notes',
            field=models.TextField(blank=True, help_text='Manual completion notes'),
        ),
        migrations.AddField(
            model_name='additionalinformationrequestaudit',
            name='owner',
            field=models.CharField(blank=True, help_text='Owner of this additional information request', max_length=60),
        ),
        migrations.AddField(
            model_name='additionalinformationrequestaudit',
            name='response_text',
            field=models.TextField(blank=True, help_text='Text of the response'),
        ),
        migrations.AddField(
            model_name='additionalinformationrequestaudit',
            name='status',
            field=models.CharField(choices=[('required', 'Required'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('submitted', 'Submitted'), ('obsolete', 'Obsolete')], default='required', help_text='Current status of this additional information request', max_length=20),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='additionalinformationrequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_completion_notes", "manual_due_at", "milestone_id", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "response_text", "status", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."manual_completion_notes", NEW."manual_due_at", NEW."milestone_id", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."response_text", NEW."status", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='a2aae8bf93ce4cd58bb5bf2e423de8569027778c', operation='INSERT', pgid='pgtrigger_insert_insert_63f0e', table='regulatory_reporting_additionalinformationrequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='additionalinformationrequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_completion_notes", "manual_due_at", "milestone_id", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "response_text", "status", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."manual_completion_notes", NEW."manual_due_at", NEW."milestone_id", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."response_text", NEW."status", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='31b628da779ea2372da15ff64be4c28d7d58d879', operation='UPDATE', pgid='pgtrigger_update_update_48e36', table='regulatory_reporting_additionalinformationrequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='additionalinformationrequest',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_additionalinformationrequestaudit" ("acl_read", "acl_write", "created_dt", "manual_completion_notes", "manual_due_at", "milestone_id", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "response_text", "status", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."manual_completion_notes", OLD."manual_due_at", OLD."milestone_id", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."response_text", OLD."status", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='a8d2befe924e20f280539b3b4c840462dbc701dd', operation='DELETE', pgid='pgtrigger_delete_delete_8d3eb', table='regulatory_reporting_additionalinformationrequest', when='AFTER')),
        ),
    ]
