# Generated by Django 3.2.6 on 2021-10-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affect",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="affectevent",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flaw",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flawcomment",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flawevent",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flawhistory",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flawmeta",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="flawmetaevent",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="tracker",
            old_name="attr",
            new_name="meta_attr",
        ),
        migrations.RenameField(
            model_name="trackerevent",
            old_name="attr",
            new_name="meta_attr",
        ),
    ]
