# Generated by Django 3.2.8 on 2021-10-21 09:31

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.fields.hstore_field


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0004_add_package_versions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affect",
            name="trackers",
        ),
        migrations.RemoveField(
            model_name="flaw",
            name="affects",
        ),
        migrations.RemoveField(
            model_name="flaw",
            name="meta",
        ),
        migrations.AddField(
            model_name="affect",
            name="flaw",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affects",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="affectevent",
            name="flaw",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="flawmeta",
            name="flaw",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="flawmetaevent",
            name="flaw",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="tracker",
            name="affect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trackers",
                to="osidb.affect",
            ),
        ),
        migrations.AddField(
            model_name="trackerevent",
            name="affect",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="osidb.affect",
            ),
        ),
        migrations.AlterField(
            model_name="affect",
            name="component",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="impact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "Novalue"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("IMPORTANT", "Important"),
                    ("CRITICAL", "Critical"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="affect",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="module_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="module_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="ps_component",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="ps_module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affect",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("NONE", "Novalue"),
                    ("FIX", "Fix"),
                    ("DEFER", "Defer"),
                    ("WONTFIX", "Wontfix"),
                    ("OOSS", "Ooss"),
                    ("DELEGATED", "Delegated"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="affect",
            name="statement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="component",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="impact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "Novalue"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("IMPORTANT", "Important"),
                    ("CRITICAL", "Critical"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="module_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="module_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="ps_component",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="ps_module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("NONE", "Novalue"),
                    ("FIX", "Fix"),
                    ("DEFER", "Defer"),
                    ("WONTFIX", "Wontfix"),
                    ("OOSS", "Ooss"),
                    ("DELEGATED", "Delegated"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="statement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackerevent",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(blank=True, null=True),
        ),
    ]
