# Generated by Django 3.2.8 on 2021-10-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0006_auto_20211021_1343"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracker",
            old_name="key",
            new_name="external_system_id",
        ),
        migrations.RenameField(
            model_name="trackerevent",
            old_name="key",
            new_name="external_system_id",
        ),
        migrations.AlterUniqueTogether(
            name="tracker",
            unique_together={("cve_id", "type", "external_system_id")},
        ),
    ]
