# Generated by Django 3.2.8 on 2021-10-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0007_auto_20211026_0617"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackerevent",
            name="cve_id",
        ),
        migrations.AlterUniqueTogether(
            name="tracker",
            unique_together={("affect", "type", "external_system_id")},
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="cve_id",
        ),
    ]
