# Generated by Django 3.2.9 on 2021-11-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0009_flaw_workflow_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flawmeta",
            options={"verbose_name": "FlawMeta"},
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGEMENT", "Acknowledgement"),
                    ("EXPLOIT", "Exploit"),
                    ("CSAW", "Csaw"),
                    ("CSAW_LITE", "Csaw Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGEMENT", "Acknowledgement"),
                    ("EXPLOIT", "Exploit"),
                    ("CSAW", "Csaw"),
                    ("CSAW_LITE", "Csaw Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flawmeta",
            unique_together={("flaw", "type", "meta_attr")},
        ),
    ]
