# Generated by Django 3.2.9 on 2021-11-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0010_auto_20211127_1652"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flawmeta",
            unique_together=set(),
        ),
    ]
