# Generated by Django 3.2.9 on 2021-11-29 06:43

from django.db import migrations, models
import osidb.validators


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0011_alter_flawmeta_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="flaw",
            name="nvd_cvss2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[osidb.validators.validate_cvss2],
            ),
        ),
        migrations.AddField(
            model_name="flaw",
            name="nvd_cvss3",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[osidb.validators.validate_cvss3],
            ),
        ),
        migrations.AddField(
            model_name="flawevent",
            name="nvd_cvss2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[osidb.validators.validate_cvss2],
            ),
        ),
        migrations.AddField(
            model_name="flawevent",
            name="nvd_cvss3",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[osidb.validators.validate_cvss3],
            ),
        ),
    ]
