# Generated by Django 3.2.9 on 2021-11-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0012_auto_20211129_0643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawmeta",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGMENT", "Acknowledgment"),
                    ("EXPLOIT", "Exploit"),
                    ("CSAW", "Csaw"),
                    ("CSAW_LITE", "Csaw Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGMENT", "Acknowledgment"),
                    ("EXPLOIT", "Exploit"),
                    ("CSAW", "Csaw"),
                    ("CSAW_LITE", "Csaw Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
