# Generated by Django 3.2.9 on 2021-12-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0013_rename_acks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affectevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="flawevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="flawmetaevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="trackerevent",
            name="pgh_obj",
        ),
    ]
