# Generated by Django 3.2.9 on 2021-12-01 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0014_auto_20211201_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="flawcomment",
            name="updated_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flawmeta",
            name="updated_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flawmetaevent",
            name="updated_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="flaw",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawcomment",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawhistory",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
