# Generated by Django 3.2.9 on 2021-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0016_auto_20211201_2157"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affect",
            name="state",
        ),
        migrations.RemoveField(
            model_name="affectevent",
            name="state",
        ),
        migrations.AddField(
            model_name="affect",
            name="affectedness",
            field=models.CharField(
                choices=[
                    ("NONE", "No value"),
                    ("NEW", "Unknown"),
                    ("AFFECTED", "Affected"),
                    ("NOT_AFFECTED", "Not affected"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affectevent",
            name="affectedness",
            field=models.CharField(
                choices=[
                    ("NONE", "No value"),
                    ("NEW", "Unknown"),
                    ("AFFECTED", "Affected"),
                    ("NOT_AFFECTED", "Not affected"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
