# Generated by Django 3.2.9 on 2021-12-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0017_affect_state_to_affectedness"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="resolution",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackerevent",
            name="resolution",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackerevent",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
