# Generated by Django 3.2.9 on 2021-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0020_fix_notaffected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaw",
            name="mitigated_by",
            field=models.CharField(
                blank=True,
                choices=[("SELINUX", "Selinux"), ("FORTIFY", "Fortify")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flaw",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("NONE", "Novalue"),
                    ("DUPLICATE", "Duplicate"),
                    ("WONTFIX", "Wontfix"),
                    ("NOTABUG", "Notabug"),
                    ("ERRATA", "Errata"),
                    ("CANTFIX", "Cantfix"),
                    ("DEFERRED", "Deferred"),
                    ("CURRENTRELEASE", "Currentrelease"),
                    ("UPSTREAM", "Upstream"),
                    ("RAWHIDE", "Rawhide"),
                    ("INSUFFICIENT_DATA", "Insufficient Data"),
                    ("NEXTRELEASE", "Nextrelease"),
                    ("WORKSFORME", "Worksforme"),
                    ("EOL", "Eol"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flaw",
            name="state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ON_QA", "On Qa"),
                    ("RELEASE_PENDING", "Release Pending"),
                    ("MODIFIED", "Modified"),
                    ("ASSIGNED", "Assigned"),
                    ("CLOSED", "Closed"),
                    ("POST", "Post"),
                    ("VERIFIED", "Verified"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="mitigated_by",
            field=models.CharField(
                blank=True,
                choices=[("SELINUX", "Selinux"), ("FORTIFY", "Fortify")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("NONE", "Novalue"),
                    ("DUPLICATE", "Duplicate"),
                    ("WONTFIX", "Wontfix"),
                    ("NOTABUG", "Notabug"),
                    ("ERRATA", "Errata"),
                    ("CANTFIX", "Cantfix"),
                    ("DEFERRED", "Deferred"),
                    ("CURRENTRELEASE", "Currentrelease"),
                    ("UPSTREAM", "Upstream"),
                    ("RAWHIDE", "Rawhide"),
                    ("INSUFFICIENT_DATA", "Insufficient Data"),
                    ("NEXTRELEASE", "Nextrelease"),
                    ("WORKSFORME", "Worksforme"),
                    ("EOL", "Eol"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ON_QA", "On Qa"),
                    ("RELEASE_PENDING", "Release Pending"),
                    ("MODIFIED", "Modified"),
                    ("ASSIGNED", "Assigned"),
                    ("CLOSED", "Closed"),
                    ("POST", "Post"),
                    ("VERIFIED", "Verified"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
