# Generated by Django 3.2.9 on 2021-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0021_auto_20211206_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="resolution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="trackerevent",
            name="resolution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="trackerevent",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
