# Generated by Django 3.2.9 on 2021-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0023_csaw_to_major_incident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaw",
            name="osim_workflow",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="osim_workflow",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
