# Generated by Django 3.2.9 on 2021-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0024_extend_workflow_name_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="ps_update_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackerevent",
            name="ps_update_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
