# Generated by Django 3.2.11 on 2022-02-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0027_remove_embargoed_attribute'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='affect',
            index=models.Index(fields=['-updated_dt'], name='osidb_affec_updated_0b1a47_idx'),
        ),
        migrations.AddIndex(
            model_name='flaw',
            index=models.Index(fields=['-updated_dt'], name='osidb_flaw_updated_090116_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['-updated_dt'], name='osidb_track_updated_6f27c1_idx'),
        ),
        migrations.AddIndex(
            model_name='flaw',
            index=models.Index(fields=['-cve_id'], name='osidb_flaw_cve_id_dd22ae_idx'),
        ),
    ]
