# Generated by Django 3.2.12 on 2022-03-14 12:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0028_flaw_osidb_flaw_cve_id_dd22ae_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsContact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('bz_username', models.CharField(max_length=100, null=True)),
                ('jboss_username', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsModule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('public_description', models.TextField(null=True)),
                ('cpe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('private_trackers_allowed', models.BooleanField(default=False)),
                ('autofile_trackers', models.BooleanField(default=False)),
                ('special_handling_features', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('bts_name', models.CharField(max_length=50)),
                ('bts_key', models.CharField(max_length=100)),
                ('bts_groups', models.JSONField(default=dict)),
                ('supported_from_dt', models.DateTimeField(null=True)),
                ('supported_until_dt', models.DateTimeField(null=True)),
                ('default_cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('private_tracker_cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('component_cc', models.JSONField(default=dict)),
                ('default_component', models.CharField(max_length=100)),
                ('component_overrides', models.JSONField(default=dict)),
                ('unacked_ps_update_stream', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('business_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PsUpdateStream',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('target_release', models.CharField(max_length=50, null=True)),
                ('rhsa_sla_applicable', models.BooleanField(default=True)),
                ('additional_fields', models.JSONField(default=dict)),
                ('collections', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('flags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('active_to_ps_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_ps_update_streams', to='osidb.psmodule')),
                ('aus_to_ps_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_ps_update_streams', to='osidb.psmodule')),
                ('default_to_ps_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_ps_update_streams', to='osidb.psmodule')),
                ('eus_to_ps_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eus_ps_update_streams', to='osidb.psmodule')),
                ('ps_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_update_streams', to='osidb.psmodule')),
            ],
        ),
        migrations.AddField(
            model_name='psmodule',
            name='ps_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps_modules', to='osidb.psproduct'),
        ),
    ]
