# Generated by Django 3.2.12 on 2022-04-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0030_correct_created_updated_dt'),
    ]

    operations = [
        # disable RLS for the tables to be changed note that this is all
        # run in a single transaction so there's no risk for concurrent
        # queries
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_flaw
            DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_affect
            DISABLE ROW LEVEL SECURITY;
            """
        ),
        # RLS on event tables must be disabled too due to triggers
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_affectevent
            DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_tracker
            DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_trackerevent
            DISABLE ROW LEVEL SECURITY;
            """
        ),
        # update affect's created_dt and updated_dt
        # to the values of their related flaw
        migrations.RunSQL(
            """
            UPDATE
                osidb_affect AS affect
            SET
                created_dt = flaw.created_dt,
                updated_dt = flaw.updated_dt
            FROM
                osidb_flaw AS flaw
            WHERE
                affect.flaw_id = flaw.uuid;
            """
        ),
        # update tracker's created_dt and updated_dt
        # to the values of their related affects
        migrations.RunSQL(
            """
            UPDATE
                osidb_tracker AS tracker
            SET
                created_dt = affect.created_dt,
                updated_dt = affect.created_dt
            FROM
                osidb_tracker_affects AS tracker_affect,
                osidb_affect AS affect
            WHERE
                tracker.uuid = tracker_affect.tracker_id
                AND
                affect.uuid = tracker_affect.affect_id;
            """
        ),
        # re-enable RLS
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_flaw
            ENABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_affect
            ENABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_affectevent
            ENABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_tracker
            ENABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE
                osidb_trackerevent
            ENABLE ROW LEVEL SECURITY;
            """
        ),
    ]
