# Generated by Django 3.2.12 on 2022-04-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('osidb', '0031_correct_created_updated_dt_affects_trackers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('bz_user_id', models.CharField(max_length=100, null=True)),
                ('jira_user_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
