# Generated by Django 3.2.13 on 2022-04-25 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0003_auto_20201023_1636"),
        ("osidb", "0036_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErratumEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                ("et_id", models.IntegerField()),
                ("advisory_name", models.CharField(max_length=20)),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Erratum",
            fields=[
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("et_id", models.IntegerField(unique=True)),
                ("advisory_name", models.CharField(max_length=20, unique=True)),
                (
                    "trackers",
                    models.ManyToManyField(related_name="errata", to="osidb.Tracker"),
                ),
            ],
            options={
                "verbose_name": "Erratum",
                "verbose_name_plural": "Errata",
            },
        ),
    ]
