# Generated by Django 3.2.13 on 2022-04-29 16:57

from django.db import migrations, models

import osidb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0038_alter_flaw_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='cve_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, validators=[osidb.validators.validate_cve_id]),
        ),
        migrations.AlterField(
            model_name='flawevent',
            name='cve_id',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[osidb.validators.validate_cve_id]),
        ),
    ]
