# Generated by Django 3.2.12 on 2022-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0039_flaw_cve_id_allow_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="flawcomment",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
