# Generated by Django 3.2.13 on 2022-05-13 12:26

from django.db import migrations, models
import osidb.validators
import psqlextra.fields.hstore_field


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0044_flaw_required_fields_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flawhistory',
            name='cve_id',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='cvss2',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss2]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='cvss3',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss3]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='cwe_id',
            field=models.CharField(blank=True, default='', max_length=50, validators=[osidb.validators.validate_cwe_id]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='impact',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('IMPORTANT', 'Important'), ('CRITICAL', 'Critical')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='is_major_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='meta_attr',
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='mitigated_by',
            field=models.CharField(blank=True, choices=[('SELINUX', 'Selinux'), ('FORTIFY', 'Fortify'), ('GRSEC', 'Grsec')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='resolution',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('DUPLICATE', 'Duplicate'), ('WONTFIX', 'Wontfix'), ('NOTABUG', 'Notabug'), ('ERRATA', 'Errata'), ('CANTFIX', 'Cantfix'), ('DEFERRED', 'Deferred'), ('CURRENTRELEASE', 'Currentrelease'), ('UPSTREAM', 'Upstream'), ('RAWHIDE', 'Rawhide'), ('INSUFFICIENT_DATA', 'Insufficient Data'), ('NEXTRELEASE', 'Nextrelease'), ('WORKSFORME', 'Worksforme'), ('EOL', 'Eol')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='source',
            field=models.CharField(blank=True, choices=[('ADOBE', 'Adobe'), ('APPLE', 'Apple'), ('ASF', 'Asf'), ('BIND', 'Bind'), ('BK', 'Bk'), ('BUGTRAQ', 'Bugtraq'), ('BUGZILLA', 'Bugzilla'), ('CERT', 'Cert'), ('CERTIFI', 'Certfi'), ('CORELABS', 'Corelabs'), ('CUSTOMER', 'Customer'), ('CVE', 'Cve'), ('DAILYDAVE', 'Dailydave'), ('DEBIAN', 'Debian'), ('DISTROS', 'Distros'), ('FEDORA', 'Fedora'), ('FETCHMAIL', 'Fetchmail'), ('FREEDESKTOP', 'Freedesktop'), ('FREERADIUS', 'Freeradius'), ('FRSIRT', 'Frsirt'), ('FULLDISCLOSURE', 'Full Disclosure'), ('GAIM', 'Gaim'), ('GENTOO', 'Gentoo'), ('GENTOOBZ', 'Gentoobz'), ('GIT', 'Git'), ('GNOME', 'Gnome'), ('GNUPG', 'Gnupg'), ('GOOGLE', 'Google'), ('HP', 'Hp'), ('HW_VENDOR', 'Hw Vendor'), ('IDEFENSE', 'Idefense'), ('INDIVIDUAL', 'Individual'), ('INTERNET', 'Internet'), ('ISC', 'Isc'), ('ISEC', 'Isec'), ('JBOSS', 'Jboss'), ('JPCERT', 'Jpcert'), ('KERNELBUGZILLA', 'Kernelbugzilla'), ('KERNELSEC', 'Kernelsec'), ('LKML', 'Lkml'), ('LWN', 'Lwn'), ('MACROMEDIA', 'Macromedia'), ('MAGEIA', 'Mageia'), ('MAILINGLIST', 'Mailinglist'), ('MILW0RM', 'Milw0Rm'), ('MIT', 'Mit'), ('MITRE', 'Mitre'), ('MOZILLA', 'Mozilla'), ('MUTTDEV', 'Muttdev'), ('NETDEV', 'Netdev'), ('NISCC', 'Niscc'), ('', 'Novalue'), ('OCERT', 'Ocert'), ('OPENOFFICE', 'Openoffice'), ('OPENSSL', 'Openssl'), ('OPENSUSE', 'Opensuse'), ('ORACLE', 'Oracle'), ('OSS', 'Oss'), ('OSSSECURITY', 'Oss Security'), ('PHP', 'Php'), ('PIDGIN', 'Pidgin'), ('POSTGRESQL', 'Postgresql'), ('PRESS', 'Press'), ('REAL', 'Real'), ('REDHAT', 'Redhat'), ('RESEARCHER', 'Researcher'), ('RT', 'Rt'), ('SAMBA', 'Samba'), ('SECALERT', 'Secalert'), ('SECUNIA', 'Secunia'), ('SECURITYFOCUS', 'Securityfocus'), ('SKO', 'Sko'), ('SQUID', 'Squid'), ('SQUIRRELMAIL', 'Squirrelmail'), ('SUN', 'Sun'), ('SUNSOLVE', 'Sunsolve'), ('SUSE', 'Suse'), ('TWITTER', 'Twitter'), ('UBUNTU', 'Ubuntu'), ('UPSTREAM', 'Upstream'), ('VENDORSEC', 'Vendor Sec'), ('VULNWATCH', 'Vulnwatch'), ('WIRESHARK', 'Wireshark'), ('XCHAT', 'Xchat'), ('XEN', 'Xen'), ('XPDF', 'Xpdf')], default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='state',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed'), ('MODIFIED', 'Modified'), ('NEW', 'New'), ('ON_DEV', 'On Dev'), ('ON_QA', 'On Qa'), ('POST', 'Post'), ('RELEASE_PENDING', 'Release Pending'), ('VERIFIED', 'Verified')], default='NEW', max_length=100),
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='statement',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='summary',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawhistory',
            name='type',
            field=models.CharField(choices=[('VULNERABILITY', 'Vuln'), ('WEAKNESS', 'Weak')], default='VULNERABILITY', max_length=20),
        ),
    ]
