# Generated by Django 3.2.13 on 2022-05-09 19:05

from django.db import migrations, models
import osidb.validators
import psqlextra.fields.hstore_field


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0045_flaw_history_required_fields_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affect',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='affectevent',
            name='statement',
        ),
        migrations.AlterField(
            model_name='affect',
            name='affectedness',
            field=models.CharField(blank=True, choices=[('', 'No value'), ('NEW', 'Unknown'), ('AFFECTED', 'Affected'), ('NOTAFFECTED', 'Not affected')], default='NEW', max_length=100),
        ),
        migrations.AlterField(
            model_name='affect',
            name='cvss2',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss2]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affect',
            name='cvss3',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss3]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affect',
            name='impact',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('IMPORTANT', 'Important'), ('CRITICAL', 'Critical')], default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affect',
            name='meta_attr',
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='affect',
            name='ps_component',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affect',
            name='ps_module',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affect',
            name='resolution',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('FIX', 'Fix'), ('DEFER', 'Defer'), ('WONTFIX', 'Wontfix'), ('OOSS', 'Ooss'), ('DELEGATED', 'Delegated'), ('WONTREPORT', 'Wontreport')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='affect',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default')], default='DEFAULT', max_length=10),
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='affectedness',
            field=models.CharField(blank=True, choices=[('', 'No value'), ('NEW', 'Unknown'), ('AFFECTED', 'Affected'), ('NOTAFFECTED', 'Not affected')], default='NEW', max_length=100),
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='cvss2',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss2]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='cvss3',
            field=models.CharField(blank=True, default='', max_length=100, validators=[osidb.validators.validate_cvss3]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='impact',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('IMPORTANT', 'Important'), ('CRITICAL', 'Critical')], default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='meta_attr',
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='ps_component',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='ps_module',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='resolution',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('FIX', 'Fix'), ('DEFER', 'Defer'), ('WONTFIX', 'Wontfix'), ('OOSS', 'Ooss'), ('DELEGATED', 'Delegated'), ('WONTREPORT', 'Wontreport')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='affectevent',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default')], default='DEFAULT', max_length=10),
        ),
    ]
