# Generated by Django 3.2.13 on 2022-05-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0047_tracker_required_fields_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='osim_state',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('ANALYSIS', 'Analysis'), ('REVIEW', 'Review'), ('FIX', 'Fix'), ('DONE', 'Done')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flaw',
            name='osim_workflow',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawevent',
            name='osim_state',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('ANALYSIS', 'Analysis'), ('REVIEW', 'Review'), ('FIX', 'Fix'), ('DONE', 'Done')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flawevent',
            name='osim_workflow',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
