# Generated by Django 3.2.13 on 2022-05-16 08:06

import django.contrib.postgres.fields
import django.db.models.deletion
import psqlextra.fields.hstore_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0048_workflow_model_required_fields_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawcomment",
            name="external_system_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawcomment",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name="flawcomment",
            name="type",
            field=models.CharField(
                choices=[("BUGZILLA", "Bugzilla")], default="BUGZILLA", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGMENT", "Acknowledgment"),
                    ("EXPLOIT", "Exploit"),
                    ("MAJOR_INCIDENT", "Major Incident"),
                    ("MAJOR_INCIDENT_LITE", "Major Incident Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                default="",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="meta_attr",
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("REFERENCE", "Reference"),
                    ("ACKNOWLEDGMENT", "Acknowledgment"),
                    ("EXPLOIT", "Exploit"),
                    ("MAJOR_INCIDENT", "Major Incident"),
                    ("MAJOR_INCIDENT_LITE", "Major Incident Lite"),
                    ("REQUIRES_DOC_TEXT", "Requires Doc Text"),
                    ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                    ("NEED_INFO", "Need Info"),
                    ("CHECKLIST", "Checklist"),
                    ("NVD_CVSS", "Nvd Cvss"),
                ],
                default="",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="component_cc",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="component_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="cpe",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="default_cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="default_component",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="private_tracker_cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="public_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="special_handling_features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="supported_from_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="supported_until_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="unacked_ps_update_stream",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="active_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="additional_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="aus_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aus_ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="collections",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="default_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="eus_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eus_ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="version",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="psupdatestream",
            name="target_release",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pscontact",
            name="bz_username",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pscontact",
            name="jboss_username",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="bz_user_id",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="jira_user_id",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
