# Generated by Django 3.2.13 on 2022-05-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0050_add_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affect',
            options={'ordering': ('created_dt', 'uuid'), 'verbose_name': 'Affect'},
        ),
        migrations.AlterModelOptions(
            name='flaw',
            options={'ordering': ('created_dt', 'uuid'), 'verbose_name': 'Flaw'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ('created_dt', 'uuid'), 'verbose_name': 'Tracker'},
        ),
    ]
