# Generated by Django 3.2.13 on 2022-05-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0052_dt_data_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flawhistory",
            options={"verbose_name": "FlawHistory"},
        ),
        migrations.RemoveField(
            model_name="flawhistory",
            name="created_dt",
        ),
        migrations.RemoveField(
            model_name="flawhistory",
            name="updated_dt",
        ),
    ]
