# Generated by Django 3.2.13 on 2022-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0053_remove_tracking_mixin_from_flawhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affect",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="affect",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="affectevent",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erratum",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erratum",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erratumevent",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erratumevent",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flaw",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flaw",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawcomment",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawcomment",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawevent",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmeta",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flawmetaevent",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracker",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracker",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trackerevent",
            name="created_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trackerevent",
            name="updated_dt",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
