# Generated by Django 3.2.13 on 2022-05-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0055_text_choices_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packageversions",
            name="acl_read",
        ),
        migrations.RemoveField(
            model_name="packageversions",
            name="acl_write",
        ),
        migrations.RemoveField(
            model_name="version",
            name="acl_read",
        ),
        migrations.RemoveField(
            model_name="version",
            name="acl_write",
        ),
    ]
