# Generated by Django 3.2.13 on 2022-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0056_remove_packageversions_acls'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO
            $$
            DECLARE
                r record;
            BEGIN
                FOR r IN
                    SELECT oid, relname FROM pg_class WHERE relname LIKE 'osidb_%event%'
                LOOP
                    EXECUTE 'DELETE FROM pg_class WHERE oid=' || r.oid;
                    EXECUTE 'DELETE FROM pg_depend WHERE objid=' || r.oid;
                    EXECUTE 'DELETE FROM pg_constraint WHERE conrelid=' || r.oid;
                    EXECUTE 'DELETE FROM pg_policy WHERE polrelid=' || r.oid;
                    EXECUTE 'DELETE FROM pg_type WHERE typrelid=' || r.oid;
                    EXECUTE 'CREATE TABLE ' || quote_ident(r.relname) || ' (pgh_context_id integer, flaw_id integer)';
                END LOOP;
            END
            $$;
            """
        ),
        migrations.RemoveField(
            model_name='erratumevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='flawevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='flawmetaevent',
            name='flaw',
        ),
        migrations.RemoveField(
            model_name='flawmetaevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='trackerevent',
            name='pgh_context',
        ),
        migrations.DeleteModel(
            name='AffectEvent',
        ),
        migrations.DeleteModel(
            name='ErratumEvent',
        ),
        migrations.DeleteModel(
            name='FlawEvent',
        ),
        migrations.DeleteModel(
            name='FlawMetaEvent',
        ),
        migrations.DeleteModel(
            name='TrackerEvent',
        ),
    ]
