# Generated by Django 3.2.13 on 2022-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0056_remove_packageversions_acls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erratumevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='flawevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='flawmetaevent',
            name='flaw',
        ),
        migrations.RemoveField(
            model_name='flawmetaevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='trackerevent',
            name='pgh_context',
        ),
        migrations.DeleteModel(
            name='AffectEvent',
        ),
        migrations.DeleteModel(
            name='ErratumEvent',
        ),
        migrations.DeleteModel(
            name='FlawEvent',
        ),
        migrations.DeleteModel(
            name='FlawMetaEvent',
        ),
        migrations.DeleteModel(
            name='TrackerEvent',
        ),
    ]
