# Generated by Django 3.2.14 on 2022-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0058_affect__alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
