# Generated by Django 3.2.15 on 2022-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0001_initial_squashed_0059_flaw__alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaw",
            name="mitigated_by",
            field=models.CharField(
                blank=True,
                choices=[("SELINUX", "Selinux"), ("FORTIFY", "Fortify")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flawhistory",
            name="mitigated_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELINUX", "Selinux"),
                    ("FORTIFY", "Fortify"),
                    ("GRSEC", "Grsec"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
