# Generated by Django 3.2.15 on 2022-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0060_mitigated_by_null_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="flawmeta",
            name="_alerts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
