# Generated by Django 3.2.15 on 2022-10-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0061_flawmeta__alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawmeta",
            name="flaw",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="osidb.flaw",
            ),
            preserve_default=False,
        ),
    ]
