# Generated by Django 3.2.15 on 2022-12-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0062_alter_flawmeta_flaw"),
    ]

    operations = [
        migrations.AddField(
            model_name="psupdatestream",
            name="unacked_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unacked_ps_update_stream_tmp",
                to="osidb.psmodule",
            ),
        ),
        migrations.AlterField(
            model_name="psmodule",
            name="unacked_ps_update_stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
