# Generated by Django 3.2.15 on 2022-12-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0063_link_unacked_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affect",
            name="ps_component",
            field=models.CharField(max_length=255),
        ),
    ]
