# Generated by Django 3.2.15 on 2022-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0065_fix_unacked_stream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
