# Generated by Django 3.2.15 on 2023-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0067_remove_mitigated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='mitigation',
            field=models.TextField(blank=True),
        ),
    ]
