# Generated by Django 3.2.15 on 2023-03-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0070_deprecate_fields_in_flaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flawhistory',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='flawhistory',
            name='state',
        ),
    ]
