# Generated by Django 3.2.18 on 2023-03-30 11:48

from django.db import migrations, models
import osidb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0071_remove_fields_from_flawhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='cwe_id',
            field=models.CharField(blank=True, max_length=255, validators=[osidb.validators.validate_cwe_id]),
        ),
    ]
