# Generated by Django 3.2.18 on 2023-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0072_alter_flaw_cwe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flawmeta',
            name='type',
            field=models.CharField(choices=[('ERRATA', 'Errata'), ('REFERENCE', 'Reference'), ('ACKNOWLEDGMENT', 'Acknowledgment'), ('EXPLOIT', 'Exploit'), ('MAJOR_INCIDENT', 'Major Incident'), ('MAJOR_INCIDENT_LITE', 'Major Incident Lite'), ('REQUIRES_SUMMARY', 'Requires Summary'), ('NIST_CVSS_VALIDATION', 'Nist Cvss Validation'), ('NEED_INFO', 'Need Info'), ('CHECKLIST', 'Checklist'), ('NVD_CVSS', 'Nvd Cvss')], max_length=500),
        ),
        migrations.RunSQL(
            """
            UPDATE
                osidb_flawmeta
            SET
                type = 'REQUIRES_SUMMARY'
            WHERE
                type = 'REQUIRES_DOC_TEXT';
            """
        ),
    ]
