# Generated by Django 3.2.18 on 2023-05-09 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0074_auto_20230420_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlawReference',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('_alerts', models.JSONField(blank=True, default=dict)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ARTICLE', 'Article'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=50)),
                ('url', models.URLField(max_length=2048)),
                ('description', models.TextField(blank=True)),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='osidb.flaw')),
            ],
            options={
                'unique_together': {('flaw', 'url')},
            },
        ),
    ]
