# Generated by Django 3.2.19 on 2023-06-12 17:42

from django.db import migrations
import psqlextra.fields.hstore_field


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0075_flawreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='flawreference',
            name='meta_attr',
            field=psqlextra.fields.hstore_field.HStoreField(default=dict),
        ),
    ]
