# Generated by Django 3.2.18 on 2023-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0075_flawreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flawcomment',
            options={'ordering': ('order', 'external_system_id', 'uuid', 'created_dt')},
        ),
        migrations.AddField(
            model_name='flawcomment',
            name='_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='flawcomment',
            name='external_system_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
