# Generated by Django 3.2.19 on 2023-06-16 10:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0076_alter_flawcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSS',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('_alerts', models.JSONField(blank=True, default=dict)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.CharField(max_length=100)),
                ('version', models.CharField(choices=[('V2', 'version 2'), ('V3', 'version 3')], default='V3', max_length=2)),
                ('issuer', models.CharField(choices=[('RH', 'Red Hat'), ('NIST', 'NIST')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('score', models.FloatField(default=0)),
                ('affect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvss_scores', to='osidb.affect')),
                ('flaw', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvss_scores', to='osidb.flaw')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cvss',
            constraint=models.UniqueConstraint(fields=('flaw', 'version', 'issuer'), name='unique CVSS of a Flaw'),
        ),
        migrations.AddConstraint(
            model_name='cvss',
            constraint=models.UniqueConstraint(fields=('affect', 'version', 'issuer'), name='unique CVSS of an Affect'),
        ),
    ]
