# Generated by Django 3.2.19 on 2023-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0077_alter_flawcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='major_incident_state',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('REQUESTED', 'Requested'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CISA_APPROVED', 'Cisa Approved'), ('INVALID', 'Invalid')], max_length=20),
        ),
    ]
