# Generated by Django 3.2.19 on 2023-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0079_flawacknowledgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flawacknowledgment',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
