# Generated by Django 3.2.19 on 2023-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0082_migrate_flawacknowledgment_flawmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='is_major_incident',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
