# Generated by Django 3.2.19 on 2023-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0083_alter_flaw_is_major_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='requires_summary',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
