# Generated by Django 3.2.20 on 2023-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0084_flaw_requires_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='nist_cvss_validation',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
