# Generated by Django 3.2.20 on 2023-08-01 15:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import osidb.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0085_flaw_nist_cvss_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlawDraft',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('_alerts', models.JSONField(blank=True, default=dict)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('component', models.CharField(blank=True, max_length=100)),
                ('impact', models.CharField(blank=True, choices=[('', 'Novalue'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('IMPORTANT', 'Important'), ('CRITICAL', 'Critical')], max_length=20)),
                ('source', models.CharField(blank=True, choices=[('ADOBE', 'Adobe'), ('APPLE', 'Apple'), ('ASF', 'Asf'), ('BIND', 'Bind'), ('BK', 'Bk'), ('BUGTRAQ', 'Bugtraq'), ('BUGZILLA', 'Bugzilla'), ('CERT', 'Cert'), ('CERTIFI', 'Certfi'), ('CORELABS', 'Corelabs'), ('CUSTOMER', 'Customer'), ('CVE', 'Cve'), ('DAILYDAVE', 'Dailydave'), ('DEBIAN', 'Debian'), ('DISTROS', 'Distros'), ('FEDORA', 'Fedora'), ('FETCHMAIL', 'Fetchmail'), ('FREEDESKTOP', 'Freedesktop'), ('FREERADIUS', 'Freeradius'), ('FRSIRT', 'Frsirt'), ('FULLDISCLOSURE', 'Full Disclosure'), ('GAIM', 'Gaim'), ('GENTOO', 'Gentoo'), ('GENTOOBZ', 'Gentoobz'), ('GIT', 'Git'), ('GNOME', 'Gnome'), ('GNUPG', 'Gnupg'), ('GOOGLE', 'Google'), ('HP', 'Hp'), ('HW_VENDOR', 'Hw Vendor'), ('IBM', 'Ibm'), ('IDEFENSE', 'Idefense'), ('INTERNET', 'Internet'), ('ISC', 'Isc'), ('ISEC', 'Isec'), ('IT', 'It'), ('JBOSS', 'Jboss'), ('JPCERT', 'Jpcert'), ('KERNELBUGZILLA', 'Kernelbugzilla'), ('KERNELSEC', 'Kernelsec'), ('LKML', 'Lkml'), ('LWN', 'Lwn'), ('MACROMEDIA', 'Macromedia'), ('MAGEIA', 'Mageia'), ('MAILINGLIST', 'Mailinglist'), ('MILW0RM', 'Milw0Rm'), ('MIT', 'Mit'), ('MITRE', 'Mitre'), ('MOZILLA', 'Mozilla'), ('MUTTDEV', 'Muttdev'), ('NETDEV', 'Netdev'), ('NISCC', 'Niscc'), ('', 'Novalue'), ('OCERT', 'Ocert'), ('OPENOFFICE', 'Openoffice'), ('OPENSSL', 'Openssl'), ('OPENSUSE', 'Opensuse'), ('ORACLE', 'Oracle'), ('OSS', 'Oss'), ('OSSSECURITY', 'Oss Security'), ('PHP', 'Php'), ('PIDGIN', 'Pidgin'), ('POSTGRESQL', 'Postgresql'), ('PRESS', 'Press'), ('REAL', 'Real'), ('REDHAT', 'Redhat'), ('RESEARCHER', 'Researcher'), ('RT', 'Rt'), ('SAMBA', 'Samba'), ('SECALERT', 'Secalert'), ('SECUNIA', 'Secunia'), ('SECURITYFOCUS', 'Securityfocus'), ('SKO', 'Sko'), ('SQUID', 'Squid'), ('SQUIRRELMAIL', 'Squirrelmail'), ('SUN', 'Sun'), ('SUNSOLVE', 'Sunsolve'), ('SUSE', 'Suse'), ('TWITTER', 'Twitter'), ('UBUNTU', 'Ubuntu'), ('UPSTREAM', 'Upstream'), ('VENDORSEC', 'Vendor Sec'), ('VULNWATCH', 'Vulnwatch'), ('WIRESHARK', 'Wireshark'), ('XCHAT', 'Xchat'), ('XEN', 'Xen'), ('XPDF', 'Xpdf')], max_length=500)),
                ('unembargo_dt', models.DateTimeField(blank=True, null=True)),
                ('reported_dt', models.DateTimeField(blank=True, null=True, validators=[osidb.validators.no_future_date])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.URLField(max_length=2048)),
                ('content', models.JSONField()),
                ('checked', models.BooleanField(default=False)),
                ('flaw', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='osidb.flaw')),
            ],
            options={
                'ordering': ('-created_dt', 'uuid'),
            },
        ),
        migrations.AddIndex(
            model_name='flawdraft',
            index=models.Index(fields=['-created_dt'], name='osidb_flawd_created_e389e0_idx'),
        ),
    ]
