# Generated by Django 3.2.20 on 2023-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0087_migrate_flaw_flag_nist_cvss_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="external_system_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
