# Generated by Django 3.2.20 on 2023-08-22 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0088_alter_tracker_external_system_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialConsiderationPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbiPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('major_stream_version', models.CharField(max_length=100)),
            ],
        ),
    ]
