# Generated by Django 3.2.20 on 2023-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0089_specialconsiderationpackage_ubipackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="erratum",
            name="shipped_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
