# Generated by Django 3.2.20 on 2023-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0090_erratum_shipped_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectcvss',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
    ]
