# Generated by Django 3.2.20 on 2023-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0090_erratum_shipped_dt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['external_system_id'], name='osidb_track_externa_e806e0_idx'),
        ),
    ]
