# Generated by Django 3.2.20 on 2023-08-23 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0093_migrate_cvss_to_affectcvss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=2048)),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_versions', to='osidb.flaw')),
            ],
        ),
        migrations.AlterModelOptions(
            name='packageversions',
            options={'verbose_name': 'Old Package Versions'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Old Version'},
        ),
        migrations.AlterField(
            model_name='packageversions',
            name='flaw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_package_versions', to='osidb.flaw'),
        ),
        migrations.CreateModel(
            name='PackageVer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=1024)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='osidb.package')),
            ],
            options={
                'verbose_name': 'Version',
            },
        ),
    ]
