# Generated by Django 3.2.20 on 2023-08-25 08:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0094_cvev5_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='acl_read',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='package',
            name='acl_write',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='package',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
