# Generated by Django 3.2.20 on 2023-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0095_cvev5_acl_tracking_mixins'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
