# Generated by Django 3.2.20 on 2023-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0097__migrate_cvev5package_cvev5ver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pscontact",
            name="bz_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pscontact",
            name="jboss_username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
