# Generated by Django 3.2.20 on 2023-10-23 15:37

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0100_fix_affectcvss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('_alerts', models.JSONField(blank=True, default=dict)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('NVD', 'Nvd')], max_length=100)),
                ('content', models.JSONField(default=dict)),
                ('flaws', models.ManyToManyField(blank=True, related_name='snippets', to='osidb.Flaw')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
