# Generated by Django 3.2.20 on 2023-10-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0101_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlawDraft',
        ),
    ]
