# Generated by Django 3.2.20 on 2023-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0103_alter_flawreference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='group_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='flaw',
            name='owner',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='flaw',
            name='task_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='flaw',
            name='team_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='osim_state',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('TRIAGE', 'Triage'), ('PRE_SECONDARY_ASSESSMENT', 'Pre Secondary Assessment'), ('SECONDARY_ASSESSMENT', 'Secondary Assessment'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], max_length=24),
        ),
    ]
