# Generated by Django 3.2.20 on 2023-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0104_auto_20231120_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.CharField(choices=[('NVD', 'Nvd'), ('Packet Storm Advisory Files', 'Feed Packetstorm'), ('Node.js Vulnerability Reports', 'Feed Nodejs'), ('Google Chrome Releases', 'Feed Chrome'), ('Elastic.co Security Announcements', 'Feed Elastic')], max_length=100),
        ),
    ]
