# Generated by Django 3.2.20 on 2023-11-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0105_remove_snippet_flaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='flaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='osidb.flaw'),
        ),
    ]
