# Generated by Django 3.2.23 on 2023-12-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0107_flawsource_nvd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaw',
            old_name='osim_workflow',
            new_name='workflow_name',
        ),
        migrations.RenameField(
            model_name='flaw',
            old_name='osim_state',
            new_name='workflow_state',
        ),
    ]
