# Generated by Django 3.2.23 on 2023-11-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osidb", "0107_flawsource_nvd"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="external_id",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="snippet",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_snippets"
            ),
        ),
    ]
