# Generated by Django 3.2.23 on 2023-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osidb", "0109_compliancepriority"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="external_id",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="affectcvss",
            name="issuer",
            field=models.CharField(
                choices=[("RH", "Red Hat"), ("NIST", "NIST"), ("OSV", "OSV")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="flawcvss",
            name="issuer",
            field=models.CharField(
                choices=[("RH", "Red Hat"), ("NIST", "NIST"), ("OSV", "OSV")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="source",
            field=models.CharField(
                choices=[("NVD", "Nvd"), ("OSV", "Osv")], max_length=100
            ),
        ),
        migrations.AddConstraint(
            model_name="snippet",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_snippets"
            ),
        ),
    ]
