# Generated by Django 3.2.23 on 2024-01-04 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0113_flaw_local_updated_dt_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='local_updated_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
