# Generated by Django 3.2.23 on 2024-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0114_flaw_local_updated_dt_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
