# Generated by Django 3.2.23 on 2024-01-30 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0115_alter_tracker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPriority',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ps_module', models.CharField(max_length=100)),
                ('ps_component', models.CharField(max_length=255)),
            ],
        ),
    ]
