# Generated by Django 3.2.23 on 2024-02-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0117_rename_ps_component_contractpriority_ps_update_stream"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psmodule",
            name="private_tracker_cc",
        ),
    ]
