# Generated by Django 3.2.24 on 2024-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0118_remove_psmodule_private_tracker_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancepriority',
            name='ps_component',
        ),
        migrations.AddField(
            model_name='compliancepriority',
            name='components',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='compliancepriority',
            name='streams',
            field=models.JSONField(default=list),
        ),
    ]
