# Generated by Django 3.2.24 on 2024-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0119_alter_compliancepriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectcvss',
            name='version',
            field=models.CharField(choices=[('V2', 'version 2'), ('V3', 'version 3'), ('V4', 'version 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flawcvss',
            name='version',
            field=models.CharField(choices=[('V2', 'version 2'), ('V3', 'version 3'), ('V4', 'version 4')], max_length=10),
        ),
    ]
