# Generated by Django 3.2.25 on 2024-03-22 12:47

from django.db import migrations
from django.conf import settings

from osidb.core import set_user_acls


BATCH_SIZE = 1000


def forwards_func(apps, schema_editor):
    set_user_acls(settings.ALL_GROUPS)
    Flaw = apps.get_model("osidb", "Flaw")

    # Map applied from outdated to current workflow states:
    # DRAFT -> NEW
    # ANALYSIS -> TRIAGE
    # REVIEW -> SECONDARY_ASSESSMENT
    # FIX -> SECONDARY_ASSESSMENT
    Flaw.objects.filter(workflow_state="DRAFT").update(workflow_state="NEW")
    Flaw.objects.filter(workflow_state="ANALYSIS").update(workflow_state="TRIAGE")
    Flaw.objects.filter(workflow_state="REVIEW").update(
        workflow_state="SECONDARY_ASSESSMENT"
    )
    Flaw.objects.filter(workflow_state="FIX").update(
        workflow_state="SECONDARY_ASSESSMENT"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0120_alter_cvss_version"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop, atomic=True)
    ]
