# Generated by Django 3.2.24 on 2024-03-25 12:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import osidb.validators
import pgtrigger.compiler
import pgtrigger.migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
        ("osidb", "0122_flaw_components"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffectAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEFAULT", "Default")],
                        default="DEFAULT",
                        max_length=10,
                    ),
                ),
                (
                    "affectedness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No value"),
                            ("NEW", "Unknown"),
                            ("AFFECTED", "Affected"),
                            ("NOTAFFECTED", "Not affected"),
                        ],
                        default="NEW",
                        max_length=100,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("FIX", "Fix"),
                            ("DEFER", "Defer"),
                            ("WONTFIX", "Wontfix"),
                            ("OOSS", "Ooss"),
                            ("DELEGATED", "Delegated"),
                            ("WONTREPORT", "Wontreport"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("ps_module", models.CharField(max_length=100)),
                ("ps_component", models.CharField(max_length=255)),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("IMPORTANT", "Important"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cvss2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss2],
                    ),
                ),
                ("cvss2_score", models.FloatField(blank=True, null=True)),
                (
                    "cvss3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss3],
                    ),
                ),
                ("cvss3_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlawAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                ("workflow_name", models.CharField(blank=True, max_length=50)),
                (
                    "workflow_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("TRIAGE", "Triage"),
                            ("PRE_SECONDARY_ASSESSMENT", "Pre Secondary Assessment"),
                            ("SECONDARY_ASSESSMENT", "Secondary Assessment"),
                            ("DONE", "Done"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=60)),
                ("group_key", models.CharField(blank=True, max_length=60)),
                ("task_key", models.CharField(blank=True, max_length=60)),
                ("team_id", models.CharField(blank=True, max_length=8)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[osidb.validators.validate_cve_id],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VULNERABILITY", "Vulnerability"),
                            ("WEAKNESS", "Weakness"),
                        ],
                        default="VULNERABILITY",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("CLOSED", "Closed"),
                            ("MODIFIED", "Modified"),
                            ("NEW", "New"),
                            ("ON_DEV", "On Dev"),
                            ("ON_QA", "On Qa"),
                            ("POST", "Post"),
                            ("RELEASE_PENDING", "Release Pending"),
                            ("VERIFIED", "Verified"),
                        ],
                        default="NEW",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("DUPLICATE", "Duplicate"),
                            ("WONTFIX", "Wontfix"),
                            ("NOTABUG", "Notabug"),
                            ("ERRATA", "Errata"),
                            ("CANTFIX", "Cantfix"),
                            ("DEFERRED", "Deferred"),
                            ("CURRENTRELEASE", "Currentrelease"),
                            ("UPSTREAM", "Upstream"),
                            ("RAWHIDE", "Rawhide"),
                            ("INSUFFICIENT_DATA", "Insufficient Data"),
                            ("NEXTRELEASE", "Nextrelease"),
                            ("WORKSFORME", "Worksforme"),
                            ("EOL", "Eol"),
                        ],
                        default="",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("IMPORTANT", "Important"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(blank=True, max_length=100)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "requires_summary",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("statement", models.TextField(blank=True)),
                (
                    "cwe_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[osidb.validators.validate_cwe_id],
                    ),
                ),
                ("unembargo_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADOBE", "Adobe"),
                            ("APPLE", "Apple"),
                            ("ASF", "Asf"),
                            ("BIND", "Bind"),
                            ("BK", "Bk"),
                            ("BUGTRAQ", "Bugtraq"),
                            ("BUGZILLA", "Bugzilla"),
                            ("CERT", "Cert"),
                            ("CERTIFI", "Certfi"),
                            ("CORELABS", "Corelabs"),
                            ("CUSTOMER", "Customer"),
                            ("CVE", "Cve"),
                            ("DAILYDAVE", "Dailydave"),
                            ("DEBIAN", "Debian"),
                            ("DISTROS", "Distros"),
                            ("FEDORA", "Fedora"),
                            ("FETCHMAIL", "Fetchmail"),
                            ("FREEDESKTOP", "Freedesktop"),
                            ("FREERADIUS", "Freeradius"),
                            ("FRSIRT", "Frsirt"),
                            ("FULLDISCLOSURE", "Full Disclosure"),
                            ("GAIM", "Gaim"),
                            ("GENTOO", "Gentoo"),
                            ("GENTOOBZ", "Gentoobz"),
                            ("GIT", "Git"),
                            ("GNOME", "Gnome"),
                            ("GNUPG", "Gnupg"),
                            ("GOOGLE", "Google"),
                            ("HP", "Hp"),
                            ("HW_VENDOR", "Hw Vendor"),
                            ("IBM", "Ibm"),
                            ("IDEFENSE", "Idefense"),
                            ("INTERNET", "Internet"),
                            ("ISC", "Isc"),
                            ("ISEC", "Isec"),
                            ("IT", "It"),
                            ("JBOSS", "Jboss"),
                            ("JPCERT", "Jpcert"),
                            ("KERNELBUGZILLA", "Kernelbugzilla"),
                            ("KERNELSEC", "Kernelsec"),
                            ("LKML", "Lkml"),
                            ("LWN", "Lwn"),
                            ("MACROMEDIA", "Macromedia"),
                            ("MAGEIA", "Mageia"),
                            ("MAILINGLIST", "Mailinglist"),
                            ("MILW0RM", "Milw0Rm"),
                            ("MIT", "Mit"),
                            ("MITRE", "Mitre"),
                            ("MOZILLA", "Mozilla"),
                            ("MUTTDEV", "Muttdev"),
                            ("NETDEV", "Netdev"),
                            ("NISCC", "Niscc"),
                            ("", "Novalue"),
                            ("NVD", "Nvd"),
                            ("OCERT", "Ocert"),
                            ("OPENOFFICE", "Openoffice"),
                            ("OPENSSL", "Openssl"),
                            ("OPENSUSE", "Opensuse"),
                            ("ORACLE", "Oracle"),
                            ("OSS", "Oss"),
                            ("OSSSECURITY", "Oss Security"),
                            ("PHP", "Php"),
                            ("PIDGIN", "Pidgin"),
                            ("POSTGRESQL", "Postgresql"),
                            ("PRESS", "Press"),
                            ("REAL", "Real"),
                            ("REDHAT", "Redhat"),
                            ("RESEARCHER", "Researcher"),
                            ("RT", "Rt"),
                            ("SAMBA", "Samba"),
                            ("SECALERT", "Secalert"),
                            ("SECUNIA", "Secunia"),
                            ("SECURITYFOCUS", "Securityfocus"),
                            ("SKO", "Sko"),
                            ("SQUID", "Squid"),
                            ("SQUIRRELMAIL", "Squirrelmail"),
                            ("SUN", "Sun"),
                            ("SUNSOLVE", "Sunsolve"),
                            ("SUSE", "Suse"),
                            ("TWITTER", "Twitter"),
                            ("UBUNTU", "Ubuntu"),
                            ("UPSTREAM", "Upstream"),
                            ("VENDORSEC", "Vendor Sec"),
                            ("VULNWATCH", "Vulnwatch"),
                            ("WIRESHARK", "Wireshark"),
                            ("XCHAT", "Xchat"),
                            ("XEN", "Xen"),
                            ("XPDF", "Xpdf"),
                        ],
                        max_length=500,
                    ),
                ),
                (
                    "reported_dt",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        validators=[osidb.validators.no_future_date],
                    ),
                ),
                ("mitigation", models.TextField(blank=True)),
                (
                    "cvss2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss2],
                    ),
                ),
                ("cvss2_score", models.FloatField(blank=True, null=True)),
                (
                    "cvss3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss3],
                    ),
                ),
                ("cvss3_score", models.FloatField(blank=True, null=True)),
                (
                    "nvd_cvss2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss2],
                    ),
                ),
                (
                    "nvd_cvss3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[osidb.validators.validate_cvss3],
                    ),
                ),
                ("is_major_incident", models.BooleanField(default=False, null=True)),
                (
                    "major_incident_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("REQUESTED", "Requested"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                            ("CISA_APPROVED", "Cisa Approved"),
                            ("INVALID", "Invalid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nist_cvss_validation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Novalue"),
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlawMetaAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ERRATA", "Errata"),
                            ("REFERENCE", "Reference"),
                            ("ACKNOWLEDGMENT", "Acknowledgment"),
                            ("EXPLOIT", "Exploit"),
                            ("MAJOR_INCIDENT", "Major Incident"),
                            ("MAJOR_INCIDENT_LITE", "Major Incident Lite"),
                            ("REQUIRES_SUMMARY", "Requires Summary"),
                            ("NIST_CVSS_VALIDATION", "Nist Cvss Validation"),
                            ("NEED_INFO", "Need Info"),
                            ("CHECKLIST", "Checklist"),
                            ("NVD_CVSS", "Nvd Cvss"),
                        ],
                        max_length=500,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="affect",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "resolution", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."created_dt", NEW."cvss2", NEW."cvss2_score", NEW."cvss3", NEW."cvss3_score", NEW."flaw_id", NEW."impact", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."resolution", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="5bc78853f5a31780489ca343f9d8cab755e8a284",  # pragma: allowlist secret
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0d1b1",
                    table="osidb_affect",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="affect",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM NEW."acl_read" OR OLD."acl_write" IS DISTINCT FROM NEW."acl_write" OR OLD."affectedness" IS DISTINCT FROM NEW."affectedness" OR OLD."created_dt" IS DISTINCT FROM NEW."created_dt" OR OLD."cvss2" IS DISTINCT FROM NEW."cvss2" OR OLD."cvss2_score" IS DISTINCT FROM NEW."cvss2_score" OR OLD."cvss3" IS DISTINCT FROM NEW."cvss3" OR OLD."cvss3_score" IS DISTINCT FROM NEW."cvss3_score" OR OLD."flaw_id" IS DISTINCT FROM NEW."flaw_id" OR OLD."impact" IS DISTINCT FROM NEW."impact" OR OLD."ps_component" IS DISTINCT FROM NEW."ps_component" OR OLD."ps_module" IS DISTINCT FROM NEW."ps_module" OR OLD."resolution" IS DISTINCT FROM NEW."resolution" OR OLD."type" IS DISTINCT FROM NEW."type" OR OLD."updated_dt" IS DISTINCT FROM NEW."updated_dt" OR OLD."uuid" IS DISTINCT FROM NEW."uuid")',
                    func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "resolution", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."created_dt", NEW."cvss2", NEW."cvss2_score", NEW."cvss3", NEW."cvss3_score", NEW."flaw_id", NEW."impact", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."resolution", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="763d0713058a5459fea2f5411ac5d02f6183e775",  # pragma: allowlist secret
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_fdef6",
                    table="osidb_affect",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="affect",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "resolution", "type", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."affectedness", OLD."created_dt", OLD."cvss2", OLD."cvss2_score", OLD."cvss3", OLD."cvss3_score", OLD."flaw_id", OLD."impact", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_component", OLD."ps_module", OLD."resolution", OLD."type", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="f0163145a9daf093c59586a1b0cf481288a60033",  # pragma: allowlist secret
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_cc8c5",
                    table="osidb_affect",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "component", "created_dt", "cve_id", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "cwe_id", "description", "group_key", "impact", "is_major_incident", "major_incident_state", "mitigation", "nist_cvss_validation", "nvd_cvss2", "nvd_cvss3", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_summary", "resolution", "source", "state", "statement", "summary", "task_key", "team_id", "title", "type", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."component", NEW."created_dt", NEW."cve_id", NEW."cvss2", NEW."cvss2_score", NEW."cvss3", NEW."cvss3_score", NEW."cwe_id", NEW."description", NEW."group_key", NEW."impact", NEW."is_major_incident", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."nvd_cvss2", NEW."nvd_cvss3", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reported_dt", NEW."requires_summary", NEW."resolution", NEW."source", NEW."state", NEW."statement", NEW."summary", NEW."task_key", NEW."team_id", NEW."title", NEW."type", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;',
                    hash="1a544eaa9768df2d12cf8622503159ef9fe950bb",  # pragma: allowlist secret
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4e668",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM NEW."acl_read" OR OLD."acl_write" IS DISTINCT FROM NEW."acl_write" OR OLD."component" IS DISTINCT FROM NEW."component" OR OLD."created_dt" IS DISTINCT FROM NEW."created_dt" OR OLD."cve_id" IS DISTINCT FROM NEW."cve_id" OR OLD."cvss2" IS DISTINCT FROM NEW."cvss2" OR OLD."cvss2_score" IS DISTINCT FROM NEW."cvss2_score" OR OLD."cvss3" IS DISTINCT FROM NEW."cvss3" OR OLD."cvss3_score" IS DISTINCT FROM NEW."cvss3_score" OR OLD."cwe_id" IS DISTINCT FROM NEW."cwe_id" OR OLD."description" IS DISTINCT FROM NEW."description" OR OLD."group_key" IS DISTINCT FROM NEW."group_key" OR OLD."impact" IS DISTINCT FROM NEW."impact" OR OLD."is_major_incident" IS DISTINCT FROM NEW."is_major_incident" OR OLD."major_incident_state" IS DISTINCT FROM NEW."major_incident_state" OR OLD."mitigation" IS DISTINCT FROM NEW."mitigation" OR OLD."nist_cvss_validation" IS DISTINCT FROM NEW."nist_cvss_validation" OR OLD."nvd_cvss2" IS DISTINCT FROM NEW."nvd_cvss2" OR OLD."nvd_cvss3" IS DISTINCT FROM NEW."nvd_cvss3" OR OLD."owner" IS DISTINCT FROM NEW."owner" OR OLD."reported_dt" IS DISTINCT FROM NEW."reported_dt" OR OLD."requires_summary" IS DISTINCT FROM NEW."requires_summary" OR OLD."resolution" IS DISTINCT FROM NEW."resolution" OR OLD."source" IS DISTINCT FROM NEW."source" OR OLD."state" IS DISTINCT FROM NEW."state" OR OLD."statement" IS DISTINCT FROM NEW."statement" OR OLD."summary" IS DISTINCT FROM NEW."summary" OR OLD."task_key" IS DISTINCT FROM NEW."task_key" OR OLD."team_id" IS DISTINCT FROM NEW."team_id" OR OLD."title" IS DISTINCT FROM NEW."title" OR OLD."type" IS DISTINCT FROM NEW."type" OR OLD."unembargo_dt" IS DISTINCT FROM NEW."unembargo_dt" OR OLD."uuid" IS DISTINCT FROM NEW."uuid" OR OLD."workflow_name" IS DISTINCT FROM NEW."workflow_name" OR OLD."workflow_state" IS DISTINCT FROM NEW."workflow_state")',
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "component", "created_dt", "cve_id", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "cwe_id", "description", "group_key", "impact", "is_major_incident", "major_incident_state", "mitigation", "nist_cvss_validation", "nvd_cvss2", "nvd_cvss3", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_summary", "resolution", "source", "state", "statement", "summary", "task_key", "team_id", "title", "type", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."component", NEW."created_dt", NEW."cve_id", NEW."cvss2", NEW."cvss2_score", NEW."cvss3", NEW."cvss3_score", NEW."cwe_id", NEW."description", NEW."group_key", NEW."impact", NEW."is_major_incident", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."nvd_cvss2", NEW."nvd_cvss3", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_summary", NEW."resolution", NEW."source", NEW."state", NEW."statement", NEW."summary", NEW."task_key", NEW."team_id", NEW."title", NEW."type", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;',
                    hash="bb79614b5b59ab15ffc824c3322cbb9d47b0d6d5",  # pragma: allowlist secret
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_96595",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "component", "created_dt", "cve_id", "cvss2", "cvss2_score", "cvss3", "cvss3_score", "cwe_id", "description", "group_key", "impact", "is_major_incident", "major_incident_state", "mitigation", "nist_cvss_validation", "nvd_cvss2", "nvd_cvss3", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_summary", "resolution", "source", "state", "statement", "summary", "task_key", "team_id", "title", "type", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (OLD."acl_read", OLD."acl_write", OLD."component", OLD."created_dt", OLD."cve_id", OLD."cvss2", OLD."cvss2_score", OLD."cvss3", OLD."cvss3_score", OLD."cwe_id", OLD."description", OLD."group_key", OLD."impact", OLD."is_major_incident", OLD."major_incident_state", OLD."mitigation", OLD."nist_cvss_validation", OLD."nvd_cvss2", OLD."nvd_cvss3", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reported_dt", OLD."requires_summary", OLD."resolution", OLD."source", OLD."state", OLD."statement", OLD."summary", OLD."task_key", OLD."team_id", OLD."title", OLD."type", OLD."unembargo_dt", OLD."uuid", OLD."workflow_name", OLD."workflow_state"); RETURN NULL;',
                    hash="8d715e5262ff2976737284916f0e01b7ce139a01",  # pragma: allowlist secret
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f2e13",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawmeta",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawmetaaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="5d7f9f4f8efc35d3f33eb73e9fa1001448ee0107",  # pragma: allowlist secret
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_6642c",
                    table="osidb_flawmeta",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawmeta",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM NEW."acl_read" OR OLD."acl_write" IS DISTINCT FROM NEW."acl_write" OR OLD."created_dt" IS DISTINCT FROM NEW."created_dt" OR OLD."flaw_id" IS DISTINCT FROM NEW."flaw_id" OR OLD."type" IS DISTINCT FROM NEW."type" OR OLD."updated_dt" IS DISTINCT FROM NEW."updated_dt" OR OLD."uuid" IS DISTINCT FROM NEW."uuid")',
                    func='INSERT INTO "osidb_flawmetaaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="cb4fdc29f8e486bc1643d961e2dc3fe48287996e",  # pragma: allowlist secret
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_0e54f",
                    table="osidb_flawmeta",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawmeta",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawmetaaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."flaw_id", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."type", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="133c0472a06d1ce5d64805d70fbd2fcaf9f9e4d7",  # pragma: allowlist secret
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_e8d58",
                    table="osidb_flawmeta",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="flawmetaaudit",
            name="flaw",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="flawmetaaudit",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="flawmetaaudit",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="osidb.flawmeta",
            ),
        ),
        migrations.AddField(
            model_name="flawaudit",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="flawaudit",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="affectaudit",
            name="flaw",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="osidb.flaw",
            ),
        ),
        migrations.AddField(
            model_name="affectaudit",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="affectaudit",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="osidb.affect",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawmetaaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b056adeb1cb489ec77fdc6c4475e42ef3ba1ba84",  # pragma: allowlist secret
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_14fb8",
                    table="osidb_flawmetaaudit",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="195cbee13b88d274b393e907e94b01bdfa87a596",  # pragma: allowlist secret
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_b8a4b",
                    table="osidb_flawaudit",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="affectaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ca2d9223a1a2e17b9fdc59a87fdcaba3362e963a",  # pragma: allowlist secret
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_fa9ab",
                    table="osidb_affectaudit",
                    when="BEFORE",
                ),
            ),
        ),
        ######################
        # ROW LEVEL SECURITY #
        ######################
        migrations.RunSQL(
            reverse_sql=migrations.RunSQL.noop,
            sql="""
    --enable row based security for following tables
    ALTER TABLE osidb_flawaudit ENABLE ROW LEVEL SECURITY;
    ALTER TABLE osidb_flawaudit FORCE ROW LEVEL SECURITY;
    --following policies define fine grained read/write control on osidb_flawaudit entity
    --policy for entity insert (eg. create)
    DROP policy if exists acl_policy_flawaudit_create on osidb_flawaudit;
    create policy acl_policy_flawaudit_create
    on osidb_flawaudit
    for INSERT
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    -- Check that read / write ACLs of record to be inserted match ACL of current user
    --policy for entity select
    DROP policy if exists acl_policy_flawaudit_select on osidb_flawaudit;
    create policy acl_policy_flawaudit_select
    on osidb_flawaudit
    for select
    USING (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    -- Select only records with ACL that matches ACL of current user
    --policy for entity update
    DROP policy if exists acl_policy_flawaudit_update on osidb_flawaudit;
    create policy acl_policy_flawaudit_update
    on osidb_flawaudit
    for update
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[])
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    --policy for entity delete
    DROP policy if exists acl_policy_flawaudit_delete on osidb_flawaudit;
    create policy acl_policy_flawaudit_delete
    on osidb_flawaudit
    for delete
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    
    --enable row based security for affectaudit entity table
    ALTER TABLE osidb_affectaudit ENABLE ROW LEVEL SECURITY;
    ALTER TABLE osidb_affectaudit FORCE ROW LEVEL SECURITY;
    --following policies define fine grained read/write control on osidb_affectaudit entity
    --policy for entity insert (eg. create)
    DROP policy if exists acl_policy_affectaudit_create on osidb_affectaudit;
    create policy acl_policy_affectaudit_create
    on osidb_affectaudit
    for INSERT
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    --policy for entity select
    DROP policy if exists acl_policy_affectaudit_select on osidb_affectaudit;
    create policy acl_policy_affectaudit_select
    on osidb_affectaudit
    for select
    USING (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    --policy for entity update
    DROP policy if exists acl_policy_affectaudit_update on osidb_affectaudit;
    create policy acl_policy_affectaudit_update
    on osidb_affectaudit
    for update
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[])
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    --policy for entity delete
    DROP policy if exists acl_policy_affectaudit_delete on osidb_affectaudit;
    create policy acl_policy_affectaudit_delete
    on osidb_affectaudit
    for delete
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    
    --enable row based security for flawmetaaudit entity table
    ALTER TABLE osidb_flawmetaaudit ENABLE ROW LEVEL SECURITY;
    ALTER TABLE osidb_flawmetaaudit FORCE ROW LEVEL SECURITY;
    --following policies define fine grained read/write control on osidb_flawmetaaudit entity
    --policy for entity insert (eg. create)
    DROP policy if exists acl_policy_meta_create on osidb_flawmetaaudit;
    create policy acl_policy_meta_create
    on osidb_flawmetaaudit
    for INSERT
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    --policy for entity select
    DROP policy if exists acl_policy_meta_select on osidb_flawmetaaudit;
    create policy acl_policy_meta_select
    on osidb_flawmetaaudit
    for select
    USING (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    --policy for entity update
    DROP policy if exists acl_policy_meta_update on osidb_flawmetaaudit;
    create policy acl_policy_meta_update
    on osidb_flawmetaaudit
    for update
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[])
    WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
         AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
    --policy for entity delete
    DROP policy if exists acl_policy_meta_delete on osidb_flawmetaaudit;
    create policy acl_policy_meta_delete
    on osidb_flawmetaaudit
    for delete
    USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
    """,
        ),
    ]
