# Generated by Django 3.2.25 on 2024-04-22 12:17

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0123_flawsource_osv"),
    ]

    operations = [
        TrigramExtension(),
    ]
