# Generated by Django 3.2.25 on 2024-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0125_psmodule_private_tracker_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='workflow_name',
            field=models.CharField(blank=True, default='DEFAULT', max_length=50),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='workflow_state',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('TRIAGE', 'Triage'), ('PRE_SECONDARY_ASSESSMENT', 'Pre Secondary Assessment'), ('SECONDARY_ASSESSMENT', 'Secondary Assessment'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='NEW', max_length=24),
        ),
    ]
