# Generated by Django 3.2.24 on 2024-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0128_fix_meta_attr_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlawHistory',
        ),
    ]
