# Generated by Django 3.2.25 on 2024-05-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0129_delete_flawhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affect',
            name='type',
        ),
    ]
