# Generated by Django 3.2.25 on 2024-05-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0130_remove_affect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='type',
        ),
    ]
