# Generated by Django 3.2.25 on 2024-05-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0131_remove_flaw_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='state',
        ),
    ]
