# Generated by Django 3.2.25 on 2024-05-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0133_flawcomment_redesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='resolution',
        ),
    ]
