# Generated by Django 3.2.24 on 2024-05-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0134_remove_flaw_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='cvss2',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='cvss2_score',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='cvss3',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='cvss3_score',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='nvd_cvss2',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='nvd_cvss3',
        ),
    ]
