# Generated by Django 3.2.24 on 2024-05-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0135_remove_flaw_cvss_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affect',
            name='cvss2',
        ),
        migrations.RemoveField(
            model_name='affect',
            name='cvss2_score',
        ),
        migrations.RemoveField(
            model_name='affect',
            name='cvss3',
        ),
        migrations.RemoveField(
            model_name='affect',
            name='cvss3_score',
        ),
    ]
