# Generated by Django 3.2.24 on 2024-05-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0137_remove_flawcomment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlawMeta',
        ),
    ]
