# Generated by Django 3.2.24 on 2024-06-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0139_remove_flaw_is_major_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flawreference',
            name='meta_attr',
        ),
    ]
