# Generated by Django 3.2.24 on 2024-06-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0140_remove_flawreference_meta_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flawacknowledgment',
            name='meta_attr',
        ),
    ]
