# Generated by Django 3.2.25 on 2024-06-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0141_remove_flawacknowledgment_meta_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaw',
            old_name='description',
            new_name='comment_zero',
        ),
        migrations.RenameField(
            model_name='flaw',
            old_name='summary',
            new_name='cve_description',
        ),
        migrations.RenameField(
            model_name='flaw',
            old_name='requires_summary',
            new_name='requires_cve_description',
        ),
    ]
