# Generated by Django 3.2.25 on 2024-06-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0142_rename_flaw_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='component',
        ),
    ]
