# Generated by Django 3.2.25 on 2024-06-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0143_remove_flaw_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flawcomment',
            name='meta_attr',
        ),
    ]
