# Generated by Django 3.2.25 on 2024-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0148_alter_workflow_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BZTrackerDownloadManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100)),
                ('last_scheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_started_dt', models.DateTimeField(blank=True, null=True)),
                ('last_finished_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_failures', models.IntegerField(default=0)),
                ('permanently_failed', models.BooleanField(default=False)),
                ('last_rescheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_rescheduled_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_reschedules', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BZTrackerLinkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100)),
                ('last_scheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_started_dt', models.DateTimeField(blank=True, null=True)),
                ('last_finished_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_failures', models.IntegerField(default=0)),
                ('permanently_failed', models.BooleanField(default=False)),
                ('last_rescheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_rescheduled_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_reschedules', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlawDownloadManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100)),
                ('last_scheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_started_dt', models.DateTimeField(blank=True, null=True)),
                ('last_finished_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_failures', models.IntegerField(default=0)),
                ('permanently_failed', models.BooleanField(default=False)),
                ('last_rescheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_rescheduled_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_reschedules', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraTrackerLinkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100)),
                ('last_scheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_started_dt', models.DateTimeField(blank=True, null=True)),
                ('last_finished_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_failures', models.IntegerField(default=0)),
                ('permanently_failed', models.BooleanField(default=False)),
                ('last_rescheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_rescheduled_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_reschedules', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
