# Generated by Django 3.2.25 on 2024-06-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0151_syncmanagers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='bz_link_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osidb.bztrackerlinkmanager'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='download_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osidb.bztrackerdownloadmanager'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='jira_link_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osidb.jiratrackerlinkmanager'),
        ),
    ]
