# Generated by Django 3.2.25 on 2024-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0154_alert_unique_deduplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bztrackerdownloadmanager',
            name='sync_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bztrackerlinkmanager',
            name='sync_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='flawdownloadmanager',
            name='sync_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jiratrackerlinkmanager',
            name='sync_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
