# Generated by Django 3.2.25 on 2024-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0157_task_last_update_dt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together=set(),
        ),
    ]
