# Generated by Django 3.2.25 on 2024-07-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0157_task_last_update_dt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='unique Alert for name and object',
        ),
    ]
