# Generated by Django 3.2.25 on 2024-08-05 09:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0159_adds_tracker_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acl_read'], name='osidb_alert_acl_rea_df0b86_gin'),
        ),
    ]
