# Generated by Django 3.2.25 on 2024-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0160_gin_index_for_alert_RBS'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='bts_updated_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
