# Generated by Django 3.2.25 on 2024-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0161_alter_cvss_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectcvss',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV')], max_length=16),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='source',
            field=models.CharField(blank=True, choices=[('ADOBE', 'Adobe'), ('APPLE', 'Apple'), ('ASF', 'Asf'), ('BIND', 'Bind'), ('BK', 'Bk'), ('BUGTRAQ', 'Bugtraq'), ('BUGZILLA', 'Bugzilla'), ('CERT', 'Cert'), ('CERTIFI', 'Certfi'), ('CORELABS', 'Corelabs'), ('CUSTOMER', 'Customer'), ('CVE', 'Cve'), ('CVEORG', 'Cveorg'), ('DAILYDAVE', 'Dailydave'), ('DEBIAN', 'Debian'), ('DISTROS', 'Distros'), ('FEDORA', 'Fedora'), ('FETCHMAIL', 'Fetchmail'), ('FREEDESKTOP', 'Freedesktop'), ('FREERADIUS', 'Freeradius'), ('FRSIRT', 'Frsirt'), ('FULLDISCLOSURE', 'Full Disclosure'), ('GAIM', 'Gaim'), ('GENTOO', 'Gentoo'), ('GENTOOBZ', 'Gentoobz'), ('GIT', 'Git'), ('GNOME', 'Gnome'), ('GNUPG', 'Gnupg'), ('GOOGLE', 'Google'), ('HP', 'Hp'), ('HW_VENDOR', 'Hw Vendor'), ('IBM', 'Ibm'), ('IDEFENSE', 'Idefense'), ('INTERNET', 'Internet'), ('ISC', 'Isc'), ('ISEC', 'Isec'), ('IT', 'It'), ('JBOSS', 'Jboss'), ('JPCERT', 'Jpcert'), ('KERNELBUGZILLA', 'Kernelbugzilla'), ('KERNELSEC', 'Kernelsec'), ('LKML', 'Lkml'), ('LWN', 'Lwn'), ('MACROMEDIA', 'Macromedia'), ('MAGEIA', 'Mageia'), ('MAILINGLIST', 'Mailinglist'), ('MILW0RM', 'Milw0Rm'), ('MIT', 'Mit'), ('MITRE', 'Mitre'), ('MOZILLA', 'Mozilla'), ('MUTTDEV', 'Muttdev'), ('NETDEV', 'Netdev'), ('NISCC', 'Niscc'), ('', 'Novalue'), ('NVD', 'Nvd'), ('OCERT', 'Ocert'), ('OPENOFFICE', 'Openoffice'), ('OPENSSL', 'Openssl'), ('OPENSUSE', 'Opensuse'), ('ORACLE', 'Oracle'), ('OSS', 'Oss'), ('OSSSECURITY', 'Oss Security'), ('OSV', 'Osv'), ('PHP', 'Php'), ('PIDGIN', 'Pidgin'), ('POSTGRESQL', 'Postgresql'), ('PRESS', 'Press'), ('REAL', 'Real'), ('REDHAT', 'Redhat'), ('RESEARCHER', 'Researcher'), ('RT', 'Rt'), ('SAMBA', 'Samba'), ('SECALERT', 'Secalert'), ('SECUNIA', 'Secunia'), ('SECURITYFOCUS', 'Securityfocus'), ('SKO', 'Sko'), ('SQUID', 'Squid'), ('SQUIRRELMAIL', 'Squirrelmail'), ('SUN', 'Sun'), ('SUNSOLVE', 'Sunsolve'), ('SUSE', 'Suse'), ('TWITTER', 'Twitter'), ('UBUNTU', 'Ubuntu'), ('UPSTREAM', 'Upstream'), ('VENDORSEC', 'Vendor Sec'), ('VULNWATCH', 'Vulnwatch'), ('WIRESHARK', 'Wireshark'), ('XCHAT', 'Xchat'), ('XEN', 'Xen'), ('XPDF', 'Xpdf')], max_length=500),
        ),
        migrations.AlterField(
            model_name='flawaudit',
            name='source',
            field=models.CharField(blank=True, choices=[('ADOBE', 'Adobe'), ('APPLE', 'Apple'), ('ASF', 'Asf'), ('BIND', 'Bind'), ('BK', 'Bk'), ('BUGTRAQ', 'Bugtraq'), ('BUGZILLA', 'Bugzilla'), ('CERT', 'Cert'), ('CERTIFI', 'Certfi'), ('CORELABS', 'Corelabs'), ('CUSTOMER', 'Customer'), ('CVE', 'Cve'), ('CVEORG', 'Cveorg'), ('DAILYDAVE', 'Dailydave'), ('DEBIAN', 'Debian'), ('DISTROS', 'Distros'), ('FEDORA', 'Fedora'), ('FETCHMAIL', 'Fetchmail'), ('FREEDESKTOP', 'Freedesktop'), ('FREERADIUS', 'Freeradius'), ('FRSIRT', 'Frsirt'), ('FULLDISCLOSURE', 'Full Disclosure'), ('GAIM', 'Gaim'), ('GENTOO', 'Gentoo'), ('GENTOOBZ', 'Gentoobz'), ('GIT', 'Git'), ('GNOME', 'Gnome'), ('GNUPG', 'Gnupg'), ('GOOGLE', 'Google'), ('HP', 'Hp'), ('HW_VENDOR', 'Hw Vendor'), ('IBM', 'Ibm'), ('IDEFENSE', 'Idefense'), ('INTERNET', 'Internet'), ('ISC', 'Isc'), ('ISEC', 'Isec'), ('IT', 'It'), ('JBOSS', 'Jboss'), ('JPCERT', 'Jpcert'), ('KERNELBUGZILLA', 'Kernelbugzilla'), ('KERNELSEC', 'Kernelsec'), ('LKML', 'Lkml'), ('LWN', 'Lwn'), ('MACROMEDIA', 'Macromedia'), ('MAGEIA', 'Mageia'), ('MAILINGLIST', 'Mailinglist'), ('MILW0RM', 'Milw0Rm'), ('MIT', 'Mit'), ('MITRE', 'Mitre'), ('MOZILLA', 'Mozilla'), ('MUTTDEV', 'Muttdev'), ('NETDEV', 'Netdev'), ('NISCC', 'Niscc'), ('', 'Novalue'), ('NVD', 'Nvd'), ('OCERT', 'Ocert'), ('OPENOFFICE', 'Openoffice'), ('OPENSSL', 'Openssl'), ('OPENSUSE', 'Opensuse'), ('ORACLE', 'Oracle'), ('OSS', 'Oss'), ('OSSSECURITY', 'Oss Security'), ('OSV', 'Osv'), ('PHP', 'Php'), ('PIDGIN', 'Pidgin'), ('POSTGRESQL', 'Postgresql'), ('PRESS', 'Press'), ('REAL', 'Real'), ('REDHAT', 'Redhat'), ('RESEARCHER', 'Researcher'), ('RT', 'Rt'), ('SAMBA', 'Samba'), ('SECALERT', 'Secalert'), ('SECUNIA', 'Secunia'), ('SECURITYFOCUS', 'Securityfocus'), ('SKO', 'Sko'), ('SQUID', 'Squid'), ('SQUIRRELMAIL', 'Squirrelmail'), ('SUN', 'Sun'), ('SUNSOLVE', 'Sunsolve'), ('SUSE', 'Suse'), ('TWITTER', 'Twitter'), ('UBUNTU', 'Ubuntu'), ('UPSTREAM', 'Upstream'), ('VENDORSEC', 'Vendor Sec'), ('VULNWATCH', 'Vulnwatch'), ('WIRESHARK', 'Wireshark'), ('XCHAT', 'Xchat'), ('XEN', 'Xen'), ('XPDF', 'Xpdf')], max_length=500),
        ),
        migrations.AlterField(
            model_name='flawcvss',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV')], max_length=16),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.CharField(choices=[('CVEORG', 'Cveorg'), ('NVD', 'Nvd'), ('OSV', 'Osv')], max_length=100),
        ),
    ]
