# Generated by Django 3.2.25 on 2024-09-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0162_flawsource_cveorg"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraTrackerDownloadManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_id", models.CharField(max_length=100, unique=True)),
                ("last_scheduled_dt", models.DateTimeField(blank=True, null=True)),
                ("last_started_dt", models.DateTimeField(blank=True, null=True)),
                ("last_finished_dt", models.DateTimeField(blank=True, null=True)),
                ("last_failed_dt", models.DateTimeField(blank=True, null=True)),
                ("last_failed_reason", models.TextField(blank=True, null=True)),
                ("last_consecutive_failures", models.IntegerField(default=0)),
                ("permanently_failed", models.BooleanField(default=False)),
                ("last_rescheduled_dt", models.DateTimeField(blank=True, null=True)),
                ("last_rescheduled_reason", models.TextField(blank=True, null=True)),
                ("last_consecutive_reschedules", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="tracker",
            old_name="download_manager",
            new_name="bz_download_manager",
        ),
        migrations.AddField(
            model_name="tracker",
            name="jira_download_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="osidb.jiratrackerdownloadmanager",
            ),
        ),
    ]
