# Generated by Django 3.2.25 on 2024-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0164_jira_task_sync_manager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractPriority",
        ),
    ]
