# Generated by Django 3.2.25 on 2024-09-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0165_delete_contractpriority"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompliancePriority",
        ),
    ]
