# Generated by Django 3.2.25 on 2024-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0167_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='last_impact_increase_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
