# Generated by Django 3.2.25 on 2024-09-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0168_tracker_last_impact_increase_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="psupdatestream",
            name="moderate_to_ps_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderate_ps_update_streams",
                to="osidb.psmodule",
            ),
        ),
    ]
