# Generated by Django 4.2.16 on 2024-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0170_alter_flaw_major_incident_state_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flawcomment',
            name='unique_per_flaw_comment_nums',
        ),
        migrations.AlterField(
            model_name='flawcomment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
