# Generated by Django 4.2.16 on 2024-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0172_alert_updated_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawreference",
            name="type",
            field=models.CharField(
                choices=[
                    ("ARTICLE", "Article"),
                    ("EXTERNAL", "External"),
                    ("SOURCE", "Source"),
                    ("UPSTREAM", "Upstream"),
                ],
                default="EXTERNAL",
                max_length=50,
            ),
        ),
    ]
