# Generated by Django 4.2.16 on 2024-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0175_add_history_to_more_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbiPackage',
        ),
    ]
