# Generated by Django 4.2.16 on 2024-12-05 12:53

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0176_delete_ubipackage'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affectcvss',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affectcvss',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affectcvss',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawacknowledgment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawacknowledgment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawacknowledgment',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcvss',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcvss',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcvss',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawreference',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawreference',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawreference',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='alert',
            name='unique Alert for name and object',
        ),
        migrations.AddField(
            model_name='affect',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='affectaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='affectcvss',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='affectcvssaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flaw',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawacknowledgment',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawacknowledgmentaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawcomment',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawcommentaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawcvss',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawcvssaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawreference',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='flawreferenceaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='snippetaudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tracker',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trackeraudit',
            name='validation_version',
            field=models.IntegerField(blank=True, default=0),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "purl", "resolution", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."created_dt", NEW."flaw_id", NEW."impact", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."purl", NEW."resolution", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='aa4e1e58b009b156b12d5ec3d98e8cb419abd398', operation='INSERT', pgid='pgtrigger_insert_insert_0d1b1', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."affectedness" IS DISTINCT FROM (NEW."affectedness") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."ps_component" IS DISTINCT FROM (NEW."ps_component") OR OLD."ps_module" IS DISTINCT FROM (NEW."ps_module") OR OLD."purl" IS DISTINCT FROM (NEW."purl") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."validation_version" IS DISTINCT FROM (NEW."validation_version"))', func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "purl", "resolution", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."created_dt", NEW."flaw_id", NEW."impact", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."purl", NEW."resolution", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='4fd022555cf131801025f81a38e8d3b744496eee', operation='UPDATE', pgid='pgtrigger_update_update_fdef6', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "created_dt", "flaw_id", "impact", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "purl", "resolution", "updated_dt", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."affectedness", OLD."created_dt", OLD."flaw_id", OLD."impact", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_component", OLD."ps_module", OLD."purl", OLD."resolution", OLD."updated_dt", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='5939c0e80187530ce1100a7886303d713905e4d5', operation='DELETE', pgid='pgtrigger_delete_delete_cc8c5', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affectcvss',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectcvssaudit" ("acl_read", "acl_write", "affect_id", "comment", "created_dt", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affect_id", NEW."comment", NEW."created_dt", NEW."issuer", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."score", NEW."updated_dt", NEW."uuid", NEW."validation_version", NEW."vector", NEW."version"); RETURN NULL;', hash='88263fb2aa5035825f43a54dc3f19042f118dddf', operation='INSERT', pgid='pgtrigger_insert_insert_b9f93', table='osidb_affectcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affectcvss',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_affectcvssaudit" ("acl_read", "acl_write", "affect_id", "comment", "created_dt", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affect_id", NEW."comment", NEW."created_dt", NEW."issuer", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."score", NEW."updated_dt", NEW."uuid", NEW."validation_version", NEW."vector", NEW."version"); RETURN NULL;', hash='94196736bacf4f1acc90af3faec3a32d776ceb21', operation='UPDATE', pgid='pgtrigger_update_update_2bc7b', table='osidb_affectcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affectcvss',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectcvssaudit" ("acl_read", "acl_write", "affect_id", "comment", "created_dt", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (OLD."acl_read", OLD."acl_write", OLD."affect_id", OLD."comment", OLD."created_dt", OLD."issuer", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."score", OLD."updated_dt", OLD."uuid", OLD."validation_version", OLD."vector", OLD."version"); RETURN NULL;', hash='f0195a8566f6322b80f0dfb8d501ed156bbece97', operation='DELETE', pgid='pgtrigger_delete_delete_5e2a9', table='osidb_affectcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "bzsync_manager_id", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "download_manager_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_download_manager_id", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "validation_version", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."bzsync_manager_id", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."download_manager_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_download_manager_id", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."validation_version", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='5576d2bd2e73aabf58e227f58dda20a19daac0ff', operation='INSERT', pgid='pgtrigger_insert_insert_4e668', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."bzsync_manager_id" IS DISTINCT FROM (NEW."bzsync_manager_id") OR OLD."comment_zero" IS DISTINCT FROM (NEW."comment_zero") OR OLD."components" IS DISTINCT FROM (NEW."components") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_description" IS DISTINCT FROM (NEW."cve_description") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."cwe_id" IS DISTINCT FROM (NEW."cwe_id") OR OLD."download_manager_id" IS DISTINCT FROM (NEW."download_manager_id") OR OLD."group_key" IS DISTINCT FROM (NEW."group_key") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."major_incident_start_dt" IS DISTINCT FROM (NEW."major_incident_start_dt") OR OLD."major_incident_state" IS DISTINCT FROM (NEW."major_incident_state") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."nist_cvss_validation" IS DISTINCT FROM (NEW."nist_cvss_validation") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."reported_dt" IS DISTINCT FROM (NEW."reported_dt") OR OLD."requires_cve_description" IS DISTINCT FROM (NEW."requires_cve_description") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."statement" IS DISTINCT FROM (NEW."statement") OR OLD."task_download_manager_id" IS DISTINCT FROM (NEW."task_download_manager_id") OR OLD."task_key" IS DISTINCT FROM (NEW."task_key") OR OLD."task_updated_dt" IS DISTINCT FROM (NEW."task_updated_dt") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."unembargo_dt" IS DISTINCT FROM (NEW."unembargo_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."validation_version" IS DISTINCT FROM (NEW."validation_version") OR OLD."workflow_name" IS DISTINCT FROM (NEW."workflow_name") OR OLD."workflow_state" IS DISTINCT FROM (NEW."workflow_state"))', func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "bzsync_manager_id", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "download_manager_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_download_manager_id", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "validation_version", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."bzsync_manager_id", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."download_manager_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_download_manager_id", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."validation_version", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='71737a6b1ba461d7876cc9e7c616964ac8a802d3', operation='UPDATE', pgid='pgtrigger_update_update_96595', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "bzsync_manager_id", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "download_manager_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_download_manager_id", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "validation_version", "workflow_name", "workflow_state") VALUES (OLD."acl_read", OLD."acl_write", OLD."bzsync_manager_id", OLD."comment_zero", OLD."components", OLD."created_dt", OLD."cve_description", OLD."cve_id", OLD."cwe_id", OLD."download_manager_id", OLD."group_key", OLD."impact", OLD."major_incident_start_dt", OLD."major_incident_state", OLD."mitigation", OLD."nist_cvss_validation", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reported_dt", OLD."requires_cve_description", OLD."source", OLD."statement", OLD."task_download_manager_id", OLD."task_key", OLD."task_updated_dt", OLD."team_id", OLD."title", OLD."unembargo_dt", OLD."uuid", OLD."validation_version", OLD."workflow_name", OLD."workflow_state"); RETURN NULL;', hash='05a4511889241a1ae69ee336fad526d44716fba1', operation='DELETE', pgid='pgtrigger_delete_delete_f2e13', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawacknowledgment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawacknowledgmentaudit" ("acl_read", "acl_write", "affiliation", "created_dt", "flaw_id", "from_upstream", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affiliation", NEW."created_dt", NEW."flaw_id", NEW."from_upstream", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='e1007808493447a322d332ca661b0884ef9d5c87', operation='INSERT', pgid='pgtrigger_insert_insert_8d8ea', table='osidb_flawacknowledgment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawacknowledgment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawacknowledgmentaudit" ("acl_read", "acl_write", "affiliation", "created_dt", "flaw_id", "from_upstream", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."affiliation", NEW."created_dt", NEW."flaw_id", NEW."from_upstream", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='e28df8945257cd68c0e27b64aa7d9d4975049ceb', operation='UPDATE', pgid='pgtrigger_update_update_3f509', table='osidb_flawacknowledgment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawacknowledgment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawacknowledgmentaudit" ("acl_read", "acl_write", "affiliation", "created_dt", "flaw_id", "from_upstream", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."affiliation", OLD."created_dt", OLD."flaw_id", OLD."from_upstream", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."updated_dt", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='6f39788bf8694808b2d49896ff10087b4d568d57', operation='DELETE', pgid='pgtrigger_delete_delete_c737c', table='osidb_flawacknowledgment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."creator", NEW."external_system_id", NEW."flaw_id", NEW."is_private", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."synced_to_bz", NEW."text", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='b1027775ae8fcea884ddcac0710ca2eab5af057c', operation='INSERT', pgid='pgtrigger_insert_insert_5fac1', table='osidb_flawcomment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."creator", NEW."external_system_id", NEW."flaw_id", NEW."is_private", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."synced_to_bz", NEW."text", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='4d1c0c7829a3f151801b8145e38d7ef5055190d9', operation='UPDATE', pgid='pgtrigger_update_update_165cb', table='osidb_flawcomment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."creator", OLD."external_system_id", OLD."flaw_id", OLD."is_private", OLD."order", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."synced_to_bz", OLD."text", OLD."updated_dt", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='7612dd5ef658ebc77b6dcf8a689e3fc2b65aece0', operation='DELETE', pgid='pgtrigger_delete_delete_09c05', table='osidb_flawcomment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcvss',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcvssaudit" ("acl_read", "acl_write", "comment", "created_dt", "flaw_id", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (NEW."acl_read", NEW."acl_write", NEW."comment", NEW."created_dt", NEW."flaw_id", NEW."issuer", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."score", NEW."updated_dt", NEW."uuid", NEW."validation_version", NEW."vector", NEW."version"); RETURN NULL;', hash='a0ccd946be2ec998122ccf68f5e8f8a4ed25f56c', operation='INSERT', pgid='pgtrigger_insert_insert_c1c4a', table='osidb_flawcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcvss',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawcvssaudit" ("acl_read", "acl_write", "comment", "created_dt", "flaw_id", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (NEW."acl_read", NEW."acl_write", NEW."comment", NEW."created_dt", NEW."flaw_id", NEW."issuer", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."score", NEW."updated_dt", NEW."uuid", NEW."validation_version", NEW."vector", NEW."version"); RETURN NULL;', hash='b8b4e304f0ab7b4c9d0960b6fbe228088ea6d29b', operation='UPDATE', pgid='pgtrigger_update_update_6038c', table='osidb_flawcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcvss',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcvssaudit" ("acl_read", "acl_write", "comment", "created_dt", "flaw_id", "issuer", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "updated_dt", "uuid", "validation_version", "vector", "version") VALUES (OLD."acl_read", OLD."acl_write", OLD."comment", OLD."created_dt", OLD."flaw_id", OLD."issuer", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."score", OLD."updated_dt", OLD."uuid", OLD."validation_version", OLD."vector", OLD."version"); RETURN NULL;', hash='f90b9ab5e25a5af4b40849616529605d20fcc408', operation='DELETE', pgid='pgtrigger_delete_delete_608c3', table='osidb_flawcvss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawreference',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawreferenceaudit" ("acl_read", "acl_write", "created_dt", "description", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "url", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."description", NEW."flaw_id", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."type", NEW."updated_dt", NEW."url", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='c95b45e469cf2ab829724d00b8c7080243b87de2', operation='INSERT', pgid='pgtrigger_insert_insert_7df8e', table='osidb_flawreference', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawreference',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawreferenceaudit" ("acl_read", "acl_write", "created_dt", "description", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "url", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."description", NEW."flaw_id", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."type", NEW."updated_dt", NEW."url", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='57a6a5f7b817e7062a3777bb1392abdc2c00dcfd', operation='UPDATE', pgid='pgtrigger_update_update_5bc43', table='osidb_flawreference', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawreference',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawreferenceaudit" ("acl_read", "acl_write", "created_dt", "description", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "updated_dt", "url", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."description", OLD."flaw_id", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."type", OLD."updated_dt", OLD."url", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='60e068afa4efbd0f7bb50d42b4813d7ef6ec6b11', operation='DELETE', pgid='pgtrigger_delete_delete_8fa4c', table='osidb_flawreference', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='snippet',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_snippetaudit" ("acl_read", "acl_write", "content", "created_dt", "external_id", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."content", NEW."created_dt", NEW."external_id", NEW."flaw_id", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."source", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='760920e5b7f6de1189a71914b30871c5bb75abd4', operation='INSERT', pgid='pgtrigger_insert_insert_e56b3', table='osidb_snippet', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='snippet',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_snippetaudit" ("acl_read", "acl_write", "content", "created_dt", "external_id", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."content", NEW."created_dt", NEW."external_id", NEW."flaw_id", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."source", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='1f4cfe59838b3aa29f3e01a9fe102b87af558080', operation='UPDATE', pgid='pgtrigger_update_update_ff792', table='osidb_snippet', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='snippet',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_snippetaudit" ("acl_read", "acl_write", "content", "created_dt", "external_id", "flaw_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source", "updated_dt", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."content", OLD."created_dt", OLD."external_id", OLD."flaw_id", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."source", OLD."updated_dt", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='a6c84a84c8f55cf3b47c02344f1fd799795d4581', operation='DELETE', pgid='pgtrigger_delete_delete_56a33', table='osidb_snippet', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "bz_link_manager_id", "created_dt", "external_system_id", "jira_download_manager_id", "jira_link_manager_id", "last_impact_increase_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "status", "type", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."bz_download_manager_id", NEW."bz_link_manager_id", NEW."created_dt", NEW."external_system_id", NEW."jira_download_manager_id", NEW."jira_link_manager_id", NEW."last_impact_increase_dt", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='053cb4ff298fd13c61e6ca34cc385fc9232a0199', operation='INSERT', pgid='pgtrigger_insert_insert_781c0', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."bz_download_manager_id" IS DISTINCT FROM (NEW."bz_download_manager_id") OR OLD."bz_link_manager_id" IS DISTINCT FROM (NEW."bz_link_manager_id") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."external_system_id" IS DISTINCT FROM (NEW."external_system_id") OR OLD."jira_download_manager_id" IS DISTINCT FROM (NEW."jira_download_manager_id") OR OLD."jira_link_manager_id" IS DISTINCT FROM (NEW."jira_link_manager_id") OR OLD."last_impact_increase_dt" IS DISTINCT FROM (NEW."last_impact_increase_dt") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."validation_version" IS DISTINCT FROM (NEW."validation_version"))', func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "bz_link_manager_id", "created_dt", "external_system_id", "jira_download_manager_id", "jira_link_manager_id", "last_impact_increase_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "status", "type", "updated_dt", "uuid", "validation_version") VALUES (NEW."acl_read", NEW."acl_write", NEW."bz_download_manager_id", NEW."bz_link_manager_id", NEW."created_dt", NEW."external_system_id", NEW."jira_download_manager_id", NEW."jira_link_manager_id", NEW."last_impact_increase_dt", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid", NEW."validation_version"); RETURN NULL;', hash='049574597f585176a692f2a95bb08df3926f1b4a', operation='UPDATE', pgid='pgtrigger_update_update_4b400', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "bz_link_manager_id", "created_dt", "external_system_id", "jira_download_manager_id", "jira_link_manager_id", "last_impact_increase_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "status", "type", "updated_dt", "uuid", "validation_version") VALUES (OLD."acl_read", OLD."acl_write", OLD."bz_download_manager_id", OLD."bz_link_manager_id", OLD."created_dt", OLD."external_system_id", OLD."jira_download_manager_id", OLD."jira_link_manager_id", OLD."last_impact_increase_dt", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_update_stream", OLD."resolution", OLD."status", OLD."type", OLD."updated_dt", OLD."uuid", OLD."validation_version"); RETURN NULL;', hash='6d702be5659cbef959f54146c6b0a43c75de4d34', operation='DELETE', pgid='pgtrigger_delete_delete_d12e8', table='osidb_tracker', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('name', 'object_id', 'content_type', 'validation_version'), name='unique Alert for name and object'),
        ),
    ]
