# Generated by Django 4.2.17 on 2025-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0180_task_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flawcollaborator',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flawcollaborator',
            name='type',
            field=models.CharField(choices=[('context_based', 'Context Based'), ('product_family', 'Product Family')], default='context_based', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='flawcollaborator',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
