# Generated by Django 4.2.17 on 2025-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0182_affect_not_affected_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affect",
            name="not_affected_justification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Novalue"),
                    ("Component not Present", "Component Not Present"),
                    (
                        "Inline Mitigations already Exist",
                        "Inline Mitigations Already Exist",
                    ),
                    (
                        "Vulnerable Code cannot be Controlled by Adversary",
                        "Vuln Code Cannot Be Controlled",
                    ),
                    (
                        "Vulnerable Code not in Execute Path",
                        "Vuln Code Not In Execute Path",
                    ),
                    ("Vulnerable Code not Present", "Vuln Code Not Present"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="affectaudit",
            name="not_affected_justification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Novalue"),
                    ("Component not Present", "Component Not Present"),
                    (
                        "Inline Mitigations already Exist",
                        "Inline Mitigations Already Exist",
                    ),
                    (
                        "Vulnerable Code cannot be Controlled by Adversary",
                        "Vuln Code Cannot Be Controlled",
                    ),
                    (
                        "Vulnerable Code not in Execute Path",
                        "Vuln Code Not In Execute Path",
                    ),
                    ("Vulnerable Code not Present", "Vuln Code Not Present"),
                ],
                max_length=100,
            ),
        ),
    ]
