# Generated by Django 4.2.20 on 2025-03-27 14:49

from django.conf import settings
from django.db import migrations
from osidb.core import set_user_acls


def forwards_func(apps, schema_editor):
    """
    Set resolved_dt of affects in AFFECTED:DELEGATED state to null
    """
    set_user_acls(settings.ALL_GROUPS)

    Affect = apps.get_model("osidb", "Affect")
    Affect.objects.filter(
        affectedness="AFFECTED",
        resolution="DELEGATED",
        resolved_dt__isnull=False,
    ).update(resolved_dt=None)


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0188_map_user_id_to_user_email_or_name"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
