# Generated by Django 4.2.20 on 2025-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0189_affect_resolved_dt_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectcvss',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV'), ('CISA', 'CISA')], max_length=16),
        ),
        migrations.AlterField(
            model_name='affectcvssaudit',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV'), ('CISA', 'CISA')], max_length=16),
        ),
        migrations.AlterField(
            model_name='flawcvss',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV'), ('CISA', 'CISA')], max_length=16),
        ),
        migrations.AlterField(
            model_name='flawcvssaudit',
            name='issuer',
            field=models.CharField(choices=[('CVEORG', 'CVEORG'), ('RH', 'Red Hat'), ('NIST', 'NIST'), ('OSV', 'OSV'), ('CISA', 'CISA')], max_length=16),
        ),
    ]
