# Generated by Django 4.2.17 on 2025-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0189_affect_resolved_dt_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzsyncmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bztrackerdownloadmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bztrackerlinkmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flawdownloadmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jirataskdownloadmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiratasksyncmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiratasktransitionmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiratrackerdownloadmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiratrackerlinkmanager',
            name='planned_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
