# Generated by Django 4.2.22 on 2025-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0191_cisa_cvss_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flawcomment',
            name='creator',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='flawcommentaudit',
            name='creator',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
