# Generated by Django 4.2.22 on 2025-07-02 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0192_cisa_cveorg_cvss_score_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='special_handling',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Major Incident', 'Major Incident'), ('KEV (active exploit case)', 'Kev'), ('compliance-priority', 'Compliance Priority'), ('contract-priority', 'Contract Priority'), ('Minor Incident', 'Minor Incident'), ('security-select', 'Security Select'), ('support-exception', 'Support Exception')], max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='trackeraudit',
            name='special_handling',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Major Incident', 'Major Incident'), ('KEV (active exploit case)', 'Kev'), ('compliance-priority', 'Compliance Priority'), ('contract-priority', 'Contract Priority'), ('Minor Incident', 'Minor Incident'), ('security-select', 'Security Select'), ('support-exception', 'Support Exception')], max_length=100), blank=True, default=list, size=None),
        ),
    ]
