# Generated by Django 4.2.22 on 2025-07-10 10:48

from django.db import migrations

from osidb.core import set_user_acls
from config.settings_local import ALL_GROUPS


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0194_denormalize_cve_id_affect_tracker'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: set_user_acls(ALL_GROUPS),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunSQL("ALTER TABLE osidb_affect DISABLE TRIGGER USER;", migrations.RunSQL.noop),
        migrations.RunSQL(
            """
                UPDATE
                    osidb_affect AS a
                SET
                    cve_id = f.cve_id
                FROM
                    osidb_flaw AS f
                WHERE
                    a.flaw_id = f.uuid
                AND
                    f.cve_id IS NOT NULL
                AND
                    f.cve_id != '';
            """,
            "UPDATE osidb_affect SET cve_id = NULL;",
        ),
        migrations.RunSQL("ALTER TABLE osidb_affect ENABLE TRIGGER USER;", migrations.RunSQL.noop),
    ]
