# Generated by Django 4.2.22 on 2025-07-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0194_denormalize_cve_id_affect_tracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affect',
            unique_together={('flaw', 'ps_module', 'ps_component', 'purl')},
        ),
    ]
