# Generated by Django 4.2.22 on 2025-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0194_denormalize_cve_id_affect_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psproduct',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
