# Generated by Django 4.2.22 on 2025-08-07 17:21

from django.conf import settings
from django.db import migrations

from osidb.core import set_user_acls


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0195_alter_psproduct_team'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: set_user_acls(settings.ALL_GROUPS), reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            """
                UPDATE
                    osidb_affect AS a
                SET
                    cve_id = f.cve_id
                FROM
                    osidb_flaw AS f
                WHERE
                    a.flaw_id = f.uuid
                    AND
                    a.cve_id IS DISTINCT FROM f.cve_id
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
                UPDATE
                    osidb_tracker AS t
                SET
                    cve_id = a.cve_id
                FROM
                    osidb_affect AS a,
                    osidb_tracker_affects AS ta
                WHERE
                    t.uuid = ta.tracker_id
                    AND
                    a.uuid = ta.affect_id
                    AND
                    a.cve_id IS DISTINCT FROM t.cve_id
            """,
            migrations.RunSQL.noop,
        ),
    ]
