# Generated by Django 4.2.22 on 2025-07-10 10:49

from django.db import migrations

from osidb.core import set_user_acls
from config.settings_local import ALL_GROUPS


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0195_backfill_affect_cve_id'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: set_user_acls(ALL_GROUPS),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunSQL("ALTER TABLE osidb_tracker DISABLE TRIGGER USER;", migrations.RunSQL.noop),
        migrations.RunSQL(
            """
                UPDATE
                    osidb_tracker AS t
                SET
                    cve_id = a.cve_id
                FROM
                    osidb_affect AS a,
                    osidb_tracker_affects AS ta
                WHERE
                    t.uuid = ta.tracker_id
                    AND
                    a.uuid = ta.affect_id
                    AND
                    a.cve_id IS NOT NULL
                    AND
                    a.cve_id != '';
            """,
            "UPDATE osidb_tracker SET cve_id = NULL;",
        ),
        migrations.RunSQL("ALTER TABLE osidb_tracker ENABLE TRIGGER USER;", migrations.RunSQL.noop),
    ]
