# Generated by Django 4.2.22 on 2025-08-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0196_fix_desync_cve_id_denormalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affect',
            name='flaw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affects', to='osidb.flaw'),
        ),
        migrations.AlterField(
            model_name='affectaudit',
            name='flaw',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='osidb.flaw'),
        ),
    ]
