# Generated by Django 4.2.24 on 2025-09-24 13:20

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0204_denormalize_flaw_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvev5packageversions',
            name='packageversions_ptr',
        ),
        migrations.RemoveField(
            model_name='cvev5version',
            name='version_ptr',
        ),
        migrations.RemoveField(
            model_name='packageversions',
            name='flaw',
        ),
        migrations.RemoveField(
            model_name='packageversions',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='packageversions',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='version',
            name='polymorphic_ctype',
        ),
        migrations.AlterModelOptions(
            name='flawcomment',
            options={'ordering': ('external_system_id', 'uuid', 'created_dt')},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flawcomment',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='flawcomment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='flawcommentaudit',
            name='order',
        ),
        migrations.RemoveField(
            model_name='psproduct',
            name='team',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "last_validated_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."creator", NEW."external_system_id", NEW."flaw_id", NEW."is_private", NEW."last_validated_dt", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."synced_to_bz", NEW."text", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='cb00b50eb47ed86976427fe07ab26cd740651e3a', operation='INSERT', pgid='pgtrigger_insert_insert_5fac1', table='osidb_flawcomment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "last_validated_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."creator", NEW."external_system_id", NEW."flaw_id", NEW."is_private", NEW."last_validated_dt", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."synced_to_bz", NEW."text", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='55bcd41d4cb141b83aac90447a7869aa1e4993e3', operation='UPDATE', pgid='pgtrigger_update_update_165cb', table='osidb_flawcomment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawcomment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawcommentaudit" ("acl_read", "acl_write", "created_dt", "creator", "external_system_id", "flaw_id", "is_private", "last_validated_dt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "synced_to_bz", "text", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."creator", OLD."external_system_id", OLD."flaw_id", OLD."is_private", OLD."last_validated_dt", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."synced_to_bz", OLD."text", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='4426adc70c439a9075b9f504f1c3c08fd7ff0155', operation='DELETE', pgid='pgtrigger_delete_delete_09c05', table='osidb_flawcomment', when='AFTER')),
        ),
        migrations.DeleteModel(
            name='CVEv5PackageVersions',
        ),
        migrations.DeleteModel(
            name='CVEv5Version',
        ),
        migrations.DeleteModel(
            name='PackageVersions',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
