# Generated by Django 4.2.24 on 2025-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0205_remove_deprecated_fields_and_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flawcomment',
            options={'ordering': ('external_system_id', 'created_dt')},
        ),
        migrations.AddConstraint(
            model_name='flawcomment',
            constraint=models.UniqueConstraint(fields=('flaw', 'external_system_id', 'created_dt'), name='unique_per_flaw_comment'),
        ),
    ]
