# Generated by Django 5.2 on 2026-01-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0212_fix_materialized_view_grouped_trackers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='team_id',
        ),
    ]
