# Generated by Django 5.2 on 2026-01-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0213_remove_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='group_key',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='group_key',
        ),
    ]
