# Generated by Django 4.2.26 on 2025-11-24 16:56

from django.db import migrations, models
from osidb.helpers import bypass_rls


BATCH_SIZE = 1000


@bypass_rls
def forwards_func(apps, schema_editor):
    """Order qualifiers in existing PURLs for all affects."""
    from packageurl import PackageURL

    Affect = apps.get_model('osidb', 'Affect')

    affects_to_update = []
    for affect in Affect.objects.all().iterator(chunk_size=BATCH_SIZE):
        if not affect.purl:
            continue

        try:
            ordered_purl = PackageURL.from_string(affect.purl).to_string()
            if affect.purl != ordered_purl:
                affect.purl = ordered_purl
                affects_to_update.append(affect)
        except ValueError:
            continue

        if len(affects_to_update) >= BATCH_SIZE:
            Affect.objects.bulk_update(affects_to_update, ['purl'])
            affects_to_update = []

    if affects_to_update:
        Affect.objects.bulk_update(affects_to_update, ['purl'])


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0214_alter_flawcollaborator_type_alter_flawlabel_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affect',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='affect',
            constraint=models.UniqueConstraint(condition=models.Q(('purl', '')), fields=('flaw', 'ps_update_stream', 'ps_component'), name='affect_unique_flaw_stream_component_when_purl_empty'),
        ),
        migrations.AddConstraint(
            model_name='affect',
            constraint=models.UniqueConstraint(condition=models.Q(('purl__gt', '')), fields=('flaw', 'ps_update_stream', 'purl'), name='affect_unique_flaw_stream_purl'),
        ),
        migrations.RunPython(forwards_func),
    ]
