# Generated by Django 4.2.26 on 2025-12-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0214_make_purl_into_purlfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affect',
            unique_together={('flaw', 'ps_update_stream', 'ps_component')},
        ),
    ]
