# Generated by Django 4.2.26 on 2025-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0214_make_purl_into_purl_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flawcollaborator',
            name='type',
            field=models.CharField(choices=[('alias', 'Alias'), ('context_based', 'Context Based'), ('product_family', 'Product Family')], default='context_based', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='flawlabel',
            name='type',
            field=models.CharField(choices=[('alias', 'Alias'), ('context_based', 'Context Based'), ('product_family', 'Product Family')], editable=False, max_length=20),
        ),
    ]
