# Generated by Django 4.2.24 on 2025-10-23 17:02

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0215_alter_flawcollaborator_type_alter_flawlabel_type'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='bz_link_manager',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='jira_link_manager',
        ),
        migrations.RemoveField(
            model_name='trackeraudit',
            name='bz_link_manager',
        ),
        migrations.RemoveField(
            model_name='trackeraudit',
            name='jira_link_manager',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "created_dt", "cve_id", "external_system_id", "jira_download_manager_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."bz_download_manager_id", NEW."created_dt", NEW."cve_id", NEW."external_system_id", NEW."jira_download_manager_id", NEW."last_impact_increase_dt", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."resolved_dt", NEW."special_handling", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='bb9b55749e6609b1ce3ebf7ef6613e7572fd41f4', operation='INSERT', pgid='pgtrigger_insert_insert_781c0', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."bz_download_manager_id" IS DISTINCT FROM (NEW."bz_download_manager_id") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."external_system_id" IS DISTINCT FROM (NEW."external_system_id") OR OLD."jira_download_manager_id" IS DISTINCT FROM (NEW."jira_download_manager_id") OR OLD."last_impact_increase_dt" IS DISTINCT FROM (NEW."last_impact_increase_dt") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."not_affected_justification" IS DISTINCT FROM (NEW."not_affected_justification") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."special_handling" IS DISTINCT FROM (NEW."special_handling") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "created_dt", "cve_id", "external_system_id", "jira_download_manager_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."bz_download_manager_id", NEW."created_dt", NEW."cve_id", NEW."external_system_id", NEW."jira_download_manager_id", NEW."last_impact_increase_dt", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."resolved_dt", NEW."special_handling", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='7f80665753dc609132d87fd12e67d1bade03aff0', operation='UPDATE', pgid='pgtrigger_update_update_4b400', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "bz_download_manager_id", "created_dt", "cve_id", "external_system_id", "jira_download_manager_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."bz_download_manager_id", OLD."created_dt", OLD."cve_id", OLD."external_system_id", OLD."jira_download_manager_id", OLD."last_impact_increase_dt", OLD."last_validated_dt", OLD."not_affected_justification", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_update_stream", OLD."resolution", OLD."resolved_dt", OLD."special_handling", OLD."status", OLD."type", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='a4881e0a735ef3b930c79f691b4fd3eb91508b8e', operation='DELETE', pgid='pgtrigger_delete_delete_d12e8', table='osidb_tracker', when='AFTER')),
        ),
        migrations.DeleteModel(
            name='BZTrackerLinkManager',
        ),
        migrations.DeleteModel(
            name='JiraTrackerLinkManager',
        ),
    ]
