# Generated by Django 5.2.10 on 2026-01-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0217_remove_cwe_auto_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='bzsync_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.bzsyncmanager'),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='task_download_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.jirataskdownloadmanager'),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='task_sync_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.jiratasksyncmanager'),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='task_transition_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.jiratasktransitionmanager'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='bz_download_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.bztrackerdownloadmanager'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='jira_download_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osidb.jiratrackerdownloadmanager'),
        ),
    ]
