# Generated by Django 4.2.26 on 2025-12-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0217_make_purl_into_purlfield'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affect',
            name='affect_unique_flaw_stream_component_when_purl_empty',
        ),
        migrations.RemoveConstraint(
            model_name='affect',
            name='affect_unique_flaw_stream_purl',
        ),
        migrations.AlterUniqueTogether(
            name='affect',
            unique_together={('flaw', 'ps_update_stream', 'ps_component')},
        ),
    ]
