# Generated by Django 5.2 on 2026-01-21 09:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0218_alter_flaw_bzsync_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('sync_id', models.CharField()),
                ('last_scheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_started_dt', models.DateTimeField(blank=True, null=True)),
                ('last_finished_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_dt', models.DateTimeField(blank=True, null=True)),
                ('last_failed_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_failures', models.IntegerField(default=0)),
                ('permanently_failed', models.BooleanField(default=False)),
                ('last_rescheduled_dt', models.DateTimeField(blank=True, null=True)),
                ('last_rescheduled_reason', models.TextField(blank=True, null=True)),
                ('last_consecutive_reschedules', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='bzsync_manager',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='bzsync_manager',
        ),
        migrations.RemoveField(
            model_name='trackeraudit',
            name='bz_download_manager',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='bz_download_manager',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='task_download_manager',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='task_download_manager',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='task_sync_manager',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='task_sync_manager',
        ),
        migrations.RemoveField(
            model_name='flawaudit',
            name='task_transition_manager',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='task_transition_manager',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='jira_download_manager',
        ),
        migrations.RemoveField(
            model_name='trackeraudit',
            name='jira_download_manager',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='delete_delete',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "last_validated_dt", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."last_validated_dt", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='8a508e412fc5780eb9d487531b43d4a76184ee94', operation='INSERT', pgid='pgtrigger_insert_insert_4e668', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."aegis_meta" IS DISTINCT FROM (NEW."aegis_meta") OR OLD."comment_zero" IS DISTINCT FROM (NEW."comment_zero") OR OLD."components" IS DISTINCT FROM (NEW."components") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_description" IS DISTINCT FROM (NEW."cve_description") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."cwe_id" IS DISTINCT FROM (NEW."cwe_id") OR OLD."group_key" IS DISTINCT FROM (NEW."group_key") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."major_incident_start_dt" IS DISTINCT FROM (NEW."major_incident_start_dt") OR OLD."major_incident_state" IS DISTINCT FROM (NEW."major_incident_state") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."nist_cvss_validation" IS DISTINCT FROM (NEW."nist_cvss_validation") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."reported_dt" IS DISTINCT FROM (NEW."reported_dt") OR OLD."requires_cve_description" IS DISTINCT FROM (NEW."requires_cve_description") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."statement" IS DISTINCT FROM (NEW."statement") OR OLD."task_key" IS DISTINCT FROM (NEW."task_key") OR OLD."task_updated_dt" IS DISTINCT FROM (NEW."task_updated_dt") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."unembargo_dt" IS DISTINCT FROM (NEW."unembargo_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."workflow_name" IS DISTINCT FROM (NEW."workflow_name") OR OLD."workflow_state" IS DISTINCT FROM (NEW."workflow_state"))', func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "last_validated_dt", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."last_validated_dt", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='3ac6f04dd6f482ffd9f7f9ee260f52da6d92578d', operation='UPDATE', pgid='pgtrigger_update_update_96595', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "last_validated_dt", "major_incident_start_dt", "major_incident_state", "mitigation", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (OLD."acl_read", OLD."acl_write", OLD."aegis_meta", OLD."comment_zero", OLD."components", OLD."created_dt", OLD."cve_description", OLD."cve_id", OLD."cwe_id", OLD."group_key", OLD."impact", OLD."last_validated_dt", OLD."major_incident_start_dt", OLD."major_incident_state", OLD."mitigation", OLD."nist_cvss_validation", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reported_dt", OLD."requires_cve_description", OLD."source", OLD."statement", OLD."task_key", OLD."task_updated_dt", OLD."team_id", OLD."title", OLD."unembargo_dt", OLD."uuid", OLD."workflow_name", OLD."workflow_state"); RETURN NULL;', hash='2bfaff05409c5c8a304ef61383858a918f5e9211', operation='DELETE', pgid='pgtrigger_delete_delete_f2e13', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "created_dt", "cve_id", "external_system_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."cve_id", NEW."external_system_id", NEW."last_impact_increase_dt", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."resolved_dt", NEW."special_handling", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='92a7ed7e5ee0eac0451f84c9e1d63291fc7c742e', operation='INSERT', pgid='pgtrigger_insert_insert_781c0', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."external_system_id" IS DISTINCT FROM (NEW."external_system_id") OR OLD."last_impact_increase_dt" IS DISTINCT FROM (NEW."last_impact_increase_dt") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."not_affected_justification" IS DISTINCT FROM (NEW."not_affected_justification") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."special_handling" IS DISTINCT FROM (NEW."special_handling") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "created_dt", "cve_id", "external_system_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."cve_id", NEW."external_system_id", NEW."last_impact_increase_dt", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."resolved_dt", NEW."special_handling", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='395e8d401fdafe90c7225e5741e80a761cf7aa89', operation='UPDATE', pgid='pgtrigger_update_update_4b400', table='osidb_tracker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "created_dt", "cve_id", "external_system_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."cve_id", OLD."external_system_id", OLD."last_impact_increase_dt", OLD."last_validated_dt", OLD."not_affected_justification", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_update_stream", OLD."resolution", OLD."resolved_dt", OLD."special_handling", OLD."status", OLD."type", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='f3e6f0c78c3f3c2f8781e5d1fe4c8814e2611db1', operation='DELETE', pgid='pgtrigger_delete_delete_d12e8', table='osidb_tracker', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='syncmanager',
            constraint=models.UniqueConstraint(fields=('name', 'sync_id'), name='unique_name_sync_id_sync_manager'),
        ),
        migrations.DeleteModel(
            name='BZSyncManager',
        ),
        migrations.DeleteModel(
            name='BZTrackerDownloadManager',
        ),
        migrations.DeleteModel(
            name='JiraTaskDownloadManager',
        ),
        migrations.DeleteModel(
            name='JiraTaskSyncManager',
        ),
        migrations.DeleteModel(
            name='JiraTaskTransitionManager',
        ),
        migrations.DeleteModel(
            name='JiraTrackerDownloadManager',
        ),
        migrations.CreateModel(
            name='BZSyncManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
        migrations.CreateModel(
            name='BZTrackerDownloadManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
        migrations.CreateModel(
            name='JiraTaskDownloadManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
        migrations.CreateModel(
            name='JiraTaskSyncManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
        migrations.CreateModel(
            name='JiraTaskTransitionManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
        migrations.CreateModel(
            name='JiraTrackerDownloadManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osidb.syncmanager',),
        ),
    ]
