# Generated by Django 4.2.27 on 2025-12-23 14:43

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0218_revert_purl_component_conditional_uniqueness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippetaudit",
            name="flaw",
        ),
        migrations.RemoveField(
            model_name="snippetaudit",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="snippetaudit",
            name="pgh_obj",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="snippet",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="snippet",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="snippet",
            name="delete_delete",
        ),
        migrations.DeleteModel(
            name="SnippetAudit",
        ),
    ]
