# Generated by Django 5.2 on 2026-01-21 11:52

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0219_syncmanager_remove_flaw_bzsync_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetaudit',
            name='flaw',
        ),
        migrations.RemoveField(
            model_name='snippetaudit',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='snippetaudit',
            name='pgh_obj',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='snippet',
            name='delete_delete',
        ),
        migrations.DeleteModel(
            name='SnippetAudit',
        ),
    ]
