# Generated by Django 5.2.8 on 2026-01-20 10:18
from django.db import migrations


CREATE_GIN_INDEXES = """
CREATE INDEX IF NOT EXISTS affect_v1_all_tracker_ids_gin_idx
ON affect_v1
USING GIN (all_tracker_ids);
"""

REVERT_GIN_INDEXES = """
DROP INDEX IF EXISTS affect_v1_all_tracker_ids_gin_idx;
"""

CREATE_PERFORMANCE_INDEXES = """
-- Supporting/performance indexes on the source table used to build/refresh affect_v1
-- (kept here as a safety net in case environments missed 0211 for any reason).
-- index for the ROW_NUMBER calculation in affect_v1 definition
CREATE INDEX IF NOT EXISTS osidb_affect_ranking_idx
ON osidb_affect (
    flaw_id,
    ps_module,
    ps_component,
    (CASE WHEN affectedness = 'NOTAFFECTED' THEN 2 ELSE 1 END),
    (CASE impact
        WHEN 'CRITICAL'  THEN 4
        WHEN 'IMPORTANT' THEN 3
        WHEN 'MODERATE'  THEN 2
        WHEN 'LOW'       THEN 1
        ELSE 0
    END) DESC,
    created_dt DESC,
    uuid DESC
);

-- index for the grouped_trackers CTE in affect_v1 definition
CREATE INDEX IF NOT EXISTS osidb_affect_tracker_grouping_idx
ON osidb_affect (flaw_id, ps_module, tracker_id)
WHERE tracker_id IS NOT NULL;

-- index for filtering by flaw
CREATE INDEX IF NOT EXISTS affect_v1_flaw_id_idx
ON affect_v1 (flaw_id);

-- index for default ordering (created_dt, uuid)
CREATE INDEX IF NOT EXISTS affect_v1_sorting_idx
ON affect_v1 (created_dt, uuid);
"""

REVERT_PERFORMANCE_INDEXES = """
DROP INDEX IF EXISTS osidb_affect_ranking_idx;
DROP INDEX IF EXISTS osidb_affect_tracker_grouping_idx;
DROP INDEX IF EXISTS affect_v1_flaw_id_idx;
DROP INDEX IF EXISTS affect_v1_sorting_idx;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('osidb', '0220_remove_snippetaudit_flaw_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_GIN_INDEXES,
            reverse_sql=REVERT_GIN_INDEXES,
        ),
        migrations.RunSQL(
            CREATE_PERFORMANCE_INDEXES,
            reverse_sql=REVERT_PERFORMANCE_INDEXES,
        )
    ]

