# Generated by Django 5.2 on 2026-01-22 19:20

from django.db import migrations



def remove_cvss_from_notaffected_affects(apps, schema_editor):
    """
    Remove CVSS scores from affects marked as NOTAFFECTED.
    """

    Affect = apps.get_model("osidb", "Affect")
    AffectCVSS = apps.get_model("osidb", "AffectCVSS")

    affect_uuids = Affect.objects.filter(
        affectedness="NOTAFFECTED",
        cvss_scores__isnull=False
    ).values_list("uuid", flat=True).distinct()

    AffectCVSS.objects.filter(affect_id__in=affect_uuids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0223_fix_update_stream'),
    ]

    operations = [
        migrations.RunPython(remove_cvss_from_notaffected_affects, reverse_code=migrations.RunPython.noop),
    ]
