# Generated by Django 5.2.10 on 2026-02-03 18:06

"""
Migration for filling in the mitre_cve_description field
Adapted from 0191_cisa_cvss_data_migration
"""

from celery.utils.log import logging
from django.db import migrations, transaction
from pghistory.runtime import json

from collectors.cveorg.collectors import CVEorgCollector, CVEorgCollectorException
from osidb.helpers import bypass_rls


_logger = logging.getLogger(__name__)


@bypass_rls
def fill(apps, schema_editor):
    Flaw = apps.get_model("osidb", "Flaw")

    if Flaw.objects.count() == 0:
        return

    collector = CVEorgCollector()
    collector.clone_repo()

    for cve_id in (
        Flaw.objects.exclude(cve_id__isnull=True)
        .exclude(cve_id__exact="")
        .values_list("cve_id", flat=True)
        .iterator()
    ):
        try:
            fp = collector.get_cve_file_path(cve_id)
        except CVEorgCollectorException as exc:
            _logger.warning(f"Could not get filepath for {cve_id}", exc_info=exc)
            continue

        with open(fp) as f:
            raw_content = json.load(f)

        try:
            content = collector.extract_content(raw_content)
        except Exception as exc:
            _logger.warning(f"Failed to extract content for {cve_id}", exc_info=exc)
            continue

        try:
            with transaction.atomic():
                collector.update_mitre_cve_description(
                    cve_id, 
                    content["mitre_cve_description"],
                    enable_timestamp=False,
                )
        except Exception as exc:
            _logger.warning(f"Failed to update mitre_cve_description for {cve_id}", exc_info=exc)

@bypass_rls
def unfill(apps, schema_editor):
    Flaw = apps.get_model("osidb", "Flaw")
    Flaw.objects.exclude(mitre_cve_description="").update(mitre_cve_description="")


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0225_add_mitre_cve_description'),
    ]

    operations = [
        migrations.RunPython(fill, reverse_code=unfill)
    ]
