# Generated by Django 4.2.25 on 2026-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0226_fill_mitre_cve_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affect',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='affect',
            constraint=models.UniqueConstraint(fields=('flaw', 'ps_update_stream', 'ps_component'), name='uniq_affect_flaw_stream_ps_component'),
        ),
        migrations.AddConstraint(
            model_name='affect',
            constraint=models.UniqueConstraint(condition=models.Q(('purl__isnull', False), models.Q(('purl', ''), _negated=True)), fields=('flaw', 'ps_update_stream', 'purl'), name='uniq_affect_flaw_stream_purl_present'),
        ),
    ]
