# Generated by Django 5.2.10 on 2026-03-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0227_jirausermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='group_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='team_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='flawaudit',
            name='group_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='flawaudit',
            name='team_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
