# Generated by Django 5.2.10 on 2026-02-26 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0227_remove_flaw_insert_insert_remove_flaw_update_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraUserMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('associate_kerberos_id', models.CharField(db_index=True, max_length=255)),
                ('associate_uuid', models.UUIDField(unique=True)),
                ('atlassian_cloud_id', models.CharField(max_length=255)),
                ('is_employed', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['associate_kerberos_id'],
            },
        ),
    ]
