# Generated by Django 5.2 on 2026-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0228_alter_flaw_group_key_alter_flaw_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='requires_cve_description',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flawaudit',
            name='requires_cve_description',
            field=models.CharField(blank=True, choices=[('', 'Novalue'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
    ]
