# Generated by Django 5.2.12 on 2026-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0230_add_audit_composite_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flaw',
            index=models.Index(fields=['uuid', 'updated_dt'], name='osidb_flaw_uuid_82d71f_idx'),
        ),
        migrations.AddIndex(
            model_name='flaw',
            index=models.Index(condition=models.Q(('cve_id__isnull', False)), fields=['cve_id', 'updated_dt'], name='osidb_flaw_cve_index'),
        ),
    ]
