# Generated by Django 5.2.12 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0231_flaw_osidb_flaw_uuid_0d503b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="atlassian_cloud_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
