# Generated by Django 5.2.12 on 2026-04-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0232_profile_atlassian_cloud_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JiraUserMapping",
        ),
    ]
