# Generated by Django 5.2.13 on 2026-05-14 18:57

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0234_alter_flawcollaborator_type_alter_flawlabel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamData',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('last_validated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upstream_purls', models.JSONField(blank=True, default=list)),
                ('upstream_descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None)),
                ('upstream_severities', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=10)),
                ('flaw', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_data', to='osidb.flaw')),
            ],
            options={
                'indexes': [models.Index(fields=['-updated_dt'], name='osidb_upstr_updated_c87b01_idx'), django.contrib.postgres.indexes.GinIndex(fields=['acl_read'], name='osidb_upstr_acl_rea_bb8e71_gin')],
                'constraints': [models.UniqueConstraint(fields=('flaw', 'source'), name='unique_upstream_data_of_a_flaw')],
            },
        ),
    ]
