# Generated by Django 4.2.25 on 2026-05-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0234_alter_flawcollaborator_type_alter_flawlabel_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACLHistorySyncManager",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("osidb.syncmanager",),
        ),
    ]
