# Generated by Django 5.2.13 on 2026-05-26 15:48

from django.db import migrations



def add_automation_labels(apps, schema_editor):

    FlawLabel = apps.get_model("osidb", "FlawLabel")
    FlawLabel.objects.get_or_create(
        name="manual-triage",
        defaults={"type": "manual_triage"},
    )
    FlawLabel.objects.get_or_create(
        name="auto-affects",
        defaults={"type": "auto_affects"}
    )
    FlawLabel.objects.get_or_create(
        name="auto-rejected",
        defaults={"type": "auto_rejected"}
        )
    FlawLabel.objects.get_or_create(
        name="potential-rejection",
        defaults={"type": "potential_rejection"}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0236_upstreamdata"),
    ]

    operations = [
        migrations.RunPython(
            add_automation_labels,
            migrations.RunPython.noop,
        )
    ]