# Generated by Django 5.2.12 on 2026-06-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0236_upstreamdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraTaskDownloadManager',
        ),
    ]
