# Generated by Django 5.2.13 on 2026-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0237_add_automation_label_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawcollaborator",
            name="type",
            field=models.CharField(
                choices=[
                    ("alias", "Alias"),
                    ("context_based", "Context Based"),
                    ("product_family", "Product Family"),
                    ("bu", "Bu"),
                    ("manual_triage", "Manual Triage"),
                    ("auto_affects", "Auto Affects"),
                    ("auto_rejected", "Auto Rejected"),
                    ("potential_rejection", "Potential Rejection"),
                ],
                default="context_based",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flawlabel",
            name="type",
            field=models.CharField(
                choices=[
                    ("alias", "Alias"),
                    ("context_based", "Context Based"),
                    ("product_family", "Product Family"),
                    ("bu", "Bu"),
                    ("manual_triage", "Manual Triage"),
                    ("auto_affects", "Auto Affects"),
                    ("auto_rejected", "Auto Rejected"),
                    ("potential_rejection", "Potential Rejection"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
    ]
