# Generated by Django 5.2.12 on 2026-06-22 19:40
# Modified to include data cleanup before removing last_validated_dt field

import pgtrigger
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations

from osidb.core import set_user_acls


def cleanup_last_validated_dt_only_events(apps, schema_editor):
    """
    Remove FlawAudit update events where only last_validated_dt changed.

    This runs BEFORE removing the last_validated_dt field from FlawAudit table.

    Background: Analysis showed 97% of FlawAudit records were only last_validated_dt
    changes, causing massive table bloat and performance issues.
    """
    # Set ACLs to access all data (RLS is enabled on audit tables)
    set_user_acls(settings.ALL_GROUPS)

    FlawAudit = apps.get_model('osidb', 'FlawAudit')

    # Only process update events (not inserts/deletes)
    update_events = FlawAudit.objects.filter(pgh_label='update')

    total_events = update_events.count()
    if total_events == 0:
        print("No FlawAudit update events to clean up.")
        return

    print(f"\nStarting FlawAudit cleanup...")
    print(f"Total update events: {total_events:,}")

    # Fields to ignore when comparing events
    IGNORE_FIELDS = {
        'pgh_id', 'pgh_created_at', 'pgh_label', 'pgh_obj_id',
        'pgh_context_id', 'pgh_context', 'updated_dt', 'id',
        'local_updated_dt', 'meta_attr'
    }

    # Get all field names from the model
    all_fields = {f.name for f in FlawAudit._meta.fields if f.name not in IGNORE_FIELDS}

    # Track statistics
    events_to_delete = []
    deleted_count = 0
    kept_count = 0

    # Get unique flaw IDs using iterator to avoid loading all into memory
    # Count them first for progress reporting
    total_flaws = update_events.values_list('pgh_obj_id', flat=True).distinct().count()
    print(f"Processing {total_flaws:,} flaws...")

    processed_flaws = 0

    # Use iterator with chunk_size for memory efficiency on large datasets
    for flaw_id in update_events.values_list('pgh_obj_id', flat=True).distinct().iterator(chunk_size=1000):
        flaw_events = list(
            update_events.filter(pgh_obj_id=flaw_id).order_by('pgh_created_at')
        )

        # Compare consecutive events
        for i in range(len(flaw_events) - 1):
            current = flaw_events[i]
            next_event = flaw_events[i + 1]

            # Find what changed between events
            changed_fields = set()
            for field_name in all_fields:
                try:
                    current_val = getattr(current, field_name, None)
                    next_val = getattr(next_event, field_name, None)

                    if current_val != next_val:
                        changed_fields.add(field_name)
                except Exception:
                    pass

            # If ONLY last_validated_dt changed, mark for deletion
            if changed_fields == {'last_validated_dt'}:
                events_to_delete.append(next_event.pgh_id)
                deleted_count += 1
            else:
                kept_count += 1

        processed_flaws += 1

        if processed_flaws % 1000 == 0:
            print(f"  Progress: {processed_flaws:,}/{total_flaws:,} flaws "
                  f"({deleted_count:,} to delete, {kept_count:,} kept)")

        # Batch delete to avoid memory issues
        if len(events_to_delete) >= 10000:
            batch_size = 10000
            with pgtrigger.ignore("osidb.FlawAudit:append_only"):
                for i in range(0, len(events_to_delete), batch_size):
                    batch = events_to_delete[i:i + batch_size]
                    FlawAudit.objects.filter(pgh_id__in=batch).delete()
            print(f"  Deleted {deleted_count:,} events...")
            events_to_delete = []

    # Delete remaining events
    if events_to_delete:
        batch_size = 10000
        with pgtrigger.ignore("osidb.FlawAudit:append_only"):
            for i in range(0, len(events_to_delete), batch_size):
                batch = events_to_delete[i:i + batch_size]
                FlawAudit.objects.filter(pgh_id__in=batch).delete()

    # Final statistics
    print(f"\n{'='*60}")
    print(f"FlawAudit cleanup complete!")
    print(f"{'='*60}")
    print(f"Total events analyzed: {total_events:,}")
    print(f"Deleted (only last_validated_dt): {deleted_count:,} ({deleted_count/total_events*100:.1f}%)")
    print(f"Kept (substantive changes): {kept_count:,} ({kept_count/total_events*100:.1f}%)")
    print(f"Expected table size reduction: ~{deleted_count/total_events*100:.0f}%")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0237_delete_jirataskdownloadmanager'),
    ]

    operations = [
        # Step 1: Clean up bloated history data (while field still exists)
        migrations.RunPython(
            cleanup_last_validated_dt_only_events,
            migrations.RunPython.noop,
        ),

        # Step 2: Remove old triggers
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='delete_delete',
        ),

        # Step 3: Remove last_validated_dt field from FlawAudit table
        migrations.RemoveField(
            model_name='flawaudit',
            name='last_validated_dt',
        ),

        # Step 4: Add new triggers (without last_validated_dt)
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."mitre_cve_description", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='09da7097cc953a3c1d8cf304d35b0256b5899ec3', operation='INSERT', pgid='pgtrigger_insert_insert_4e668', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."aegis_meta" IS DISTINCT FROM (NEW."aegis_meta") OR OLD."comment_zero" IS DISTINCT FROM (NEW."comment_zero") OR OLD."components" IS DISTINCT FROM (NEW."components") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_description" IS DISTINCT FROM (NEW."cve_description") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."cwe_id" IS DISTINCT FROM (NEW."cwe_id") OR OLD."group_key" IS DISTINCT FROM (NEW."group_key") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."major_incident_start_dt" IS DISTINCT FROM (NEW."major_incident_start_dt") OR OLD."major_incident_state" IS DISTINCT FROM (NEW."major_incident_state") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."mitre_cve_description" IS DISTINCT FROM (NEW."mitre_cve_description") OR OLD."nist_cvss_validation" IS DISTINCT FROM (NEW."nist_cvss_validation") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."reported_dt" IS DISTINCT FROM (NEW."reported_dt") OR OLD."requires_cve_description" IS DISTINCT FROM (NEW."requires_cve_description") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."statement" IS DISTINCT FROM (NEW."statement") OR OLD."task_key" IS DISTINCT FROM (NEW."task_key") OR OLD."task_updated_dt" IS DISTINCT FROM (NEW."task_updated_dt") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."unembargo_dt" IS DISTINCT FROM (NEW."unembargo_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."workflow_name" IS DISTINCT FROM (NEW."workflow_name") OR OLD."workflow_state" IS DISTINCT FROM (NEW."workflow_state"))', func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."mitre_cve_description", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='7c0e1e16a8990229d8d38099e7aee8b41a684e9a', operation='UPDATE', pgid='pgtrigger_update_update_96595', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (OLD."acl_read", OLD."acl_write", OLD."aegis_meta", OLD."comment_zero", OLD."components", OLD."created_dt", OLD."cve_description", OLD."cve_id", OLD."cwe_id", OLD."group_key", OLD."impact", OLD."major_incident_start_dt", OLD."major_incident_state", OLD."mitigation", OLD."mitre_cve_description", OLD."nist_cvss_validation", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reported_dt", OLD."requires_cve_description", OLD."source", OLD."statement", OLD."task_key", OLD."task_updated_dt", OLD."team_id", OLD."title", OLD."unembargo_dt", OLD."uuid", OLD."workflow_name", OLD."workflow_state"); RETURN NULL;', hash='ada5b557cb1f4d82a617146d2c3131fcf6acb969', operation='DELETE', pgid='pgtrigger_delete_delete_f2e13', table='osidb_flaw', when='AFTER')),
        ),
    ]
