# Generated by Django 5.2.12 on 2026-05-15 11:03

from django.db import migrations, models


def clear_workflow_name_without_task_key(apps, schema_editor):
    """
    Clear workflow_name for Flaws that don't have a task_key.

    This addresses the issue where workflow_name defaulted to "DEFAULT"
    but flaws without a task_key should have empty workflow_name and workflow_state.
    The task_key is the workflow enabler - without it, there should be no workflow classification.
    """
    Flaw = apps.get_model('osidb', 'Flaw')

    # Clear workflow_name and workflow_state for flaws without task_key
    updated_count = Flaw.objects.filter(
        task_key__in=['', None]
    ).exclude(
        workflow_name__in=['', None]
    ).update(
        workflow_name='',
        workflow_state=''
    )

    if updated_count > 0:
        print(f"Cleared workflow_name for {updated_count} flaws without task_key")



class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0238_exclude_last_validated_dt_from_history'),
    ]

    operations = [
        # Schema change: remove "DEFAULT" default from workflow_name field
        migrations.AlterField(
            model_name='flaw',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='flawaudit',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        # Data migration: clear workflow_name for flaws without task_key
        migrations.RunPython(
            clear_workflow_name_without_task_key,
            migrations.RunPython.noop
        ),
    ]
