# Generated by Django 5.2.12 on 2026-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0239_remove_default_workflow_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flawcollaborator",
            name="type",
            field=models.CharField(
                choices=[
                    ("alias", "Alias"),
                    ("bu", "Bu"),
                    ("context_based", "Context Based"),
                    ("product_family", "Product Family"),
                    ("workflow", "Workflow"),
                ],
                default="context_based",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flawlabel",
            name="type",
            field=models.CharField(
                choices=[
                    ("alias", "Alias"),
                    ("bu", "Bu"),
                    ("context_based", "Context Based"),
                    ("product_family", "Product Family"),
                    ("workflow", "Workflow"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
    ]
