# Generated by Django 5.2.12 on 2026-06-28 19:46

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osidb', '0241_merge_workflow_improvements'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlawLabelV2',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels_v2', to='osidb.flaw')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BULabelDefinition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'BU Label Definition',
                'verbose_name_plural': 'BU Label Definitions',
            },
        ),
        migrations.CreateModel(
            name='CollaboratorLabelDefinition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Collaborator Label Definition',
                'verbose_name_plural': 'Collaborator Label Definitions',
            },
        ),
        migrations.CreateModel(
            name='ProductFamilyLabelDefinition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ps_components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ps_modules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ps_components_exclude', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ps_modules_exclude', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Product Family Label Definition',
                'verbose_name_plural': 'Product Family Label Definitions',
            },
        ),
        migrations.CreateModel(
            name='AliasLabel',
            fields=[
                ('flawlabelv2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osidb.flawlabelv2')),
            ],
            options={
                'verbose_name': 'Alias Label',
                'verbose_name_plural': 'Alias Labels',
            },
            bases=('osidb.flawlabelv2',),
        ),
        migrations.CreateModel(
            name='BULabel',
            fields=[
                ('flawlabelv2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osidb.flawlabelv2')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('REQ', 'Req'), ('SKIP', 'Skip'), ('DONE', 'Done')], default='NEW', max_length=10)),
                ('contributor', models.CharField(blank=True, max_length=255)),
                ('relevant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BU Label',
                'verbose_name_plural': 'BU Labels',
            },
            bases=('osidb.flawlabelv2',),
        ),
        migrations.CreateModel(
            name='CollaboratorLabel',
            fields=[
                ('flawlabelv2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osidb.flawlabelv2')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('REQ', 'Req'), ('SKIP', 'Skip'), ('DONE', 'Done')], default='NEW', max_length=10)),
                ('contributor', models.CharField(blank=True, max_length=255)),
                ('relevant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collaborator Label',
                'verbose_name_plural': 'Collaborator Labels',
            },
            bases=('osidb.flawlabelv2',),
        ),
        migrations.CreateModel(
            name='ProductFamilyLabel',
            fields=[
                ('flawlabelv2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osidb.flawlabelv2')),
                ('relevant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Family Label',
                'verbose_name_plural': 'Product Family Labels',
            },
            bases=('osidb.flawlabelv2',),
        ),
        migrations.CreateModel(
            name='WorkflowLabel',
            fields=[
                ('flawlabelv2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osidb.flawlabelv2')),
            ],
            options={
                'verbose_name': 'Workflow Label',
                'verbose_name_plural': 'Workflow Labels',
            },
            bases=('osidb.flawlabelv2',),
        ),
        migrations.CreateModel(
            name='FlawLabelV2Audit',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flaw', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='osidb.flaw')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='osidb.flawlabelv2')),
                ('polymorphic_ctype', models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='flawlabelv2',
            index=models.Index(fields=['flaw'], name='osidb_flawl_flaw_id_e760d6_idx'),
        ),
        migrations.AddIndex(
            model_name='flawlabelv2',
            index=models.Index(fields=['name'], name='osidb_flawl_name_e5b0eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='flawlabelv2',
            constraint=models.UniqueConstraint(fields=('flaw', 'name'), name='unique_label_per_flaw_v2'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawlabelv2',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawlabelv2audit" ("created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='42fcb997a0e79a74db0e8a7a7e61691d7323e49f', operation='INSERT', pgid='pgtrigger_insert_insert_fac9f', table='osidb_flawlabelv2', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawlabelv2',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "osidb_flawlabelv2audit" ("created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='243affe706143e4644cbdaba7b3af26b1022e518', operation='UPDATE', pgid='pgtrigger_update_update_6c509', table='osidb_flawlabelv2', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawlabelv2',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_flawlabelv2audit" ("created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (OLD."created_dt", OLD."flaw_id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."polymorphic_ctype_id", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='1812320983a301aa80ed96dadde062167d4e2a6a', operation='DELETE', pgid='pgtrigger_delete_delete_13ad7', table='osidb_flawlabelv2', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flawlabelv2audit',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='aa17b521c4ab50b0f606b73f610c6593f0d2cead', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_025ee', table='osidb_flawlabelv2audit', when='BEFORE')),
        ),
    ]
