# Generated by Django 5.2.13 on 2026-06-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0238_exclude_last_validated_dt_from_history"),
        ("osidb", "0242_workflow_state_free_form"),
    ]

    operations = []
