# Generated by Django 5.2.14 on 2026-07-23 18:24

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

from osidb.core import set_user_acls


def _rls_policy_sql(table: str, policy_prefix: str) -> str:
    return f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
--following policies define fine grained read/write control on {table} entity
--policy for entity insert (eg. create)
DROP policy if exists acl_policy_{policy_prefix}_create on {table};
create policy acl_policy_{policy_prefix}_create
on {table}
for INSERT
WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
     AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
--policy for entity select
DROP policy if exists acl_policy_{policy_prefix}_select on {table};
create policy acl_policy_{policy_prefix}_select
on {table}
for select
USING (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
--policy for entity update
DROP policy if exists acl_policy_{policy_prefix}_update on {table};
create policy acl_policy_{policy_prefix}_update
on {table}
for update
USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[])
WITH CHECK (acl_read::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]
     AND   acl_write::uuid[] && string_to_array(current_setting('osidb.acl'), ',')::uuid[]);
--policy for entity delete
DROP policy if exists acl_policy_{policy_prefix}_delete on {table};
create policy acl_policy_{policy_prefix}_delete
on {table}
for delete
USING (acl_write::uuid[] && string_to_array(current_setting('osidb.acl'),',')::uuid[]);
"""


LABEL_ACL_TABLES = (
    ("osidb_flawcollaborator", "flawcollaborator"),
    ("osidb_flawlabelv2", "flawlabelv2"),
    ("osidb_flawlabelv2audit", "flawlabelv2audit"),
)

ENABLE_LABEL_ACL_TABLE_RLS_SQL = "".join(
    _rls_policy_sql(table, policy_prefix) for table, policy_prefix in LABEL_ACL_TABLES
)

BACKFILL_LABEL_ACLS_SQL = """
UPDATE osidb_flawcollaborator
SET acl_read = f.acl_read, acl_write = f.acl_write
FROM osidb_flaw f
WHERE osidb_flawcollaborator.flaw_id = f.uuid
AND (osidb_flawcollaborator.acl_read != f.acl_read
     OR osidb_flawcollaborator.acl_write != f.acl_write);

UPDATE osidb_flawlabelv2
SET acl_read = f.acl_read, acl_write = f.acl_write
FROM osidb_flaw f
WHERE osidb_flawlabelv2.flaw_id = f.uuid
AND (osidb_flawlabelv2.acl_read != f.acl_read
     OR osidb_flawlabelv2.acl_write != f.acl_write);

-- Audit table is append-only; disable that trigger for the one-time backfill.
ALTER TABLE osidb_flawlabelv2audit DISABLE TRIGGER pgtrigger_append_only_025ee;
UPDATE osidb_flawlabelv2audit
SET acl_read = f.acl_read, acl_write = f.acl_write
FROM osidb_flaw f
WHERE osidb_flawlabelv2audit.flaw_id = f.uuid
AND (osidb_flawlabelv2audit.acl_read != f.acl_read
     OR osidb_flawlabelv2audit.acl_write != f.acl_write);
ALTER TABLE osidb_flawlabelv2audit ENABLE TRIGGER pgtrigger_append_only_025ee;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("osidb", "0246_enable_rls_on_child_acl_tables"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabelv2",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabelv2",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabelv2",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="flawcollaborator",
            name="acl_read",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="flawcollaborator",
            name="acl_write",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="flawlabelv2",
            name="acl_read",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="flawlabelv2",
            name="acl_write",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="flawlabelv2audit",
            name="acl_read",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="flawlabelv2audit",
            name="acl_write",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        # Bypass RLS while copying parent Flaw ACLs onto existing label rows.
        migrations.RunPython(
            lambda apps, schema_editor: set_user_acls(settings.ALL_GROUPS),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=BACKFILL_LABEL_ACLS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="flawcollaborator",
            index=models.Index(
                fields=["-updated_dt"], name="osidb_flawc_updated_f3a702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flawcollaborator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["acl_read"], name="osidb_flawc_acl_rea_8bc947_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="flawlabelv2",
            index=models.Index(
                fields=["-updated_dt"], name="osidb_flawl_updated_81fc17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flawlabelv2",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["acl_read"], name="osidb_flawl_acl_rea_04ecb5_gin"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabelv2",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="a85b567245ff1e95529613ec20f4126a91b54242",  # pragma: allowlist secret
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_fac9f",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabelv2",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="497cc9920a256ab3d4c58948a40b77a8441ad899",  # pragma: allowlist secret
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6c509",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabelv2",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."flaw_id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."polymorphic_ctype_id", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="25fa83ce00f1cca944923a932cf6c176ee0155a5",  # pragma: allowlist secret
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_13ad7",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RunSQL(
            sql=ENABLE_LABEL_ACL_TABLE_RLS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
