# Generated by Django 5.2.14 on 2026-07-14 16:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

from osidb.acls import ACL


SORT_ACL_ARRAYS = """
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'osidb_affect', 'osidb_affectaudit', 'osidb_affectcvss', 'osidb_affectcvssaudit',
        'osidb_alert', 'osidb_flaw', 'osidb_flawacknowledgment', 'osidb_flawacknowledgmentaudit',
        'osidb_flawaudit', 'osidb_flawcomment', 'osidb_flawcommentaudit',
        'osidb_flawcvss', 'osidb_flawcvssaudit', 'osidb_flawreference', 'osidb_flawreferenceaudit',
        'osidb_package', 'osidb_snippet', 'osidb_tracker', 'osidb_trackeraudit', 'osidb_upstreamdata'
    ]) LOOP
        EXECUTE format(
            'UPDATE %I SET '
            'acl_read = COALESCE((SELECT array_agg(u ORDER BY u) FROM unnest(acl_read) u), ARRAY[]::uuid[]), '
            'acl_write = COALESCE((SELECT array_agg(u ORDER BY u) FROM unnest(acl_write) u), ARRAY[]::uuid[])',
            tbl
        );
    END LOOP;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0246_enable_rls_on_child_acl_tables'),
    ]

    operations = [
        migrations.RunSQL(SORT_ACL_ARRAYS, migrations.RunSQL.noop),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='flaw',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tracker',
            name='update_update',
        ),
        migrations.AddField(
            model_name='affect',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='affect',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='affectaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='affectaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='affectcvss',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='affectcvss',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='affectcvssaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='affectcvssaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='alert',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='alert',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flaw',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flaw',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawacknowledgment',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawacknowledgment',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawacknowledgmentaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawacknowledgmentaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawcomment',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawcomment',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawcommentaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawcommentaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawcvss',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawcvss',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawcvssaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawcvssaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawreference',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawreference',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='flawreferenceaudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='flawreferenceaudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='package',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='package',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='snippet',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='snippet',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='tracker',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='tracker',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='trackeraudit',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='trackeraudit',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='upstreamdata',
            name='embargoed',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AddField(
            model_name='upstreamdata',
            name='visibility',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(acl_read=ACL.EMBARGO.uuid_read, then=models.Value('EMBARGOED')), models.When(acl_read=ACL.INTERNAL.uuid_read, then=models.Value('INTERNAL')), models.When(acl_read=ACL.PUBLIC.uuid_read, then=models.Value('PUBLIC')), default=models.Value('PUBLIC'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."affectedness" IS DISTINCT FROM (NEW."affectedness") OR OLD."assist_meta" IS DISTINCT FROM (NEW."assist_meta") OR OLD."created_by" IS DISTINCT FROM (NEW."created_by") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."labels" IS DISTINCT FROM (NEW."labels") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."not_affected_justification" IS DISTINCT FROM (NEW."not_affected_justification") OR OLD."ps_component" IS DISTINCT FROM (NEW."ps_component") OR OLD."ps_module" IS DISTINCT FROM (NEW."ps_module") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."purl" IS DISTINCT FROM (NEW."purl") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."subpackage_purls" IS DISTINCT FROM (NEW."subpackage_purls") OR OLD."tracker_id" IS DISTINCT FROM (NEW."tracker_id") OR OLD."updated_by" IS DISTINCT FROM (NEW."updated_by") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "assist_meta", "created_by", "created_dt", "cve_id", "flaw_id", "impact", "labels", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "ps_update_stream", "purl", "resolution", "resolved_dt", "subpackage_purls", "tracker_id", "updated_by", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."assist_meta", NEW."created_by", NEW."created_dt", NEW."cve_id", NEW."flaw_id", NEW."impact", NEW."labels", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."ps_update_stream", NEW."purl", NEW."resolution", NEW."resolved_dt", NEW."subpackage_purls", NEW."tracker_id", NEW."updated_by", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='77bfe303f508dde43bfbbd452c44227cfb2085b2', operation='UPDATE', pgid='pgtrigger_update_update_fdef6', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."aegis_meta" IS DISTINCT FROM (NEW."aegis_meta") OR OLD."comment_zero" IS DISTINCT FROM (NEW."comment_zero") OR OLD."components" IS DISTINCT FROM (NEW."components") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_description" IS DISTINCT FROM (NEW."cve_description") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."cwe_id" IS DISTINCT FROM (NEW."cwe_id") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."group_key" IS DISTINCT FROM (NEW."group_key") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."major_incident_start_dt" IS DISTINCT FROM (NEW."major_incident_start_dt") OR OLD."major_incident_state" IS DISTINCT FROM (NEW."major_incident_state") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."mitre_cve_description" IS DISTINCT FROM (NEW."mitre_cve_description") OR OLD."nist_cvss_validation" IS DISTINCT FROM (NEW."nist_cvss_validation") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."reported_dt" IS DISTINCT FROM (NEW."reported_dt") OR OLD."requires_cve_description" IS DISTINCT FROM (NEW."requires_cve_description") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."statement" IS DISTINCT FROM (NEW."statement") OR OLD."task_key" IS DISTINCT FROM (NEW."task_key") OR OLD."task_updated_dt" IS DISTINCT FROM (NEW."task_updated_dt") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."unembargo_dt" IS DISTINCT FROM (NEW."unembargo_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility") OR OLD."workflow_name" IS DISTINCT FROM (NEW."workflow_name") OR OLD."workflow_state" IS DISTINCT FROM (NEW."workflow_state"))', func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."mitre_cve_description", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;', hash='a921b372725efc44f142137090ea41c46ebec6d3', operation='UPDATE', pgid='pgtrigger_update_update_96595', table='osidb_flaw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tracker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."external_system_id" IS DISTINCT FROM (NEW."external_system_id") OR OLD."last_impact_increase_dt" IS DISTINCT FROM (NEW."last_impact_increase_dt") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."not_affected_justification" IS DISTINCT FROM (NEW."not_affected_justification") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."special_handling" IS DISTINCT FROM (NEW."special_handling") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "osidb_trackeraudit" ("acl_read", "acl_write", "created_dt", "cve_id", "external_system_id", "last_impact_increase_dt", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_update_stream", "resolution", "resolved_dt", "special_handling", "status", "type", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."cve_id", NEW."external_system_id", NEW."last_impact_increase_dt", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_update_stream", NEW."resolution", NEW."resolved_dt", NEW."special_handling", NEW."status", NEW."type", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='5974dd3abcf0570602d7d6813801354c1c461808', operation='UPDATE', pgid='pgtrigger_update_update_4b400', table='osidb_tracker', when='AFTER')),
        ),
    ]
