# Generated by Django 5.2.12 on 2026-07-29 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0247_add_acl_and_rls_to_flaw_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbiPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('ps_module', models.CharField()),
            ],
        ),
    ]
