# Generated by Django 5.2.12 on 2026-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0248_ubipackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='classification_meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
