# Generated by Django 5.2.13 on 2026-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0249_flaw_classification_meta"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flaw",
            index=models.Index(
                fields=["workflow_name"], name="osidb_flaw_workflo_b8190d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaw",
            index=models.Index(
                fields=["workflow_state"], name="osidb_flaw_workflo_500bae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaw",
            index=models.Index(fields=["owner"], name="osidb_flaw_owner_fc8e97_idx"),
        ),
    ]
