# Generated by Django 5.2.15 on 2026-07-31 16:13

import django.contrib.postgres.search
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0250_add_workflow_field_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='flaw',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector', sql=pgtrigger.compiler.UpsertTriggerSql(func="NEW.search_vector := setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') || setweight(to_tsvector('english', COALESCE(NEW.cve_id, '')), 'A') || setweight(to_tsvector('english', COALESCE(NEW.comment_zero, '')), 'B') || setweight(to_tsvector('english', COALESCE(NEW.cve_description, '')), 'C') || setweight(to_tsvector('english', COALESCE(NEW.statement, '')), 'D'); RETURN NEW;", hash='573bd5fc3b8fe380485bd01228cbb29f6f78a01f', operation='INSERT OR UPDATE OF "title", "cve_id", "comment_zero", "cve_description", "statement"', pgid='pgtrigger_update_search_vector_b66cc', table='osidb_flaw', when='BEFORE')),
        ),
    ]
