# Generated by Django 5.2.15 on 2026-07-31 16:14

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    # AddIndexConcurrently issues CREATE INDEX CONCURRENTLY, which cannot run inside a
    # transaction, so it does not block reads/writes on osidb_flaw while it builds.
    atomic = False

    dependencies = [
        ('osidb', '0252_flaw_search_vector_backfill'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='flaw',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='osidb_flaw_search__452786_gin'),
        ),
    ]
