# Generated by Django 5.2.13 on 2026-08-06 13:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0258_rename_flawlabelv2_to_flawlabel"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabel",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabel",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flawlabel",
            name="delete_delete",
        ),
        # Rename pointer fields in migration state only (no database changes).
        # The database column names remain as flawlabelv2_ptr_id to match the
        # parent table name (osidb_flawlabelv2, preserved via db_table in migration 0258).
        # For each child model: RenameField updates the Python field name to
        # match the new parent, then AlterField pins db_column="flawlabelv2_ptr_id"
        # so Django doesn't infer "flawlabel_ptr_id" (which doesn't exist in the DB).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="aliaslabel",
                    old_name="flawlabelv2_ptr",
                    new_name="flawlabel_ptr",
                ),
                migrations.AlterField(
                    model_name="aliaslabel",
                    name="flawlabel_ptr",
                    field=models.OneToOneField(
                        db_column="flawlabelv2_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osidb.flawlabel",
                    ),
                ),
                migrations.RenameField(
                    model_name="bulabel",
                    old_name="flawlabelv2_ptr",
                    new_name="flawlabel_ptr",
                ),
                migrations.AlterField(
                    model_name="bulabel",
                    name="flawlabel_ptr",
                    field=models.OneToOneField(
                        db_column="flawlabelv2_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osidb.flawlabel",
                    ),
                ),
                migrations.RenameField(
                    model_name="collaboratorlabel",
                    old_name="flawlabelv2_ptr",
                    new_name="flawlabel_ptr",
                ),
                migrations.AlterField(
                    model_name="collaboratorlabel",
                    name="flawlabel_ptr",
                    field=models.OneToOneField(
                        db_column="flawlabelv2_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osidb.flawlabel",
                    ),
                ),
                migrations.RenameField(
                    model_name="productfamilylabel",
                    old_name="flawlabelv2_ptr",
                    new_name="flawlabel_ptr",
                ),
                migrations.AlterField(
                    model_name="productfamilylabel",
                    name="flawlabel_ptr",
                    field=models.OneToOneField(
                        db_column="flawlabelv2_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osidb.flawlabel",
                    ),
                ),
                migrations.RenameField(
                    model_name="workflowlabel",
                    old_name="flawlabelv2_ptr",
                    new_name="flawlabel_ptr",
                ),
                migrations.AlterField(
                    model_name="workflowlabel",
                    name="flawlabel_ptr",
                    field=models.OneToOneField(
                        db_column="flawlabelv2_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osidb.flawlabel",
                    ),
                ),
            ],
            # No database operations - columns stay as flawlabelv2_ptr_id
            database_operations=[],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabel",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="bb4889967c6dd2993b2f8664e7c2a198564f2f51",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_cb495",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabel",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."polymorphic_ctype_id", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="73141dafb18c25c18b45eac3a140b7928b0d0d4c",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c49e8",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawlabel",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawlabelv2audit" ("acl_read", "acl_write", "created_dt", "flaw_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "polymorphic_ctype_id", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."flaw_id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."polymorphic_ctype_id", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="08c1e7dd4e681b4482a247b66ead4a4b3f8fbd29",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a3d49",
                    table="osidb_flawlabelv2",
                    when="AFTER",
                ),
            ),
        ),
    ]
