# Generated by Django 5.2.12 on 2026-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0264_enable_rls_on_label_child_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlabel',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Explanation for why this workflow label was applied (set by automation).'),
        ),
    ]
