# Generated by Django 5.2.12 on 2026-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0266_manual_triage_kernel_flaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='psproduct',
            name='team',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
