# Generated by Django 5.2.12 on 2026-08-31 13:23

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0268_create_natural_collation'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='affect',
            name='update_update',
        ),
        migrations.AddField(
            model_name='affect',
            name='affectedness_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='affectaudit',
            name='affectedness_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "affectedness_explanation", "assist_meta", "created_by", "created_dt", "cve_id", "flaw_id", "impact", "labels", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "ps_update_stream", "purl", "resolution", "resolved_dt", "subpackage_purls", "tracker_id", "updated_by", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."affectedness_explanation", NEW."assist_meta", NEW."created_by", NEW."created_dt", NEW."cve_id", NEW."flaw_id", NEW."impact", NEW."labels", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."ps_update_stream", NEW."purl", NEW."resolution", NEW."resolved_dt", NEW."subpackage_purls", NEW."tracker_id", NEW."updated_by", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='20cbef850a95fec439bc047f43c6475d3c8772c4', operation='INSERT', pgid='pgtrigger_insert_insert_0d1b1', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."affectedness" IS DISTINCT FROM (NEW."affectedness") OR OLD."affectedness_explanation" IS DISTINCT FROM (NEW."affectedness_explanation") OR OLD."assist_meta" IS DISTINCT FROM (NEW."assist_meta") OR OLD."created_by" IS DISTINCT FROM (NEW."created_by") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."labels" IS DISTINCT FROM (NEW."labels") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."not_affected_justification" IS DISTINCT FROM (NEW."not_affected_justification") OR OLD."ps_component" IS DISTINCT FROM (NEW."ps_component") OR OLD."ps_module" IS DISTINCT FROM (NEW."ps_module") OR OLD."ps_update_stream" IS DISTINCT FROM (NEW."ps_update_stream") OR OLD."purl" IS DISTINCT FROM (NEW."purl") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."subpackage_purls" IS DISTINCT FROM (NEW."subpackage_purls") OR OLD."tracker_id" IS DISTINCT FROM (NEW."tracker_id") OR OLD."updated_by" IS DISTINCT FROM (NEW."updated_by") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "affectedness_explanation", "assist_meta", "created_by", "created_dt", "cve_id", "flaw_id", "impact", "labels", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "ps_update_stream", "purl", "resolution", "resolved_dt", "subpackage_purls", "tracker_id", "updated_by", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."affectedness", NEW."affectedness_explanation", NEW."assist_meta", NEW."created_by", NEW."created_dt", NEW."cve_id", NEW."flaw_id", NEW."impact", NEW."labels", NEW."last_validated_dt", NEW."not_affected_justification", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."ps_component", NEW."ps_module", NEW."ps_update_stream", NEW."purl", NEW."resolution", NEW."resolved_dt", NEW."subpackage_purls", NEW."tracker_id", NEW."updated_by", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='762fd1a576347aee00bbb5d94466a4ae0267f80a', operation='UPDATE', pgid='pgtrigger_update_update_fdef6', table='osidb_affect', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='affect',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "osidb_affectaudit" ("acl_read", "acl_write", "affectedness", "affectedness_explanation", "assist_meta", "created_by", "created_dt", "cve_id", "flaw_id", "impact", "labels", "last_validated_dt", "not_affected_justification", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ps_component", "ps_module", "ps_update_stream", "purl", "resolution", "resolved_dt", "subpackage_purls", "tracker_id", "updated_by", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."affectedness", OLD."affectedness_explanation", OLD."assist_meta", OLD."created_by", OLD."created_dt", OLD."cve_id", OLD."flaw_id", OLD."impact", OLD."labels", OLD."last_validated_dt", OLD."not_affected_justification", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."ps_component", OLD."ps_module", OLD."ps_update_stream", OLD."purl", OLD."resolution", OLD."resolved_dt", OLD."subpackage_purls", OLD."tracker_id", OLD."updated_by", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='27318ea742ba139f28a6604dd0f48addf638a8f3', operation='DELETE', pgid='pgtrigger_delete_delete_cc8c5', table='osidb_affect', when='AFTER')),
        ),
    ]
