# Generated by Django 4.2.20 on 2026-09-18 00:00

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from osidb.helpers import bypass_rls


@bypass_rls
def recalculate_cvssv4_scores(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Recalculate scores for all CVSSv4 vectors using the updated cvss library
    which includes rounding error fixes for CVSSv4 score calculation.
    """
    from cvss import CVSS4

    FlawCVSS = apps.get_model("osidb", "FlawCVSS")
    AffectCVSS = apps.get_model("osidb", "AffectCVSS")

    # Process FlawCVSS records
    flaw_cvss_v4 = FlawCVSS.objects.filter(version="V4")
    flaw_to_update = []

    for cvss in flaw_cvss_v4.iterator(chunk_size=1000):
        cvss_obj = CVSS4(cvss.vector)
        new_score = float(cvss_obj.base_score)

        # Only update if the score has changed
        if cvss.score != new_score:
            cvss.score = new_score
            flaw_to_update.append(cvss)

        if len(flaw_to_update) >= 1000:
            FlawCVSS.objects.bulk_update(flaw_to_update, ["score"], batch_size=1000)
            flaw_to_update = []

    if flaw_to_update:
        FlawCVSS.objects.bulk_update(flaw_to_update, ["score"], batch_size=1000)

    # Process AffectCVSS records
    affect_cvss_v4 = AffectCVSS.objects.filter(version="V4")
    affect_to_update = []

    for cvss in affect_cvss_v4.iterator(chunk_size=1000):
        cvss_obj = CVSS4(cvss.vector)
        new_score = float(cvss_obj.base_score)

        # Only update if the score has changed
        if cvss.score != new_score:
            cvss.score = new_score
            affect_to_update.append(cvss)

        if len(affect_to_update) >= 1000:
            AffectCVSS.objects.bulk_update(affect_to_update, ["score"], batch_size=1000)
            affect_to_update = []

    if affect_to_update:
        AffectCVSS.objects.bulk_update(affect_to_update, ["score"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0270_remove_flaw_insert_insert_remove_flaw_delete_delete_and_more"),
    ]

    operations = [
        migrations.RunPython(
            recalculate_cvssv4_scores, reverse_code=migrations.RunPython.noop
        ),
    ]
