# Generated by Django 5.2.16 on 2026-10-02 15:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0273_psupdatestream_minimal_impact"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="flaw",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flaw",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="flaw",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="flaw",
            name="assist_meta",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="flawaudit",
            name="assist_meta",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "assist_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "resolved_dt", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."assist_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."mitre_cve_description", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."resolved_dt", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;',
                    hash="cb9455227d4ba5daad701af4c44840a1bc754e43",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4e668",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."aegis_meta" IS DISTINCT FROM (NEW."aegis_meta") OR OLD."assist_meta" IS DISTINCT FROM (NEW."assist_meta") OR OLD."comment_zero" IS DISTINCT FROM (NEW."comment_zero") OR OLD."components" IS DISTINCT FROM (NEW."components") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."cve_description" IS DISTINCT FROM (NEW."cve_description") OR OLD."cve_id" IS DISTINCT FROM (NEW."cve_id") OR OLD."cwe_id" IS DISTINCT FROM (NEW."cwe_id") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."group_key" IS DISTINCT FROM (NEW."group_key") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."major_incident_start_dt" IS DISTINCT FROM (NEW."major_incident_start_dt") OR OLD."major_incident_state" IS DISTINCT FROM (NEW."major_incident_state") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."mitre_cve_description" IS DISTINCT FROM (NEW."mitre_cve_description") OR OLD."nist_cvss_validation" IS DISTINCT FROM (NEW."nist_cvss_validation") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."reported_dt" IS DISTINCT FROM (NEW."reported_dt") OR OLD."requires_cve_description" IS DISTINCT FROM (NEW."requires_cve_description") OR OLD."resolved_dt" IS DISTINCT FROM (NEW."resolved_dt") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."statement" IS DISTINCT FROM (NEW."statement") OR OLD."task_key" IS DISTINCT FROM (NEW."task_key") OR OLD."task_updated_dt" IS DISTINCT FROM (NEW."task_updated_dt") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."unembargo_dt" IS DISTINCT FROM (NEW."unembargo_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility") OR OLD."workflow_name" IS DISTINCT FROM (NEW."workflow_name") OR OLD."workflow_state" IS DISTINCT FROM (NEW."workflow_state"))',
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "assist_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "resolved_dt", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (NEW."acl_read", NEW."acl_write", NEW."aegis_meta", NEW."assist_meta", NEW."comment_zero", NEW."components", NEW."created_dt", NEW."cve_description", NEW."cve_id", NEW."cwe_id", NEW."group_key", NEW."impact", NEW."major_incident_start_dt", NEW."major_incident_state", NEW."mitigation", NEW."mitre_cve_description", NEW."nist_cvss_validation", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reported_dt", NEW."requires_cve_description", NEW."resolved_dt", NEW."source", NEW."statement", NEW."task_key", NEW."task_updated_dt", NEW."team_id", NEW."title", NEW."unembargo_dt", NEW."uuid", NEW."workflow_name", NEW."workflow_state"); RETURN NULL;',
                    hash="2e4511e0c0022fe6ec60b76d78ff26253f73e468",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_96595",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flaw",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "osidb_flawaudit" ("acl_read", "acl_write", "aegis_meta", "assist_meta", "comment_zero", "components", "created_dt", "cve_description", "cve_id", "cwe_id", "group_key", "impact", "major_incident_start_dt", "major_incident_state", "mitigation", "mitre_cve_description", "nist_cvss_validation", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reported_dt", "requires_cve_description", "resolved_dt", "source", "statement", "task_key", "task_updated_dt", "team_id", "title", "unembargo_dt", "uuid", "workflow_name", "workflow_state") VALUES (OLD."acl_read", OLD."acl_write", OLD."aegis_meta", OLD."assist_meta", OLD."comment_zero", OLD."components", OLD."created_dt", OLD."cve_description", OLD."cve_id", OLD."cwe_id", OLD."group_key", OLD."impact", OLD."major_incident_start_dt", OLD."major_incident_state", OLD."mitigation", OLD."mitre_cve_description", OLD."nist_cvss_validation", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reported_dt", OLD."requires_cve_description", OLD."resolved_dt", OLD."source", OLD."statement", OLD."task_key", OLD."task_updated_dt", OLD."team_id", OLD."title", OLD."unembargo_dt", OLD."uuid", OLD."workflow_name", OLD."workflow_state"); RETURN NULL;',
                    hash="4fc0f6f7b1318d7b07a58c0627528fb35572f026",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f2e13",
                    table="osidb_flaw",
                    when="AFTER",
                ),
            ),
        ),
    ]
