# Generated by Django 5.2.12 on 2026-06-23 14:12

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import psqlextra.fields.hstore_field
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osidb', '0237_delete_jirataskdownloadmanager'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPReport',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('last_validated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missing_required_fields', models.TextField(blank=True, help_text='Missing required fields')),
                ('manual_completion_notes', models.TextField(blank=True, help_text='Manual completion notes')),
                ('title', models.CharField(help_text='Title of the SRP report', max_length=255)),
                ('manufacturer_or_steward_name', models.CharField(blank=True, help_text='Name of the manufacturer or steward', max_length=255)),
                ('responsibility_scope', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('steward', 'Steward')], help_text='Whether Red Hat acts as manufacturer or steward', max_length=20)),
                ('reportable_event_type', models.CharField(choices=[('actively_exploited_vulnerability', 'Actively Exploited Vulnerability'), ('severe_incident', 'Severe Incident'), ('additional_information_request', 'Additional Information Request')], help_text='Type of event being reported to ENISA', max_length=50)),
                ('status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_required', 'Not Required'), ('required', 'Required'), ('prepared', 'Prepared'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='required', help_text='Current status of the SRP report', max_length=20)),
                ('timer_started_at', models.DateTimeField(blank=True, help_text='When the SLA clock started for this report', null=True)),
                ('srp_reference_id', models.CharField(blank=True, help_text='Reference ID returned by the SRP after submission', max_length=255)),
                ('srp_reference_url', models.URLField(blank=True, help_text='URL of the SRP reference')),
                ('member_states_available', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='List of EU member state codes where product is available', size=None)),
                ('designated_csirt_country', models.CharField(blank=True, help_text='Country code of the designated CSIRT coordinator', max_length=2)),
                ('designated_csirt_source', models.CharField(blank=True, help_text='Source of the designated CSIRT coordinator', max_length=255)),
                ('meta_attr', psqlextra.fields.hstore_field.HStoreField(default=dict)),
                ('flaw', models.ForeignKey(help_text='The flaw for which this SRP report is being created', on_delete=django.db.models.deletion.PROTECT, related_name='srp_reports', to='osidb.flaw')),
            ],
            options={
                'verbose_name': 'SRP Report',
                'verbose_name_plural': 'SRP Reports',
                'ordering': ('created_dt', 'uuid', 'timer_started_at'),
            },
        ),
        migrations.CreateModel(
            name='SRPReportAudit',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('last_validated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('missing_required_fields', models.TextField(blank=True, help_text='Missing required fields')),
                ('manual_completion_notes', models.TextField(blank=True, help_text='Manual completion notes')),
                ('title', models.CharField(help_text='Title of the SRP report', max_length=255)),
                ('manufacturer_or_steward_name', models.CharField(blank=True, help_text='Name of the manufacturer or steward', max_length=255)),
                ('responsibility_scope', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('steward', 'Steward')], help_text='Whether Red Hat acts as manufacturer or steward', max_length=20)),
                ('reportable_event_type', models.CharField(choices=[('actively_exploited_vulnerability', 'Actively Exploited Vulnerability'), ('severe_incident', 'Severe Incident'), ('additional_information_request', 'Additional Information Request')], help_text='Type of event being reported to ENISA', max_length=50)),
                ('status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_required', 'Not Required'), ('required', 'Required'), ('prepared', 'Prepared'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='required', help_text='Current status of the SRP report', max_length=20)),
                ('timer_started_at', models.DateTimeField(blank=True, help_text='When the SLA clock started for this report', null=True)),
                ('srp_reference_id', models.CharField(blank=True, help_text='Reference ID returned by the SRP after submission', max_length=255)),
                ('srp_reference_url', models.URLField(blank=True, help_text='URL of the SRP reference')),
                ('member_states_available', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='List of EU member state codes where product is available', size=None)),
                ('designated_csirt_country', models.CharField(blank=True, help_text='Country code of the designated CSIRT coordinator', max_length=2)),
                ('designated_csirt_source', models.CharField(blank=True, help_text='Source of the designated CSIRT coordinator', max_length=255)),
                ('flaw', models.ForeignKey(db_constraint=False, help_text='The flaw for which this SRP report is being created', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='osidb.flaw')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='regulatory_reporting.srpreport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SRPReportMilestone',
            fields=[
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('last_validated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missing_required_fields', models.TextField(blank=True, help_text='Missing required fields')),
                ('manual_completion_notes', models.TextField(blank=True, help_text='Manual completion notes')),
                ('milestone_type', models.CharField(choices=[('24h', '24 Hour Template'), ('72h', '72 Hour Template'), ('final', 'Final Report Template'), ('additional_information_response', 'Additional Information Response Template')], help_text='Type of milestone (24h, 72h, final, etc.)', max_length=50)),
                ('request_received_at', models.DateTimeField(blank=True, help_text='When the request was received', null=True)),
                ('request_source', models.CharField(blank=True, help_text='Source of the request', max_length=255)),
                ('request_text', models.TextField(blank=True, help_text='Text of the request')),
                ('status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_required', 'Not Required'), ('required', 'Required'), ('prepared', 'Prepared'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='required', help_text='Current status of the milestone', max_length=20)),
                ('meta_attr', psqlextra.fields.hstore_field.HStoreField(default=dict)),
                ('srp_report', models.ForeignKey(help_text='The SRP report this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='regulatory_reporting.srpreport')),
            ],
            options={
                'verbose_name': 'SRP Report Milestone',
                'verbose_name_plural': 'SRP Report Milestones',
                'ordering': ('srp_report', 'created_dt'),
            },
        ),
        migrations.CreateModel(
            name='SRPReportMilestoneAudit',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created_dt', models.DateTimeField(blank=True)),
                ('updated_dt', models.DateTimeField(blank=True)),
                ('acl_read', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('acl_write', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('last_validated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('missing_required_fields', models.TextField(blank=True, help_text='Missing required fields')),
                ('manual_completion_notes', models.TextField(blank=True, help_text='Manual completion notes')),
                ('milestone_type', models.CharField(choices=[('24h', '24 Hour Template'), ('72h', '72 Hour Template'), ('final', 'Final Report Template'), ('additional_information_response', 'Additional Information Response Template')], help_text='Type of milestone (24h, 72h, final, etc.)', max_length=50)),
                ('request_received_at', models.DateTimeField(blank=True, help_text='When the request was received', null=True)),
                ('request_source', models.CharField(blank=True, help_text='Source of the request', max_length=255)),
                ('request_text', models.TextField(blank=True, help_text='Text of the request')),
                ('status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_required', 'Not Required'), ('required', 'Required'), ('prepared', 'Prepared'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='required', help_text='Current status of the milestone', max_length=20)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='regulatory_reporting.srpreportmilestone')),
                ('srp_report', models.ForeignKey(db_constraint=False, help_text='The SRP report this milestone belongs to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='regulatory_reporting.srpreport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['-updated_dt'], name='regulatory__updated_dd635c_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['flaw'], name='regulatory__flaw_id_13d5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['status'], name='regulatory__status_95077c_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['timer_started_at'], name='regulatory__timer_s_46c076_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['reportable_event_type'], name='regulatory__reporta_2f2214_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=models.Index(fields=['responsibility_scope'], name='regulatory__respons_5ed658_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acl_read'], name='regulatory__acl_rea_fe6189_gin'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreport',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."designated_csirt_country", NEW."designated_csirt_source", NEW."flaw_id", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manufacturer_or_steward_name", NEW."member_states_available", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reportable_event_type", NEW."responsibility_scope", NEW."srp_reference_id", NEW."srp_reference_url", NEW."status", NEW."timer_started_at", NEW."title", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='6251342ad40b38dbfb27e8d177d2b482d029c2d5', operation='INSERT', pgid='pgtrigger_insert_insert_b0483', table='regulatory_reporting_srpreport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreport',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."designated_csirt_country" IS DISTINCT FROM (NEW."designated_csirt_country") OR OLD."designated_csirt_source" IS DISTINCT FROM (NEW."designated_csirt_source") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."manufacturer_or_steward_name" IS DISTINCT FROM (NEW."manufacturer_or_steward_name") OR OLD."member_states_available" IS DISTINCT FROM (NEW."member_states_available") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."reportable_event_type" IS DISTINCT FROM (NEW."reportable_event_type") OR OLD."responsibility_scope" IS DISTINCT FROM (NEW."responsibility_scope") OR OLD."srp_reference_id" IS DISTINCT FROM (NEW."srp_reference_id") OR OLD."srp_reference_url" IS DISTINCT FROM (NEW."srp_reference_url") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."timer_started_at" IS DISTINCT FROM (NEW."timer_started_at") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."designated_csirt_country", NEW."designated_csirt_source", NEW."flaw_id", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manufacturer_or_steward_name", NEW."member_states_available", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportable_event_type", NEW."responsibility_scope", NEW."srp_reference_id", NEW."srp_reference_url", NEW."status", NEW."timer_started_at", NEW."title", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='bae34fae192486393ca56660eac601210c836c43', operation='UPDATE', pgid='pgtrigger_update_update_20d0f', table='regulatory_reporting_srpreport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreport',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."designated_csirt_country", OLD."designated_csirt_source", OLD."flaw_id", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."manufacturer_or_steward_name", OLD."member_states_available", OLD."missing_required_fields", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reportable_event_type", OLD."responsibility_scope", OLD."srp_reference_id", OLD."srp_reference_url", OLD."status", OLD."timer_started_at", OLD."title", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='531c1edc98ade0b23475d7655ccc0ead351804ad', operation='DELETE', pgid='pgtrigger_delete_delete_a5222', table='regulatory_reporting_srpreport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportaudit',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='175197ff1c4c1fd3da783daf7cc9b7d93e0a6d1d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_24327', table='regulatory_reporting_srpreportaudit', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['-updated_dt'], name='regulatory__updated_d06ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['srp_report'], name='regulatory__srp_rep_22bfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['milestone_type'], name='regulatory__milesto_a09bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['status'], name='regulatory__status_4cec18_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acl_read'], name='regulatory__acl_rea_2aabad_gin'),
        ),
        migrations.AddConstraint(
            model_name='srpreportmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('milestone_type', 'additional_information_response'), _negated=True), fields=('srp_report', 'milestone_type'), name='unique_srp_report_milestone_type_level'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='be72abc9a4558cece9a31e967b87cd1597891651', operation='INSERT', pgid='pgtrigger_insert_insert_53837', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."milestone_type" IS DISTINCT FROM (NEW."milestone_type") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."request_received_at" IS DISTINCT FROM (NEW."request_received_at") OR OLD."request_source" IS DISTINCT FROM (NEW."request_source") OR OLD."request_text" IS DISTINCT FROM (NEW."request_text") OR OLD."srp_report_id" IS DISTINCT FROM (NEW."srp_report_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='de99675ca0fa4c188e5ceb60002746ee4aa1205d', operation='UPDATE', pgid='pgtrigger_update_update_59a28', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."milestone_type", OLD."missing_required_fields", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."srp_report_id", OLD."status", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='33fedc6c27ed6d9cd5711a47f488c05770e79d69', operation='DELETE', pgid='pgtrigger_delete_delete_a9aad', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestoneaudit',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='06629a5c88f54e70c89e751fcff954e5ef8ea1d7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_5de36', table='regulatory_reporting_srpreportmilestoneaudit', when='BEFORE')),
        ),
    ]
