# Generated by Django 5.2.13 on 2026-06-23 16:22

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osidb", "0237_delete_jirataskdownloadmanager"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("regulatory_reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpstreamProject",
            fields=[
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_name", models.CharField(max_length=255)),
                ("repository_url", models.URLField(blank=True)),
                ("security_contact", models.CharField(blank=True, max_length=255)),
                (
                    "contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("github_issue", "Github Issue"),
                            ("gitlab_issue", "Gitlab Issue"),
                            ("forgejo_issue", "Forgejo Issue"),
                            ("website_form", "Website Form"),
                            ("none_found", "None Found"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_url", models.URLField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("confidence", models.CharField(blank=True, max_length=50)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by", models.CharField(blank=True, max_length=255)),
                ("unsupported", models.BooleanField(default=False)),
                ("stewarded_awareness", models.BooleanField(default=False)),
                ("stewarded_awareness_reason", models.TextField(blank=True)),
                (
                    "stewarded_awareness_marked_by",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "stewarded_awareness_marked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Upstream Project",
                "verbose_name_plural": "Upstream Projects",
            },
        ),
        migrations.CreateModel(
            name="FlawUpstreamMapping",
            fields=[
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "flaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_mappings",
                        to="osidb.flaw",
                    ),
                ),
                (
                    "upstream_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flaw_mappings",
                        to="regulatory_reporting.upstreamproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flaw Upstream Mapping",
                "verbose_name_plural": "Flaw Upstream Mappings",
            },
        ),
        migrations.CreateModel(
            name="UpstreamNotification",
            fields=[
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("not_required", "Not Required"),
                            ("required", "Required"),
                            ("contact_needed", "Contact Needed"),
                            ("prepared", "Prepared"),
                            ("reviewed", "Reviewed"),
                            ("sent", "Sent"),
                            ("deferred", "Deferred"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                (
                    "reportability_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red_hat_identified", "Red Hat Identified"),
                            ("jointly_identified", "Jointly Identified"),
                            ("manual_override", "Manual Override"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("github_issue", "Github Issue"),
                            ("gitlab_issue", "Gitlab Issue"),
                            ("forgejo_issue", "Forgejo Issue"),
                            ("website_form", "Website Form"),
                            ("other_manual", "Other Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "flaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_notifications",
                        to="osidb.flaw",
                    ),
                ),
                (
                    "upstream_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="regulatory_reporting.upstreamproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upstream Notification",
                "verbose_name_plural": "Upstream Notifications",
            },
        ),
        migrations.CreateModel(
            name="UpstreamNotificationAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "acl_read",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "acl_write",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("not_required", "Not Required"),
                            ("required", "Required"),
                            ("contact_needed", "Contact Needed"),
                            ("prepared", "Prepared"),
                            ("reviewed", "Reviewed"),
                            ("sent", "Sent"),
                            ("deferred", "Deferred"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                (
                    "reportability_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red_hat_identified", "Red Hat Identified"),
                            ("jointly_identified", "Jointly Identified"),
                            ("manual_override", "Manual Override"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("github_issue", "Github Issue"),
                            ("gitlab_issue", "Gitlab Issue"),
                            ("forgejo_issue", "Forgejo Issue"),
                            ("website_form", "Website Form"),
                            ("other_manual", "Other Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "flaw",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="osidb.flaw",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="regulatory_reporting.upstreamnotification",
                    ),
                ),
                (
                    "upstream_project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="regulatory_reporting.upstreamproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlawUpstreamMappingAudit",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_dt", models.DateTimeField(blank=True)),
                ("updated_dt", models.DateTimeField(blank=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "flaw",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="osidb.flaw",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="regulatory_reporting.flawupstreammapping",
                    ),
                ),
                (
                    "upstream_project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="regulatory_reporting.upstreamproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotificationaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="c82c453eced7d9f18d3f18c91ad612a07b5237b0",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_f899c",
                    table="regulatory_reporting_upstreamnotificationaudit",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="upstreamnotification",
            index=models.Index(fields=["flaw"], name="regulatory__flaw_id_bf4d9d_idx"),
        ),
        migrations.AddIndex(
            model_name="upstreamnotification",
            index=models.Index(fields=["status"], name="regulatory__status_f6064d_idx"),
        ),
        migrations.AddIndex(
            model_name="upstreamnotification",
            index=models.Index(
                fields=["timer_started_at"], name="regulatory__timer_s_209cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upstreamnotification",
            index=models.Index(
                fields=["upstream_project"], name="regulatory__upstrea_b432a4_idx"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reportability_reason", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="f99afaed3edb8a5ce6c4d4cf5cb609a8b8e9b8b5",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_cba87",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportability_reason", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="fe64e4cb9d2a01d66251363f9bb0767acc348499",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_281d6",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."flaw_id", OLD."last_error", OLD."method", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reportability_reason", OLD."status", OLD."timer_started_at", OLD."updated_dt", OLD."upstream_project_id", OLD."uuid"); RETURN NULL;',
                    hash="71315ae65de72c0afb12880478d76840a7fb8c07",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_3a634",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawupstreammappingaudit",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="97a3f51c185b374cf42bd22fafb0bf5e0e2c1562",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4a66b",
                    table="regulatory_reporting_flawupstreammappingaudit",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawupstreammapping",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_flawupstreammappingaudit" ("created_dt", "flaw_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."created_dt", NEW."flaw_id", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="68782b67597cfba4592ad7ffb34215ee7a83ba8e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_85e92",
                    table="regulatory_reporting_flawupstreammapping",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawupstreammapping",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_flawupstreammappingaudit" ("created_dt", "flaw_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."created_dt", NEW."flaw_id", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="e5afb86aa3ede040e99d0c114c8d1167cfd15c4f",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_37fd9",
                    table="regulatory_reporting_flawupstreammapping",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="flawupstreammapping",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_flawupstreammappingaudit" ("created_dt", "flaw_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_dt", "upstream_project_id", "uuid") VALUES (OLD."created_dt", OLD."flaw_id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."updated_dt", OLD."upstream_project_id", OLD."uuid"); RETURN NULL;',
                    hash="e588b98bd7b45a7a8b0416e73dd79bb71dae59bb",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_d6b81",
                    table="regulatory_reporting_flawupstreammapping",
                    when="AFTER",
                ),
            ),
        ),
    ]
