# Generated by Django 5.2.13 on 2026-06-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulatory_reporting", "0002_upstreamproject_flawupstreammapping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upstreamnotification",
            name="upstream_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="regulatory_reporting.upstreamproject",
            ),
        ),
        migrations.AlterField(
            model_name="upstreamnotificationaudit",
            name="upstream_project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="regulatory_reporting.upstreamproject",
            ),
        ),
    ]
