# Generated by Django 5.2.13 on 2026-07-09 15:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "regulatory_reporting",
            "0003_alter_upstreamnotification_upstream_project_and_more",
        ),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="upstreamnotification",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="upstreamnotification",
            name="payload_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="upstreamnotificationaudit",
            name="payload_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="upstreamnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("required", "Required"),
                    ("contact_needed", "Contact Needed"),
                    ("prepared", "Prepared"),
                    ("reviewed", "Reviewed"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="upstreamnotificationaudit",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("required", "Required"),
                    ("contact_needed", "Contact Needed"),
                    ("prepared", "Prepared"),
                    ("reviewed", "Reviewed"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                max_length=20,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", NEW."payload_text", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reportability_reason", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="ab3283502a4cab2c6fdf3169657fdfb56df2bbab",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_cba87",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."flaw_id", NEW."last_error", NEW."method", NEW."payload_text", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportability_reason", NEW."status", NEW."timer_started_at", NEW."updated_dt", NEW."upstream_project_id", NEW."uuid"); RETURN NULL;',
                    hash="02332edaf55e01ad466072a1b7597014384cad32",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_281d6",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="upstreamnotification",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_upstreamnotificationaudit" ("acl_read", "acl_write", "created_dt", "flaw_id", "last_error", "method", "payload_text", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportability_reason", "status", "timer_started_at", "updated_dt", "upstream_project_id", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."flaw_id", OLD."last_error", OLD."method", OLD."payload_text", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reportability_reason", OLD."status", OLD."timer_started_at", OLD."updated_dt", OLD."upstream_project_id", OLD."uuid"); RETURN NULL;',
                    hash="1366dcb4f6b486ead4564e504c9699df3d78d6d8",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_3a634",
                    table="regulatory_reporting_upstreamnotification",
                    when="AFTER",
                ),
            ),
        ),
    ]
