# Generated by Django 5.2.14 on 2026-08-03 08:42

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulatory_reporting", "0005_upstreamproject_purl"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreport",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreport",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="srpreport",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="srpreport",
            name="evidence",
            field=models.TextField(
                blank=True,
                help_text="Justification for manually creating this SRP report when automatic criteria were not met",
            ),
        ),
        migrations.AddField(
            model_name="srpreportaudit",
            name="evidence",
            field=models.TextField(
                blank=True,
                help_text="Justification for manually creating this SRP report when automatic criteria were not met",
            ),
        ),
        migrations.AlterField(
            model_name="srpreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("pre_required", "Pre Required"),
                    ("required", "Required"),
                    ("prepared", "Prepared"),
                    ("submitted", "Submitted"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                help_text="Current status of the SRP report",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="srpreportaudit",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("pre_required", "Pre Required"),
                    ("required", "Required"),
                    ("prepared", "Prepared"),
                    ("submitted", "Submitted"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                help_text="Current status of the SRP report",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="srpreportmilestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("pre_required", "Pre Required"),
                    ("required", "Required"),
                    ("prepared", "Prepared"),
                    ("submitted", "Submitted"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                help_text="Current status of the milestone",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="srpreportmilestoneaudit",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("not_required", "Not Required"),
                    ("pre_required", "Pre Required"),
                    ("required", "Required"),
                    ("prepared", "Prepared"),
                    ("submitted", "Submitted"),
                    ("deferred", "Deferred"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="required",
                help_text="Current status of the milestone",
                max_length=20,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreport",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "evidence", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."designated_csirt_country", NEW."designated_csirt_source", NEW."evidence", NEW."flaw_id", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manufacturer_or_steward_name", NEW."member_states_available", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."reportable_event_type", NEW."responsibility_scope", NEW."srp_reference_id", NEW."srp_reference_url", NEW."status", NEW."timer_started_at", NEW."title", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="8e8a66e9676dbf699928a707e2bbe3b8ec1757c8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b0483",
                    table="regulatory_reporting_srpreport",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreport",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."designated_csirt_country" IS DISTINCT FROM (NEW."designated_csirt_country") OR OLD."designated_csirt_source" IS DISTINCT FROM (NEW."designated_csirt_source") OR OLD."evidence" IS DISTINCT FROM (NEW."evidence") OR OLD."flaw_id" IS DISTINCT FROM (NEW."flaw_id") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."manufacturer_or_steward_name" IS DISTINCT FROM (NEW."manufacturer_or_steward_name") OR OLD."member_states_available" IS DISTINCT FROM (NEW."member_states_available") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."reportable_event_type" IS DISTINCT FROM (NEW."reportable_event_type") OR OLD."responsibility_scope" IS DISTINCT FROM (NEW."responsibility_scope") OR OLD."srp_reference_id" IS DISTINCT FROM (NEW."srp_reference_id") OR OLD."srp_reference_url" IS DISTINCT FROM (NEW."srp_reference_url") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."timer_started_at" IS DISTINCT FROM (NEW."timer_started_at") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))',
                    func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "evidence", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."designated_csirt_country", NEW."designated_csirt_source", NEW."evidence", NEW."flaw_id", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."manufacturer_or_steward_name", NEW."member_states_available", NEW."missing_required_fields", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."reportable_event_type", NEW."responsibility_scope", NEW."srp_reference_id", NEW."srp_reference_url", NEW."status", NEW."timer_started_at", NEW."title", NEW."updated_dt", NEW."uuid"); RETURN NULL;',
                    hash="7ce3f4245c80a434a1064f37a47dadb282df3a95",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_20d0f",
                    table="regulatory_reporting_srpreport",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="srpreport",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "regulatory_reporting_srpreportaudit" ("acl_read", "acl_write", "created_dt", "designated_csirt_country", "designated_csirt_source", "evidence", "flaw_id", "last_validated_dt", "manual_completion_notes", "manufacturer_or_steward_name", "member_states_available", "missing_required_fields", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reportable_event_type", "responsibility_scope", "srp_reference_id", "srp_reference_url", "status", "timer_started_at", "title", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."designated_csirt_country", OLD."designated_csirt_source", OLD."evidence", OLD."flaw_id", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."manufacturer_or_steward_name", OLD."member_states_available", OLD."missing_required_fields", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."reportable_event_type", OLD."responsibility_scope", OLD."srp_reference_id", OLD."srp_reference_url", OLD."status", OLD."timer_started_at", OLD."title", OLD."updated_dt", OLD."uuid"); RETURN NULL;',
                    hash="0e4fa3fd1353c2815fb001ad887fd29d3b8c92c3",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a5222",
                    table="regulatory_reporting_srpreport",
                    when="AFTER",
                ),
            ),
        ),
    ]
