# Generated by Django 5.2.16 on 2026-08-31 10:05

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0011_remove_srpreport_update_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='srpreportmilestone',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='srpreportmilestone',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='srpreportmilestone',
            name='update_update',
        ),
        migrations.AddField(
            model_name='srpreportmilestone',
            name='owner',
            field=models.CharField(blank=True, help_text='Owner of this milestone', max_length=60),
        ),
        migrations.AddField(
            model_name='srpreportmilestone',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was submitted', null=True),
        ),
        migrations.AddField(
            model_name='srpreportmilestoneaudit',
            name='owner',
            field=models.CharField(blank=True, help_text='Owner of this milestone', max_length=60),
        ),
        migrations.AddField(
            model_name='srpreportmilestoneaudit',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was submitted', null=True),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['owner'], name='regulatory__owner_05dc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='srpreportmilestone',
            index=models.Index(fields=['submitted_at'], name='regulatory__submitt_5c7b82_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'insert\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='fb01a833a42bf03f17c8d7a0238f522a874efbdb', operation='INSERT', pgid='pgtrigger_insert_insert_53837', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."acl_read" IS DISTINCT FROM (NEW."acl_read") OR OLD."acl_write" IS DISTINCT FROM (NEW."acl_write") OR OLD."created_dt" IS DISTINCT FROM (NEW."created_dt") OR OLD."embargoed" IS DISTINCT FROM (NEW."embargoed") OR OLD."last_validated_dt" IS DISTINCT FROM (NEW."last_validated_dt") OR OLD."manual_completion_notes" IS DISTINCT FROM (NEW."manual_completion_notes") OR OLD."milestone_type" IS DISTINCT FROM (NEW."milestone_type") OR OLD."missing_required_fields" IS DISTINCT FROM (NEW."missing_required_fields") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."request_received_at" IS DISTINCT FROM (NEW."request_received_at") OR OLD."request_source" IS DISTINCT FROM (NEW."request_source") OR OLD."request_text" IS DISTINCT FROM (NEW."request_text") OR OLD."srp_report_id" IS DISTINCT FROM (NEW."srp_report_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."submitted_at" IS DISTINCT FROM (NEW."submitted_at") OR OLD."updated_dt" IS DISTINCT FROM (NEW."updated_dt") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (NEW."acl_read", NEW."acl_write", NEW."created_dt", NEW."last_validated_dt", NEW."manual_completion_notes", NEW."milestone_type", NEW."missing_required_fields", NEW."owner", _pgh_attach_context(), NOW(), \'update\', NEW."uuid", NEW."request_received_at", NEW."request_source", NEW."request_text", NEW."srp_report_id", NEW."status", NEW."submitted_at", NEW."updated_dt", NEW."uuid"); RETURN NULL;', hash='a7a03162dc9cec772be67394be0c2faba313cb0d', operation='UPDATE', pgid='pgtrigger_update_update_59a28', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='srpreportmilestone',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "regulatory_reporting_srpreportmilestoneaudit" ("acl_read", "acl_write", "created_dt", "last_validated_dt", "manual_completion_notes", "milestone_type", "missing_required_fields", "owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "request_received_at", "request_source", "request_text", "srp_report_id", "status", "submitted_at", "updated_dt", "uuid") VALUES (OLD."acl_read", OLD."acl_write", OLD."created_dt", OLD."last_validated_dt", OLD."manual_completion_notes", OLD."milestone_type", OLD."missing_required_fields", OLD."owner", _pgh_attach_context(), NOW(), \'delete\', OLD."uuid", OLD."request_received_at", OLD."request_source", OLD."request_text", OLD."srp_report_id", OLD."status", OLD."submitted_at", OLD."updated_dt", OLD."uuid"); RETURN NULL;', hash='3951fcb8254f008bd91cd63b0b57087e8d6c7fac', operation='DELETE', pgid='pgtrigger_delete_delete_a9aad', table='regulatory_reporting_srpreportmilestone', when='AFTER')),
        ),
    ]
