# Generated by Django 5.2.16 on 2026-08-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0011_remove_srpreport_update_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpreport',
            name='reportable_event_type',
            field=models.CharField(choices=[('EXPLOITS_KEV_APPROVED', 'Actively Exploited Vulnerability'), ('MAJOR_INCIDENT_APPROVED', 'Severe Incident')], help_text='Type of event being reported to ENISA', max_length=50),
        ),
        migrations.AlterField(
            model_name='srpreportaudit',
            name='reportable_event_type',
            field=models.CharField(choices=[('EXPLOITS_KEV_APPROVED', 'Actively Exploited Vulnerability'), ('MAJOR_INCIDENT_APPROVED', 'Severe Incident')], help_text='Type of event being reported to ENISA', max_length=50),
        ),
    ]
