# Generated by Django 5.2.16 on 2026-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0012_alter_srpreport_reportable_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpreport',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='empty', help_text='Current status of the SRP report', max_length=20),
        ),
        migrations.AlterField(
            model_name='srpreportaudit',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='empty', help_text='Current status of the SRP report', max_length=20),
        ),
    ]
