# Generated by Django 5.2.16 on 2026-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_reporting', '0012_alter_srpreport_status_alter_srpreportaudit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpreportmilestone',
            name='status',
            field=models.CharField(choices=[('pre_required', 'Pre Required'), ('required', 'Required'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('submitted', 'Submitted'), ('obsolete', 'Obsolete')], default='required', help_text='Current status of the milestone', max_length=20),
        ),
        migrations.AlterField(
            model_name='srpreportmilestoneaudit',
            name='status',
            field=models.CharField(choices=[('pre_required', 'Pre Required'), ('required', 'Required'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('submitted', 'Submitted'), ('obsolete', 'Obsolete')], default='required', help_text='Current status of the milestone', max_length=20),
        ),
    ]
