import re

WHITELIST = ["Spring", "dotnet", "kernel"]

# r'\b\.NET\b' does not match properly because word boundary \b does not cooperate well
# with dot.
WHITELIST_SPECIAL_CASES = [r"(?:\W|^)\.NET\b"]

BLACKLIST = [
    "1Password",
    "ABB netCADOPS",
    "Acronis Cyber Backup",
    "Acronis True Image",
    "Adobe Acrobat and Reader",
    "Adobe Lightroom",
    "Adobe Media Encoder",
    "Advanced SystemCare Ultimate",
    "Advantech",
    "AEF CMS",
    "Afian FileRun",
    "Ajenti",
    "ALPS ALPINE touchpad driver",
    "AnchorCMS",
    "AntSword",
    "Anuko Time Tracker",
    "Apache Geode",
    "Apache NiFi",
    "Apache OpenMeetings",
    "Apache ShenYu",
    "Apache Syncope",
    "Apache Wicket",
    "Apexis",
    "APNGDis",
    "AppFormix",
    "Arista EOS",
    "ArsenoL",
    "Artica Web Proxy",
    "ASANHAMAYESH CMS",
    "Atlassian Bamboo",
    "Atlassian Confluence",
    "Atlassian Crucible",
    "Atlassian Fisheye",
    "Atlassian JIRA",
    "Aurea Jive",
    "Automation License Manager",
    "Avaya",
    "Avira",
    "Avolve Software ProjectDox",
    "AxxonSoft",
    "BEESCMS",
    "Bento4",
    "BigBlueButton",
    "BigTree CMS",
    "Bitcoin Core",
    "Bitdefender Antivirus",
    "Bitdefender Engines",
    "BlackBerry QNX Software Development Platform",
    "BlackBerry UEM Management Console",
    "BlackCat CMS",
    "Bludit",
    "BMC Medical",
    "BMC Remedy Action Request",
    "BMC Remedy AR System",
    "Bookme Control Panel",
    "bootstrap-table",
    "Bravo Tejari",
    "Brocade Fabric OS",
    "Brocade Fibre",
    "Brocade SANnav",
    "BtiTracker",
    "CactusVPN",
    "Call for Papers",
    "Carbon Black",
    "CCN-lite",
    "Centum CS",
    "ChemCMS",
    "Cisco",
    "Citrix NetScaler",
    "Claymore Dual Miner",
    "CloudMe",
    "CloudVision Portal",
    "Clustered Data ONTAP",
    "CMS Made Simple",
    "CMSuno",
    "CoDeSys Runtime",
    "Combodo iTop",
    "comforte SWAP",
    "Composr CMS",
    "Codoforum",
    "Contiki-NG",
    r"Converse\.js",
    "CoverCMS",
    "Cozy",
    "Creditwest Bank CMS",
    "Cybozu Garoon",
    "Dataiku DSS",
    "DedeCMS",
    "Dell EMC",
    "Dell SonicWALL Scrutinizer",
    "Dell Storage Manager",
    "Delta Electronics",
    "Desigo",
    "Digital Guardian Managment Console",
    "DiliCMS",
    "DiligentCMS",
    "Discuz",
    "Disk Savvy Enterprise",
    r"D-LINK DIR.*",
    "DocuTrac QuicDoc",
    "DomainMOD",
    "dotCMS",
    "drawio",
    "EasyCMS",
    "Eaton's",
    "eDNA Enterprise Data Historian",
    r"ednareporting\.asmx",
    "EMC Data Protection Advisor",
    "Enalean Tuleap",
    "Enhancesoft osTicket",
    "enhavo CMS",
    "EPIC MyChart",
    "Epson Airprint",
    "Eshtery CMS",
    "Explzh",
    "Exponent CMS",
    "F5 BIG-IP",
    "FactoryTalk",
    "FastAdmin",
    "FastCMS",
    r"FeMiner.*wms",
    "FiberHome",
    "Flexense DiskBoss",
    "Flexense DiskPulse",
    "Flexense DiskSavvy",
    "Flexense DiskSorter",
    "Flexense DupScout",
    "Flexense SyncBreeze",
    "Flexense VX Search",
    "ForgeRock",
    "FortiAnalyzer",
    "FortiClient",
    "FortiNAC",
    "Fortinet",
    "FortiOS",
    "Frog CMS",
    "FusionCompute",
    "FusionSphere OpenStack",
    "Gallagher Command Centre",
    "Galileo CMS",
    "GE D60",
    "Geist WatchDog Console",
    "Gemini-Net",
    "GeniXCMS",
    "GetSimple CMS",
    "GetSimpleCMS",
    "Gleez CMS",
    "GPAC ",
    "GSKit",
    "GXCMS",
    "Gxlcms",
    "HashiCorp Terraform",
    "Hewlett Packard Enterprise Intelligent Management Center",
    "Hewlett Packard Enterprise Moonshot Provisioning Manager",
    "HongCMS",
    "Horizon Client for Windows",
    "HPE Aruba AirWave Glass",
    "HPE Aruba ClearPass Policy Manager",
    "HPE Business Process Monitor",
    "HPE Cloud Optimizer",
    "HPE Data Protector",
    "HPE Diagnostics",
    "HPE Helion Eucalyptus",
    "HPE IceWall Federation Agent",
    "HPE iMC PLAT",
    "HPE Insight Control",
    "HPE Integrated Lights-Out",
    "HPE Intelligent Management Center",
    "HPE LoadRunner",
    "HPE Matrix Operating Environment",
    "HPE Network Automation",
    "HPE Network Node Manager",
    "HPE NonStop Server",
    "HPE NonStop Software Essentials",
    "HPE OfficeConnect Network Switches",
    "HPE OpenCall Media Platform",
    "HPE Operations Bridge Analytics",
    "HPE Operations Orchestration Community",
    "HPE Pay Per Use",
    "HPE Project and Portfolio Management",
    "HPE SiteScope",
    "HPE Smart Storage Administrator",
    "HPE StoreVirtual",
    "HPE Systems Insight Manager",
    "HPE UCMDB",
    "HPE Version Control Repository Manager",
    "HPE Vertica Analytics",
    "HP Security",
    "https://github.com/kabirkhyrul/HMS/",
    "https://www.solarwinds.com/",
    "IBM API Connect",
    "IBM AppScan",
    "IBM Aspera Web Application",
    "IBM BigFix",
    "IBM Business Automation Content Analyzer",
    "IBM Business Automation Workflow",
    "IBM Business Process Manager",
    "IBM Campaign",
    "IBM Capacity Management Analytics",
    "IBM Cognos",
    "IBM Connections",
    "IBM Content Manager",
    "IBM Content Navigator",
    "IBM Curam",
    "IBM DataPower Gateway",
    "IBM Data Risk Manager",
    "IBM Daeja ViewONE",
    "IBM Doors",
    "IBM Emptoris",
    "IBM Endpoint Manager",
    "IBM Event Streams",
    "IBM Financial Transaction Manager",
    "IBM Flex System",
    "IBM Forms Experience Builder",
    "IBM Forms Server",
    "IBM i2 iBase",
    "IBM InfoSphere",
    "IBM Jazz Foundation",
    "IBM Jazz Reporting Service",
    "IBM Maximo",
    "IBM MQ Appliance",
    "IBM Notes",
    "IBM Planning Analytics",
    "IBM Power Hardware Management Console",
    "IBM Publishing Engine",
    "IBM QRadar",
    "IBM Rational",
    "IBM Rhapsody",
    "IBM Robotic",
    "IBM RSA DM",
    "IBM Sametime",
    "IBM Secure External Authentication Server",
    "IBM Security Access Manager",
    "IBM Security Guardium",
    "IBM Security Identity Governance and Intelligence",
    "IBM Security Key Lifecycle Manager",
    "IBM Security QRadar",
    "IBM Security Secret Server",
    "IBM Security SiteProtector",
    "IBM Security Trusteer Pinpoint Detect",
    "IBM Spectrum Protect Plus",
    "IBM Spectrum Scale",
    "IBM Sterling B2B Integrator",
    "IBM Sterling Connect:Direct",
    "IBM Sterling File Gateway",
    "IBM Sterling Secure Proxy",
    "IBM Tealeaf",
    "IBM Tivoli",
    "IBM TRIRIGA",
    "IBM UrbanCode Deploy",
    "IBM WebSphere",
    "IBM XIV Storage",
    "iDashboards",
    "I-librarian",
    "I, Librarian",
    "Imagely NextGEN Gallery",
    "ImageWorsener",
    "InHand Networks",
    "Insurance Management System",
    "InspIRCd",
    "Intelbras TELEFONE IP",
    "Intel(R) Graphics Drivers",
    "Intel (R) LED Manager for NUC",
    "Intel(R) PAC with Arria(R)",
    "Intel(R) Server Boards",
    "Intel Server Boards",
    "Invision Power Board",
    "IOBit Malware Fighter",
    "IonizeCMS",
    "iPayPal",
    "Ipswitch WhatsUp Gold",
    "iRedMail",
    "iScripts eSwap",
    "iScripts SupportDesk",
    "iScripts UberforX",
    "ismartgate PRO",
    "iTunes",
    "Ivanti Endpoint Security",
    "JEXTN",
    "JerryScript",
    "JFrog Artifactory",
    "Jiangmin Antivirus",
    "Jirafeau",
    "Joomla!",
    "Joyent SmartOS",
    "joyplus-cms",
    "JupyterHub OAuthenticator",
    "JT2Go",
    "Kaspersky Secure Mail",
    "Kentico",
    "Kingsoft Internet Security",
    "Kliqqi CMS",
    "LAquis SCADA",
    "Liferay Portal",
    "LogicalDoc",
    "Loway QueueMetrics",
    "lyadmin",
    "madlib-object-utils",
    "Mahara",
    "Mailbutler Shimo",
    "Malwarebytes Anti-Malware",
    "MalwareFox AntiMalware",
    "ManageEngine Service Desk Plus",
    "March Hare WINCVS",
    "MB CONNECT LINE",
    "McAfee Network Security Management",
    "McAfee VirusScan Enterprise",
    "MetInfo",
    "Micro Focus ArcSight Management Center",
    "Micro Focus Project",
    "Micro Focus UCMDB",
    "Micro Focus Universal CMDB",
    "Micropoint proactive",
    "Microsoft",
    "Microweber",
    "MikroTik's RouterOS",
    "MiniCMS",
    "Mitel ST",
    "Mitsubishi E-Designer",
    "Mobotix",
    "Money Transfer Management System",
    "Monstra CMS",
    "Moxa OnCell",
    "MP Form Mail",
    "MTS Simple Booking",
    "Navarino Infinity",
    "NetEx HyperIP",
    "NETGEAR",
    "NetIQ Access Manager",
    "NetIQ Identity Manager",
    "NetIQ Identity Reporting",
    "NetIQ iManager",
    "Niagara",
    "Nokia",
    "NordVPN",
    "Nortek Linear",
    "NVIDIA GeForce NOW",
    "October CMS",
    "Omron CX-One",
    "Omron CX-Supervisor",
    "Online Sports Complex Booking System",
    "Opencast",
    "Open-AudIT Professional",
    "OpenEMR",
    "OpenScape Deployment Service",
    "OSIsoft PI",
    "OTCMS",
    "OXID eShop",
    "Ozeki NG SMS Gateway",
    "Paessler PRTG Network Monitor",
    "PAN-OS",
    "Parallels Remote Application Server",
    "PayPal",
    "Pega Platform",
    "Pegasystems Pega Platform",
    "Philips Intellispace Portal",
    "PHP Scripts Mall",
    "PHPGurukul",
    "phpjs",
    "PicturesPro Photo Cart",
    "Piwigo",
    "Pixar OpenUSD",
    "Plixer Scrutinizer",
    "Pluck",
    r".*plugin.*for WordPress",
    "POSCMS",
    "prime-jwt",
    "PrivateVPN",
    "Project-Pier",
    "Promise Technology",
    "publify",
    "Pulse Connect Secure",
    "Pulse Secure Desktop Client",
    "PureVPN",
    "QNAP QTS",
    "Quest NetVault",
    "QuickTime",
    "rap2hpoutre Laravel Log Viewer",
    "Rapid Software LLC Rapid SCADA",
    "Red Discord Bot",
    "Rocket.Chat",
    "RosarioSIS",
    "Ruckus Networks",
    "Sagemcom",
    "Sandoba CP:Shop",
    "SAP 3D Visual Enterprise Viewer",
    "SAP Adaptive Server Enterprise",
    "SAP Banking Services",
    "SAP BASIS",
    "SAP Business Objects Business Intelligence Platform",
    "SAP Commerce versions",
    "SAP Data Hub",
    "SAP Fiori Launchpad",
    "SAP Marketing",
    "Saperion Web Client",
    "SAP ERP",
    "SAP NetWeaver",
    "Schneider Electric",
    "Seagate Media Server",
    "Shimmie",
    "ShopXO",
    "SICAM",
    r"SIMATIC.*(PCS|CP)",
    "Simple Client Management System",
    "SnapCreek Duplicator",
    "Sophos Endpoint Protection",
    "SourceCodester",
    "SpamTitan",
    "SpiderControl MicroBrowser",
    "Square 9 GlobalForms",
    "Stormshield Network Security",
    "Sumatra PDF",
    "Symantec",
    "Synacor Zimbra",
    "Synology DiskStation Manager",
    "Synology Photo",
    "Synology Router Manager",
    "Synology Surveillance Station",
    "Sysax Multi Server",
    "Telegram Desktop",
    "Tenda AC15",
    "Tenda AC9",
    "TIBCO DataSynapse GridServer Manager",
    "totaljs",
    "TreasuryXpress",
    "Trend Micro",
    "TRENDNet",
    "trudesk",
    "TuziCMS",
    "Twonky Server",
    "Ubiquiti Networks EdgeOS",
    "Unisys ClearPath",
    "Unisys Stealth SVG",
    "United Planet Intrexx Professional",
    "Unitrends Backup",
    "Untis WebUntis",
    "Userscape HelpSpot",
    "vBulletin",
    "Verint Workforce Optimization",
    "Vesta Control Panel",
    "Victor CMS",
    "VirtueMart",
    "VMware ESXi and vCenter Server",
    "VMware Fusion",
    "VMware Workstation",
    "WatchDog Anti-Malware",
    "WBCE CMS",
    "WebDynpro Java",
    "Weblication CMS",
    "WECON LeviStudioU",
    "Weeny Audio Cutter",
    "Western Bridge Cobub Razor",
    "Western Digital My Cloud",
    r"win32k\.sys",
    "Winmail",
    "Wireless IP Camera 360",
    "WonderCMS",
    r"WordPress.*plugin",
    "WoWonder",
    "Wowza Streaming",
    "WPS Office",
    "WSO2 Enterprise Integrator",
    "WTCMS",
    "WUZHI CMS",
    "Xiuno BBS",
    "XYHCMS",
    "Yab Quarx",
    "Yahoo!",
    "Yxcms",
    "YxtCMF",
    "YzmCMS",
    "Z-BlogPHP",
    "Zikula Application Framework",
    "Zoho ManageEngine",
    "ZoneAlarm",
    "Zulip Desktop",
    "zzcms",
]

BLACKLIST_CASE_SENSITIVE = ["iOS"]

KEYWORD_WHITELIST = [
    re.compile(rf"\b{keyword}\b", re.IGNORECASE) for keyword in WHITELIST
] + [re.compile(keyword) for keyword in WHITELIST_SPECIAL_CASES]

KEYWORD_BLACKLIST = [
    re.compile(rf"\b{keyword}\b", re.IGNORECASE) for keyword in BLACKLIST
] + [re.compile(rf"\b{keyword}\b") for keyword in BLACKLIST_CASE_SENSITIVE]


def check_keywords(text):
    """
    Checks if a specified text is relevant or not based on found keywords.

    Returns tuple of matched blacklisted and whitelisted keywords.
    """
    whitelist = []
    for word in (regex.search(text) for regex in KEYWORD_WHITELIST):
        if word is not None:
            whitelist.append(word.group().strip())

    blacklist = []
    for word in (regex.search(text) for regex in KEYWORD_BLACKLIST):
        if word is not None:
            blacklist.append(word.group())

    return sorted(blacklist), sorted(whitelist)


def should_create_snippet(text):
    """
    Returns True if a snippet should be created, False otherwise.

    Snippet should be created if:
        words in `text` are in both whitelist and blacklist ([x], [x])
        words in `text` are in whitelist only               ([x], [])
        words in `text` are not in whitelist or blacklist   ([], [])

    Snippet should not be created if:
        words in `text` are in blacklist only               ([], [x])
        `text` is empty
    """
    if not text:
        return False

    blacklist, whitelist = check_keywords(text)

    return False if (blacklist and not whitelist) else True
