name: Lint
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Check for secret leakage
        run: uvx tox -e secrets
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Lint codebase and check it for security issues with ruff
        run: uvx tox -e ruff-check
  ruff-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Check that imports are formatted with ruff
        run: uvx tox -e ruff-isort
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Check that code is formatted with ruff
        run: uvx tox -e ruff-format
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Install required ubuntu packages
        run: sudo apt update && sudo apt install libkrb5-dev build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Ensure Django migrations have been generated
        run: uvx tox -e migrations
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Install required ubuntu packages
        run: sudo apt update && sudo apt install libkrb5-dev build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Install tox and tox-uv
        run: uv tool install tox==4.28.1 -w tox-uv==1.26.2
      - name: Ensure the OpenAPI schema has been generated
        run: uvx tox -e schema-check
